<!--
Generated by SKILL-NUXT (W7 #281).
Default layout — ships a semantic landmark header + main + footer
so the W5 WCAG gate passes without additional markup. Layouts in
Nuxt 4 are auto-registered from the `layouts/` directory.
-->

<template>
  <div class="app-shell">
    <header role="banner">
      <nav aria-label="primary">
        <NuxtLink to="/">Home</NuxtLink>
        <NuxtLink to="/about">About</NuxtLink>
      </nav>
    </header>
    <main id="main" role="main">
      <slot />
    </main>
    <footer role="contentinfo">
      <small>Generated by SKILL-NUXT (W7 #281)</small>
    </footer>
  </div>
</template>

<style>
.app-shell {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}
.app-shell > main {
  flex: 1;
}
</style>
