<!--
Generated by SKILL-NUXT (W7 #281).
Minimal GDPR/ePrivacy cookie-banner — first-party consent manager.
Stores the decision in a first-party cookie and emits a custom
event so the rest of the app can toggle analytics / personalization
trackers on acceptance. Recognised by backend.web_compliance.gdpr
via the "cookie-banner" / "cookieconsent" signatures below.
-->

<script setup lang="ts">
type Decision = "accept" | "reject"
const COOKIE = "consent_v1"
const decision = ref<Decision | null>(null)

function read(): Decision | null {
  if (typeof document === "undefined") return null
  const m = document.cookie.match(/(?:^|; )consent_v1=([^;]+)/)
  return m ? (decodeURIComponent(m[1]) as Decision) : null
}

function write(value: Decision) {
  const oneYear = 60 * 60 * 24 * 365
  document.cookie = `${COOKIE}=${value}; Path=/; Max-Age=${oneYear}; SameSite=Lax; Secure`
  window.dispatchEvent(new CustomEvent("consent:update", { detail: value }))
  decision.value = value
}

onMounted(() => {
  decision.value = read()
})
</script>

<template>
  <div
    v-if="decision === null"
    role="dialog"
    aria-labelledby="consent-heading"
    aria-describedby="consent-desc"
  >
    <h2 id="consent-heading">Cookie preferences</h2>
    <p id="consent-desc">
      We use strictly necessary cookies by default. Optional analytics
      cookies help us improve the product — your choice.
    </p>
    <button type="button" @click="write('accept')">Accept</button>
    <button type="button" @click="write('reject')">Reject optional</button>
  </div>
</template>
