// Generated by SKILL-NUXT (W7 #281).
// Smoke E2E — confirms a cold boot of the generated app serves the
// home page and the health route responds. If either fails, the W2
// simulate-track Playwright gate will also fail.

import { test, expect } from "@playwright/test"

test("home page renders heading", async ({ page }) => {
  await page.goto("/")
  await expect(page.getByRole("main")).toBeVisible()
  await expect(page.getByRole("heading", { level: 1 })).toBeVisible()
})

test("health endpoint returns ok", async ({ request }) => {
  const res = await request.get("/api/health")
  expect(res.status()).toBe(200)
  const body = await res.json()
  expect(body.status).toBe("ok")
})

test("counter button increments", async ({ page }) => {
  await page.goto("/")
  const button = page.getByRole("button", { name: /increment counter/i })
  await expect(button).toContainText("Count: 0")
  await button.click()
  await expect(button).toContainText("Count: 1")
})

test("about page navigates via vue-router", async ({ page }) => {
  await page.goto("/")
  await page.getByRole("link", { name: "About" }).click()
  await expect(page).toHaveURL(/\/about$/)
  await expect(page.getByRole("heading", { name: "About" })).toBeVisible()
})
