// Generated by SKILL-DESKTOP-TAURI (X8 #304).
//
// Tauri 2.x build script. `tauri_build::build()` reads tauri.conf.json,
// validates the bundle.identifier + capabilities, generates code-side
// command bindings, and emits cargo:rerun-if-changed entries for the
// frontend dist directory so `cargo build` retriggers when the SPA
// rebuilds.

fn main() {
    tauri_build::build()
}
