<!--
Generated by SKILL-NUXT (W7 #281).
Secondary page — exists to prove the pages-based Vue Router wired
up correctly. Nuxt auto-generates a route for `/about` from this
file; no manual router.ts needed. frontend-vue role prefers the
pages/ convention to explicit router config.
-->

<script setup lang="ts">
definePageMeta({
  title: "About",
})
</script>

<template>
  <article aria-labelledby="about-heading">
    <h1 id="about-heading">About</h1>
    <p>
      This project was generated by SKILL-NUXT (W7 #281). See
      <code>docs/privacy/retention.md</code> for the data retention
      policy and <code>spdx.allowlist.json</code> for the license
      allowlist.
    </p>
  </article>
</template>
