<!--
Generated by SKILL-NUXT (W7 #281).
Home page — demonstrates the Nuxt-idiomatic data-fetch pattern:
`useFetch` inside `<script setup>` so SSR hydration works without
double-fetching on the client. frontend-vue role explicitly bans
raw `fetch()` calls from component setup; `useFetch` respects the
request lifecycle and serialises the payload for hydration.
-->

<script setup lang="ts">
definePageMeta({
  title: "Home",
})

const { data: health } = await useFetch<{ status: string; service?: string }>(
  "/api/health",
  { key: "index-health" },
)
</script>

<template>
  <section aria-labelledby="home-heading">
    <h1 id="home-heading">{{ $config.public.appName }}</h1>
    <p>Backend health: {{ health?.status ?? "unknown" }}</p>
    <Counter :initial="0" />
  </section>
</template>
