"use client"

// Generated by SKILL-NEXTJS (W6 #280).
// Minimal GDPR/ePrivacy cookie-banner — first-party consent manager.
// Stores the decision in a first-party cookie and emits a custom
// event so the rest of the app can toggle analytics / personalization
// trackers on acceptance. Recognised by backend.web_compliance.gdpr
// via the "cookie-banner" / "cookieconsent" signatures below.

import { useEffect, useState } from "react"

const COOKIE = "consent_v1"

function read(): "accept" | "reject" | null {
  if (typeof document === "undefined") return null
  const m = document.cookie.match(/(?:^|; )consent_v1=([^;]+)/)
  return m ? (decodeURIComponent(m[1]!) as "accept" | "reject") : null
}

function write(value: "accept" | "reject") {
  const oneYear = 60 * 60 * 24 * 365
  document.cookie = `${COOKIE}=${value}; Path=/; Max-Age=${oneYear}; SameSite=Lax; Secure`
  window.dispatchEvent(new CustomEvent("consent:update", { detail: value }))
}

export function CookieBanner() {
  const [decision, setDecision] = useState<"accept" | "reject" | null>(null)

  useEffect(() => setDecision(read()), [])

  if (decision !== null) return null

  return (
    <div
      role="dialog"
      aria-labelledby="consent-heading"
      aria-describedby="consent-desc"
    >
      <h2 id="consent-heading">Cookie preferences</h2>
      <p id="consent-desc">
        We use strictly necessary cookies by default. Optional analytics
        cookies help us improve the product — your choice.
      </p>
      <button type="button" onClick={() => { write("accept"); setDecision("accept") }}>
        Accept
      </button>
      <button type="button" onClick={() => { write("reject"); setDecision("reject") }}>
        Reject optional
      </button>
    </div>
  )
}
