// Generated by SKILL-NEXTJS (W6 #280). SC.6.3 security headers.
// Root middleware auto-registers for rendered Next.js projects and
// keeps origin-level browser hardening in place across deploy targets.

import { NextResponse } from "next/server"
import type { NextRequest } from "next/server"

const SECURITY_HEADERS: Array<[string, string]> = [
  ["Content-Security-Policy", "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; connect-src 'self' https:; frame-ancestors 'none'; base-uri 'self'; form-action 'self'"],
  ["Strict-Transport-Security", "max-age=31536000; includeSubDomains; preload"],
  ["X-Frame-Options", "DENY"],
  ["X-Content-Type-Options", "nosniff"],
  ["Referrer-Policy", "strict-origin"],
  ["Permissions-Policy", "camera=(), microphone=(), geolocation=(), payment=()"],
  ["Cross-Origin-Resource-Policy", "same-origin"],
  ["Cross-Origin-Embedder-Policy", "require-corp"],
  ["Cross-Origin-Opener-Policy", "same-origin"],
]

export function middleware(_request: NextRequest) {
  const response = NextResponse.next()
  for (const [header, value] of SECURITY_HEADERS) {
    response.headers.set(header, value)
  }
  return response
}

export const config = {
  matcher: [
    "/((?!api|_next/static|_next/image|favicon.ico|icon-.*\\.png|apple-icon\\.png|icon\\.svg).*)",
  ],
}
