"""Scaffold: customer USB camera wired to the prebuilt uvc-uac-app (usb-cam).

The USB-side mirror of the ipcam pack's prebuilt_rtsp_onvif_integration.
A customer USB-camera product *reuses* the tested omnisight/uvc-uac-app
gadget firmware (the board becomes a standard USB UVC[+UAC] device)
instead of regenerating a gadget stack.

Given product params, a target SoC, a pinned release tag, a packaging
system (Yocto / Buildroot / Debian), and a device MODE, this renders:

  * a product manifest pinning the firmware release + board profile,
  * a tailored on-device profile (UVC-only vs UVC+UAC; identity stub),
  * packaging glue (Yocto SRCREV pin / Buildroot defconfig / .deb),
  * a smoke checklist (host enumerates the UVC[/UAC] device).

MODE captures the real product split:
  * UVC_ONLY    — pure camera: laptop module / Windows Hello / AI
                  streaming-input stick (no audio endpoint).
  * UVC_UAC     — camera + mic/speaker: conferencing, medical/industrial.

Pure-Python / stdlib so it renders offline in CI.

Usage:
    from prebuilt_uvc_uac_integration import Packaging, Mode, render_integration
    art = render_integration(
        product="acme-streamcam", soc="rk3588", release_tag="v0.1.0",
        packaging=Packaging.YOCTO, mode=Mode.UVC_ONLY,
        manufacturer="Acme", product_name="StreamCam-1")
"""
from __future__ import annotations

import enum
from dataclasses import dataclass, field

FIRMWARE_REPO = "omnisight/uvc-uac-app"

# SoC -> the uvc-uac-app HAL profile id. Only rk3588 ships a profile today;
# the rest are HAL-supported but profile/HIL-pending (component board
# matrix). Unknown/unprofiled SoCs render a profile stub + a loud warning.
_SOC_PROFILE = {"rk3588": "rk3588"}
_PROFILED_SOCS = frozenset(_SOC_PROFILE)
# has_vpu == hardware H.264/H.265; i.MX93 and AM62x have no VPU -> MJPEG/YUV
# or software encode only (a real product-decision flag).
_NO_VPU_SOCS = frozenset({"imx93", "am62x"})


class Packaging(enum.Enum):
    YOCTO = "yocto"
    BUILDROOT = "buildroot"
    DEBIAN = "debian"


class Mode(enum.Enum):
    UVC_ONLY = "uvc-only"   # pure camera, no audio endpoint
    UVC_UAC = "uvc-uac"     # camera + audio (mic/speaker)


@dataclass
class IntegrationArtifacts:
    manifest: dict
    profile_yaml: str
    packaging_glue: str
    smoke_checklist: list[str] = field(default_factory=list)


def profile_for_soc(soc: str) -> str:
    return _SOC_PROFILE.get(soc, f"{soc}")


def soc_has_profile(soc: str) -> bool:
    return soc in _PROFILED_SOCS


def soc_has_vpu(soc: str) -> bool:
    return soc not in _NO_VPU_SOCS


def render_profile_yaml(*, soc: str, mode: Mode, manufacturer: str,
                        product_name: str, uvc_version: str = "1.5",
                        uac_version: str = "2.0") -> str:
    has_vpu = soc_has_vpu(soc)
    # encode formats depend on VPU presence
    if has_vpu:
        video_formats = (
            "    - { codec: NV12,  uvc: uncompressed }\n"
            "    - { codec: MJPEG, uvc: mjpeg }\n"
            "    - { codec: H264,  uvc: framebased }\n"
            "    - { codec: H265,  uvc: framebased }\n"
        )
    else:
        # no hardware encoder: uncompressed + MJPEG (software) only
        video_formats = (
            "    - { codec: NV12,  uvc: uncompressed }\n"
            "    - { codec: YUYV,  uvc: uncompressed }\n"
            "    - { codec: MJPEG, uvc: mjpeg }   # software encode (no VPU)\n"
        )
    audio = ""
    if mode is Mode.UVC_UAC:
        audio = (
            "\naudio:\n"
            f"  uac_version: \"{uac_version}\"\n"
            "  capture:   { card: \"hw:0,0\", rates: [48000, 16000], channels: 2, format: s16le }\n"
            "  playback:  { card: \"hw:0,0\", rates: [48000], channels: 2, format: s16le }\n"
        )
    return (
        "# Generated by the usb-cam prebuilt-firmware integration.\n"
        f"# Mode: {mode.value}. Fill (BOARD) values before shipping.\n"
        "profile:\n"
        f"  name: {soc}\n"
        f"  soc: {soc}\n"
        "usb:\n"
        "  udc:  { match: \"*.usb\" }          # (BOARD) prefer-list per board\n"
        "  role: { mechanism: dwc3-sysfs, default: device }\n"
        "buffer:\n"
        "  heap: auto                          # dma-heap >=5.6, ion/cma fallback\n"
        "camera:\n"
        "  backend: v4l2\n"
        "  device: \"/dev/video0\"             # (BOARD) stable udev symlink\n"
        "encoder:\n"
        f"  has_vpu: {'true' if has_vpu else 'false'}\n"
        "video:\n"
        "  formats:\n"
        f"{video_formats}"
        f"  uvc_version: \"{uvc_version}\"\n"
        f"{audio}"
        "device:\n"
        "  vendor_id: 0x1d6b                   # (BOARD) your assigned VID\n"
        "  product_id: 0x0102                  # (BOARD)\n"
        f"  manufacturer: \"{manufacturer}\"\n"
        f"  product: \"{product_name}\"\n"
        "  serial: \"\"                        # (BOARD) per-unit serial\n"
    )


def _yocto_glue(release_tag: str) -> str:
    return (
        "# Yocto: add uvc-uac-app's integration/yocto layer and pin.\n"
        'IMAGE_INSTALL:append = " uvc-uac-app"\n'
        f'SRCREV:pn-uvc-uac-app = "{release_tag}"\n'
    )


def _buildroot_glue(release_tag: str) -> str:
    return (
        "# Buildroot: BR2_EXTERNAL -> uvc-uac-app integration/buildroot.\n"
        "BR2_PACKAGE_UVC_UAC_APP=y\n"
        f'BR2_PACKAGE_UVC_UAC_APP_VERSION="{release_tag}"\n'
    )


def _debian_glue(release_tag: str) -> str:
    return (
        "# Debian/vendor rootfs: cross-build the pinned release and pack a\n"
        "# .deb (integration/debian/build-deb.sh). UVCUAC_STATIC_CXX=ON\n"
        "# recommended for old vendor rootfs.\n"
        f"# git checkout {release_tag} && cmake --preset <board> && \\\n"
        "#   integration/debian/build-deb.sh build/<board>\n"
    )


def render_integration(*, product: str, soc: str, release_tag: str,
                       packaging: Packaging, mode: Mode, manufacturer: str,
                       product_name: str) -> IntegrationArtifacts:
    if not product:
        raise ValueError("product name is required")
    if not release_tag:
        raise ValueError("release_tag is required (pin the firmware release)")
    if not isinstance(packaging, Packaging):
        raise TypeError("packaging must be a Packaging enum")
    if not isinstance(mode, Mode):
        raise TypeError("mode must be a Mode enum")

    profile = profile_for_soc(soc)
    manifest = {
        "product": product,
        "soc": soc,
        "firmware": {
            "repo": FIRMWARE_REPO,
            "release_tag": release_tag,
            "packaging": packaging.value,
        },
        "mode": mode.value,
        "hal_profile": profile,
        "hal_profile_verified": soc_has_profile(soc),
        "hardware_encode": soc_has_vpu(soc),
    }

    glue = {
        Packaging.YOCTO: _yocto_glue,
        Packaging.BUILDROOT: _buildroot_glue,
        Packaging.DEBIAN: _debian_glue,
    }[packaging](release_tag)

    checklist = [
        "USB enumerate: host sees a UVC video device (lsusb / Device Manager)",
        "Stream: capture frames at an advertised resolution/fps (ffmpeg/OBS)",
    ]
    if mode is Mode.UVC_UAC:
        checklist.append(
            "Audio: host sees the UAC device; mic capture + speaker playback")
    if not soc_has_profile(soc):
        checklist.insert(
            0,
            f"WARNING: {soc} has no verified uvc-uac-app HAL profile yet — "
            "the rendered profile is a (BOARD) stub; add a board profile + "
            "on-target HIL validation (component board matrix) before "
            "production.")
    if not soc_has_vpu(soc):
        checklist.insert(
            0,
            f"NOTE: {soc} has no VPU — H.264/H.265 unavailable; product is "
            "limited to MJPEG / uncompressed (software encode).")

    return IntegrationArtifacts(
        manifest=manifest,
        profile_yaml=render_profile_yaml(
            soc=soc, mode=mode, manufacturer=manufacturer,
            product_name=product_name),
        packaging_glue=glue,
        smoke_checklist=checklist,
    )


if __name__ == "__main__":
    import json

    art = render_integration(
        product="acme-streamcam", soc="rk3588", release_tag="v0.1.0",
        packaging=Packaging.YOCTO, mode=Mode.UVC_ONLY,
        manufacturer="Acme", product_name="StreamCam-1")
    print(json.dumps(art.manifest, indent=2))
    print(art.profile_yaml)
    print(art.packaging_glue)
    print("\n".join(art.smoke_checklist))
