"""C26 — Pluggable LLM backend for HMI generation.

Three providers:
    1. ``anthropic`` — Opus 4.7 Design Tool (when API key is set)
    2. ``ollama``    — Local model (when ``OMNISIGHT_LLM_PROVIDER=ollama``)
    3. ``rule_based`` — deterministic keyword-driven fallback

Selection order:
    * Explicit ``provider`` kwarg
    * ``HMI_LLM_PROVIDER`` env (C26-specific override)
    * ``OMNISIGHT_LLM_PROVIDER`` env (project-wide default)
    * Falls back to ``rule_based`` so offline CI / embedded minimal
      images never error out.

The LLM is intentionally sandboxed: its output is used only for
non-structural enrichment (description text, field docstrings). All
C handler / JS client skeletons are produced deterministically by
``hmi_binding`` regardless of the LLM provider.
"""

from __future__ import annotations

import logging
import os
from dataclasses import dataclass
from typing import Any

logger = logging.getLogger(__name__)

LLM_VERSION = "1.0.0"

SUPPORTED_PROVIDERS = ("anthropic", "ollama", "rule_based")


@dataclass
class EnrichedBinding:
    description: str
    provider: str
    used_real_llm: bool


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  Provider selection
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


def choose_provider(explicit: str | None = None) -> str:
    candidate = (
        explicit
        or os.environ.get("HMI_LLM_PROVIDER")
        or os.environ.get("OMNISIGHT_LLM_PROVIDER")
        or "rule_based"
    )
    candidate = (candidate or "").strip().lower()
    if candidate == "anthropic":
        if not os.environ.get("ANTHROPIC_API_KEY"):
            logger.info("anthropic provider requested but ANTHROPIC_API_KEY not set — falling back to rule_based")
            return "rule_based"
        return "anthropic"
    if candidate == "ollama":
        if not os.environ.get("OLLAMA_BASE_URL") and not os.environ.get("OLLAMA_HOST"):
            # Ollama default URL is fine; provider stays
            return "ollama"
        return "ollama"
    return "rule_based"


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  Rule-based backend (always available)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


_KEYWORD_HINTS = {
    "wifi": "Wi-Fi configuration endpoint — connect, disconnect, list SSIDs",
    "network": "Network settings — DHCP, static IP, VLAN, MAC filters",
    "ota": "OTA firmware update — upload, verify, apply, rollback",
    "log": "Log query — tail, search, export",
    "reboot": "Device reboot / factory reset",
    "camera": "Camera stream control — bitrate, resolution, codec",
    "gpio": "GPIO pin control — read, write, interrupt",
    "sensor": "Sensor telemetry — read, calibrate, zero",
    "auth": "Authentication — login, logout, MFA, session refresh",
    "user": "User management — CRUD, roles, passwords",
}


def _rule_based(prompt: str, endpoint: Any) -> str:
    prompt_l = (prompt or "").lower()
    matches = [hint for kw, hint in _KEYWORD_HINTS.items() if kw in prompt_l]
    base = "; ".join(matches) if matches else "HMI binding"
    method = getattr(endpoint, "method", "POST")
    path = getattr(endpoint, "path", "/")
    req_count = len(getattr(endpoint, "request_fields", []) or [])
    resp_count = len(getattr(endpoint, "response_fields", []) or [])
    return (
        f"{base} ({method} {path}); {req_count} request field(s), "
        f"{resp_count} response field(s). Generated by rule-based fallback."
    )


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  Anthropic / Ollama backends (lazy import)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


def _try_anthropic(prompt: str, endpoint: Any) -> str | None:
    try:
        import anthropic  # type: ignore[import-not-found]
    except Exception:
        return None
    try:
        client = anthropic.Anthropic()
        model = os.environ.get("ANTHROPIC_MODEL", "claude-opus-4-7")
        system = (
            "You are a senior embedded engineer writing HMI binding docs. "
            "Respond with ONE concise sentence describing the endpoint intent."
        )
        user = (
            f"HAL endpoint: {getattr(endpoint, 'method', '?')} {getattr(endpoint, 'path', '?')}\n"
            f"Request fields: {[f.name for f in getattr(endpoint, 'request_fields', [])]}\n"
            f"Response fields: {[f.name for f in getattr(endpoint, 'response_fields', [])]}\n"
            f"User intent: {prompt}"
        )
        resp = client.messages.create(
            model=model,
            max_tokens=120,
            system=system,
            messages=[{"role": "user", "content": user}],
        )
        if hasattr(resp, "content") and resp.content:
            block = resp.content[0]
            if hasattr(block, "text"):
                return str(block.text).strip()
    except Exception as exc:
        logger.warning("anthropic enrichment failed: %s", exc)
        return None
    return None


def _try_ollama(prompt: str, endpoint: Any) -> str | None:
    try:
        import urllib.error
        import urllib.request
        import json as _json
    except Exception:
        return None
    try:
        base = os.environ.get("OLLAMA_BASE_URL") or os.environ.get("OLLAMA_HOST") or "http://localhost:11434"
        model = os.environ.get("OLLAMA_MODEL", "llama3.1")
        body = _json.dumps({
            "model": model,
            "prompt": (
                f"Write a one-sentence description of this HMI endpoint.\n"
                f"Endpoint: {getattr(endpoint, 'method', '?')} {getattr(endpoint, 'path', '?')}\n"
                f"Intent: {prompt}"
            ),
            "stream": False,
        }).encode("utf-8")
        req = urllib.request.Request(  # noqa: S310 — trusted local endpoint
            f"{base}/api/generate",
            data=body,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=10) as r:  # noqa: S310
            data = _json.loads(r.read().decode("utf-8"))
            return (data.get("response") or "").strip() or None
    except Exception as exc:
        logger.info("ollama enrichment unavailable: %s", exc)
        return None


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  Public API
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


def enrich_binding_description(
    prompt: str,
    endpoint: Any,
    provider: str | None = None,
) -> EnrichedBinding:
    chosen = choose_provider(provider)
    description: str | None = None

    if chosen == "anthropic":
        description = _try_anthropic(prompt, endpoint)
    elif chosen == "ollama":
        description = _try_ollama(prompt, endpoint)

    used_real = description is not None
    if not description:
        description = _rule_based(prompt, endpoint)
        chosen = "rule_based" if not used_real else chosen

    return EnrichedBinding(
        description=description,
        provider=chosen,
        used_real_llm=used_real,
    )


def summary() -> dict[str, Any]:
    return {
        "llm_version": LLM_VERSION,
        "supported_providers": list(SUPPORTED_PROVIDERS),
        "active_provider": choose_provider(),
    }
