// Generated by SKILL-ASTRO (W8 #282). CMS=contentful.
// Typed fetch wrapper around the Contentful Delivery API. Preview
// reads live through the Preview API when CONTENTFUL_PREVIEW_TOKEN
// is set — editors see drafts without public traffic seeing them.
//
// Keep this module thin: Astro pages import `fetchEntries` /
// `verifyWebhook`, not the Contentful SDK directly. That's the seam
// for swapping CMS.

import { createClient, type ContentfulClientApi, type Entry } from "contentful"

export interface ContentfulConfig {
  space: string
  environment: string
  accessToken: string
  host?: string
}

export interface ContentfulBlogFields {
  title: string
  slug: string
  description: string
  body: string
  publishedAt: string
}

export function resolveConfig(usePreview = false): ContentfulConfig {
  const space = import.meta.env.CONTENTFUL_SPACE_ID
  const environment = import.meta.env.CONTENTFUL_ENVIRONMENT || "master"
  const delivery = import.meta.env.CONTENTFUL_DELIVERY_TOKEN
  const preview = import.meta.env.CONTENTFUL_PREVIEW_TOKEN
  const accessToken = usePreview ? preview : delivery
  if (!space || !accessToken) {
    throw new Error(
      "CONTENTFUL_SPACE_ID + {DELIVERY|PREVIEW}_TOKEN required — see .env.example",
    )
  }
  return {
    space,
    environment,
    accessToken,
    host: usePreview ? "preview.contentful.com" : "cdn.contentful.com",
  }
}

let _client: ContentfulClientApi<undefined> | null = null
export function getClient(config?: ContentfulConfig): ContentfulClientApi<undefined> {
  if (_client) return _client
  _client = createClient(config ?? resolveConfig())
  return _client
}

/** Public surface — Astro pages call this. */
export async function fetchEntries<T = ContentfulBlogFields>(
  contentType: string,
  params: Record<string, unknown> = {},
): Promise<Entry<T>[]> {
  const res = await getClient().getEntries<T>({
    content_type: contentType,
    ...params,
  })
  return res.items
}

export async function fetchEntry<T = ContentfulBlogFields>(
  id: string,
): Promise<Entry<T> | null> {
  try {
    return await getClient().getEntry<T>(id)
  } catch {
    return null
  }
}

/** Contentful delivers webhooks with `X-Contentful-Topic` + a shared secret
 *  header the operator configures at CMS side. We implement timing-safe
 *  comparison so timing attacks can't leak the secret. */
export function verifyWebhook(
  signature: string | null,
  expected: string | undefined = import.meta.env.CONTENTFUL_WEBHOOK_SECRET,
): boolean {
  if (!signature || !expected) return false
  if (signature.length !== expected.length) return false
  let diff = 0
  for (let i = 0; i < signature.length; i++) {
    diff |= signature.charCodeAt(i) ^ expected.charCodeAt(i)
  }
  return diff === 0
}
