// Generated by SKILL-ASTRO (W8 #282). CMS=sanity.
// Typed fetch wrapper around @sanity/client. GROQ queries used in
// the Astro pages reference this module; previewing sits behind the
// SANITY_PREVIEW_TOKEN env var so editors can see unpublished drafts
// without leaking them to public traffic.
//
// Why this adapter is thin: the Astro pages should NOT import
// @sanity/client directly. This module is the seam for swapping to
// Contentful or another CMS — keep it small.

import { createClient, type SanityClient } from "@sanity/client"

export interface SanityConfig {
  projectId: string
  dataset: string
  apiVersion: string
  token?: string
  useCdn?: boolean
}

export interface SanityBlogEntry {
  _id: string
  title: string
  slug: { current: string }
  description: string
  body: unknown
  publishedAt: string
}

export function resolveConfig(): SanityConfig {
  const projectId = import.meta.env.SANITY_PROJECT_ID
  const dataset = import.meta.env.SANITY_DATASET || "production"
  const apiVersion = import.meta.env.SANITY_API_VERSION || "2024-10-01"
  const token = import.meta.env.SANITY_PREVIEW_TOKEN
  if (!projectId) {
    throw new Error("SANITY_PROJECT_ID is not set — see .env.example")
  }
  return {
    projectId,
    dataset,
    apiVersion,
    token,
    useCdn: !token,
  }
}

let _client: SanityClient | null = null
export function getClient(config?: SanityConfig): SanityClient {
  if (_client) return _client
  _client = createClient(config ?? resolveConfig())
  return _client
}

/** Preferred public surface — the Astro pages call this. */
export async function fetchEntries<T = SanityBlogEntry>(
  query: string,
  params: Record<string, unknown> = {},
): Promise<T[]> {
  return getClient().fetch<T[]>(query, params)
}

/** Single-entry helper with typing. */
export async function fetchEntry<T = SanityBlogEntry>(
  query: string,
  params: Record<string, unknown> = {},
): Promise<T | null> {
  return getClient().fetch<T | null>(query, params)
}

/** HMAC-SHA256 Sanity webhook verifier — fires on `/api/webhooks/sanity`. */
export async function verifyWebhook(
  signature: string | null,
  rawBody: string,
  secret: string | undefined = import.meta.env.SANITY_WEBHOOK_SECRET,
): Promise<boolean> {
  if (!signature || !secret) return false
  const encoder = new TextEncoder()
  const key = await crypto.subtle.importKey(
    "raw",
    encoder.encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  )
  const mac = await crypto.subtle.sign("HMAC", key, encoder.encode(rawBody))
  const hex = [...new Uint8Array(mac)]
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("")
  return timingSafeEquals(signature, hex)
}

function timingSafeEquals(a: string, b: string): boolean {
  if (a.length !== b.length) return false
  let diff = 0
  for (let i = 0; i < a.length; i++) {
    diff |= a.charCodeAt(i) ^ b.charCodeAt(i)
  }
  return diff === 0
}
