// Generated by SKILL-NUXT (W7 #281).
// Pinia store — `defineStore` exposes reactive state the whole app
// can bind to without prop-drilling. Auto-imported by @pinia/nuxt so
// components can call `useCounterStore()` without the `import`.

export const useCounterStore = defineStore("counter", {
  state: () => ({
    count: 0,
  }),
  getters: {
    doubled: (state): number => state.count * 2,
  },
  actions: {
    increment(): void {
      this.count += 1
    },
    reset(): void {
      this.count = 0
    },
  },
})
