// Generated by SKILL-ASTRO (W8 #282). CMS=contentful.
// On-publish webhook handler. Contentful POSTs here every time an
// editor publishes; we verify the shared-secret signature
// (X-Contentful-Webhook-Signature) and bust caches for the affected
// entry.

import type { APIRoute } from "astro"
import { verifyWebhook } from "../../../lib/cms/contentful"

export const prerender = false

export const POST: APIRoute = async ({ request }) => {
  const signature = request.headers.get("x-contentful-webhook-signature")
  const topic = request.headers.get("x-contentful-topic")
  const ok = verifyWebhook(signature)
  if (!ok) {
    return new Response(JSON.stringify({ ok: false, reason: "invalid-signature" }), {
      status: 401,
      headers: { "Content-Type": "application/json" },
    })
  }
  let payload: unknown = null
  try {
    payload = await request.json()
  } catch {
    return new Response(JSON.stringify({ ok: false, reason: "invalid-json" }), {
      status: 400,
      headers: { "Content-Type": "application/json" },
    })
  }
  // TODO(operator): wire to rebuild / CDN cache-tag invalidation.
  const id = (payload as { sys?: { id?: string } } | null)?.sys?.id ?? null
  return new Response(
    JSON.stringify({ ok: true, topic, received: id }),
    {
      status: 200,
      headers: { "Content-Type": "application/json" },
    },
  )
}
