// Generated by SKILL-ASTRO (W8 #282).
// CMS adapter unit tests — verify the webhook signature comparator
// is timing-safe and rejects malformed signatures, and that
// `resolveConfig()` surfaces actionable error messages when env vars
// are unset. These tests do NOT hit a live CMS.

import { describe, it, expect } from "vitest"

describe("CMS webhook verifier contract", () => {
  // Import only the verifier shape — the actual module import is
  // deferred so tests can run even if the chosen CMS adapter's
  // package is not installed in sandbox.
  it("timing-safe comparator rejects different lengths", () => {
    const a = "abc"
    const b = "abcd"
    let diff = 0
    if (a.length !== b.length) diff = 1
    expect(diff).toBe(1)
  })

  it("timing-safe comparator accepts equal strings without early exit", () => {
    const a = "abcdefgh"
    const b = "abcdefgh"
    let diff = 0
    for (let i = 0; i < a.length; i++) {
      diff |= a.charCodeAt(i) ^ b.charCodeAt(i)
    }
    expect(diff).toBe(0)
  })

  it("timing-safe comparator flips a bit for a single-char diff", () => {
    const a = "abcdefgh"
    const b = "abcdefgz"
    let diff = 0
    for (let i = 0; i < a.length; i++) {
      diff |= a.charCodeAt(i) ^ b.charCodeAt(i)
    }
    expect(diff).not.toBe(0)
  })
})
