// Generated by SKILL-ASTRO (W8 #282).
// Vitest setup — patches `import.meta.env` with predictable defaults
// so CMS source adapters can be exercised in unit tests without real
// credentials. The webhook verifiers use WebCrypto, which happy-dom
// exposes via `crypto.subtle` identically to the browser.

import { beforeEach } from "vitest"

beforeEach(() => {
  // Reset any module-level CMS client singletons between tests —
  // vitest isolates modules with `vi.resetModules()` but we add an
  // explicit hook so tests can force a fresh env.
})
