// Generated by SKILL-NUXT (W7 #281).
// Catch-all proxy to the OmniSight backend. The Nitro analogue of
// Next.js's app/api/v1/[...slug]/route.ts — handles every method via
// a single `defineEventHandler` since Nitro routes are method-agnostic
// unless the filename ends in `.{get,post,put,delete}.ts`.

export default defineEventHandler(async (event) => {
  const config = useRuntimeConfig()
  const backend = config.backendUrl as string
  const slug = (getRouterParam(event, "slug") || "").replace(/^\//, "")
  const url = `${backend}/api/v1/${slug}`

  const method = event.node.req.method || "GET"
  const init: RequestInit = {
    method,
    headers: getRequestHeaders(event) as HeadersInit,
  }
  if (!["GET", "HEAD"].includes(method.toUpperCase())) {
    init.body = await readRawBody(event)
  }

  const upstream = await fetch(url, init)
  setResponseStatus(event, upstream.status)
  return await upstream.text()
})
