// Generated by SKILL-NEXTJS (W6 #280).
// GDPR Art. 17 — right-to-be-forgotten handler. Forwards the request
// to the backend; backend is responsible for scrubbing across all
// sub-processors and returning the audit trail.

import { NextRequest, NextResponse } from "next/server"

export const runtime = "nodejs"

export async function POST(req: NextRequest) {
  const backend = process.env.BACKEND_URL || "http://localhost:8000"
  const body = await req.json().catch(() => ({}))
  const upstream = await fetch(`${backend}/api/v1/privacy/erasure`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  })
  return new NextResponse(upstream.body, {
    status: upstream.status,
    headers: { "Content-Type": "application/json" },
  })
}
