/* ICC Profile Embedding — C scaffold
 * Auto-generated by OmniSight Imaging Pipeline (CORE-19)
 *
 * Embeds ICC color profiles into TIFF/JPEG/PNG output files.
 */

#include <stdint.h>
#include <string.h>
#include <stdio.h>

/* ICC profile tag for TIFF (tag 34675 = InterColorProfile) */
#define TIFF_TAG_ICC_PROFILE  34675

/* JPEG APP2 marker for ICC profile */
#define JPEG_MARKER_APP2      0xFFE2
#define ICC_PROFILE_HEADER    "ICC_PROFILE"
#define ICC_MAX_CHUNK_SIZE    65519

typedef struct {
    const uint8_t *data;
    uint32_t       size;
    char           profile_id[64];
} icc_profile_t;

int icc_embed_tiff(FILE *tiff_fp, const icc_profile_t *profile)
{
    /* Write ICC profile as TIFF tag 34675 (binary blob) */
    /* Caller must update IFD entry count and offset */
    if (!tiff_fp || !profile || !profile->data)
        return -1;

    /* Tag ID (2) + Type (2) + Count (4) + Value/Offset (4) */
    uint16_t tag_id = TIFF_TAG_ICC_PROFILE;
    uint16_t tag_type = 7;  /* UNDEFINED */
    uint32_t count = profile->size;
    fwrite(&tag_id, 2, 1, tiff_fp);
    fwrite(&tag_type, 2, 1, tiff_fp);
    fwrite(&count, 4, 1, tiff_fp);
    /* Offset to profile data — caller fills in */
    uint32_t offset = 0;
    fwrite(&offset, 4, 1, tiff_fp);
    return 0;
}

int icc_embed_jpeg_chunks(FILE *jpeg_fp, const icc_profile_t *profile)
{
    if (!jpeg_fp || !profile || !profile->data)
        return -1;

    uint32_t remaining = profile->size;
    uint8_t  chunk_num = 1;
    uint8_t  total_chunks = (uint8_t)((profile->size + ICC_MAX_CHUNK_SIZE - 1)
                                       / ICC_MAX_CHUNK_SIZE);
    const uint8_t *ptr = profile->data;

    while (remaining > 0) {
        uint32_t chunk_size = (remaining > ICC_MAX_CHUNK_SIZE)
                              ? ICC_MAX_CHUNK_SIZE : remaining;
        uint16_t marker = JPEG_MARKER_APP2;
        uint16_t length = (uint16_t)(2 + 12 + 2 + chunk_size);

        fwrite(&marker, 2, 1, jpeg_fp);
        fwrite(&length, 2, 1, jpeg_fp);
        fwrite(ICC_PROFILE_HEADER, 1, 12, jpeg_fp);
        fwrite(&chunk_num, 1, 1, jpeg_fp);
        fwrite(&total_chunks, 1, 1, jpeg_fp);
        fwrite(ptr, 1, chunk_size, jpeg_fp);

        ptr += chunk_size;
        remaining -= chunk_size;
        chunk_num++;
    }
    return 0;
}
