/* Scanner ISP Pipeline — C scaffold
 * Auto-generated by OmniSight Imaging Pipeline (CORE-19)
 *
 * This scaffold provides the ISP processing stages for document scanner
 * sensors (CIS/CCD). Integrate with your sensor driver and DMA engine.
 */

#include <stdint.h>
#include <string.h>

/* ISP configuration */
typedef struct {
    uint8_t  sensor_type;    /* 0=CIS, 1=CCD */
    uint8_t  color_mode;     /* 0=grey8, 1=grey16, 2=rgb24, 3=rgb48 */
    uint16_t width_pixels;
    uint16_t height_lines;
    uint16_t dpi;
    float    gamma;
    uint8_t  enable_binarize;
    uint8_t  enable_deskew;
} isp_config_t;

/* Dark frame reference (captured during calibration) */
static uint16_t dark_frame[8192];

/* White reference (captured during calibration) */
static uint16_t white_ref[8192];

int isp_calibrate_dark(const uint16_t *raw, uint32_t len)
{
    if (len > sizeof(dark_frame) / sizeof(dark_frame[0]))
        len = sizeof(dark_frame) / sizeof(dark_frame[0]);
    memcpy(dark_frame, raw, len * sizeof(uint16_t));
    return 0;
}

int isp_calibrate_white(const uint16_t *raw, uint32_t len)
{
    if (len > sizeof(white_ref) / sizeof(white_ref[0]))
        len = sizeof(white_ref) / sizeof(white_ref[0]);
    memcpy(white_ref, raw, len * sizeof(uint16_t));
    return 0;
}

void isp_dark_subtract(uint16_t *line, uint32_t len)
{
    for (uint32_t i = 0; i < len; i++) {
        int32_t val = (int32_t)line[i] - (int32_t)dark_frame[i % sizeof(dark_frame)];
        line[i] = (val < 0) ? 0 : (uint16_t)val;
    }
}

void isp_white_balance(uint16_t *line, uint32_t len, uint16_t max_val)
{
    for (uint32_t i = 0; i < len; i++) {
        uint32_t ref = white_ref[i % sizeof(white_ref)];
        if (ref == 0) ref = 1;
        line[i] = (uint16_t)(((uint32_t)line[i] * max_val) / ref);
        if (line[i] > max_val) line[i] = max_val;
    }
}

void isp_gamma(uint16_t *line, uint32_t len, uint16_t max_val, float gamma)
{
    float inv = 1.0f / gamma;
    for (uint32_t i = 0; i < len; i++) {
        float norm = (float)line[i] / (float)max_val;
        float corrected = powf(norm, inv);
        line[i] = (uint16_t)(corrected * max_val);
    }
}

int isp_process_line(isp_config_t *cfg, uint16_t *line, uint32_t len)
{
    uint16_t max_val = (cfg->color_mode & 1) ? 65535 : 255;

    isp_dark_subtract(line, len);
    isp_white_balance(line, len, max_val);
    isp_gamma(line, len, max_val, cfg->gamma);

    return 0;
}
