// Enterprise Web Stack — NextAuth configuration scaffold
// Generated by CORE-21. Adapt to target project's stack.

import NextAuth from "next-auth";
import CredentialsProvider from "next-auth/providers/credentials";
// import LDAPProvider from "./providers/ldap";
// import SAMLProvider from "./providers/saml";
// import { OIDCProvider } from "./providers/oidc";

export const authOptions = {
  providers: [
    CredentialsProvider({
      name: "Credentials",
      credentials: {
        email: { label: "Email", type: "email" },
        password: { label: "Password", type: "password" },
      },
      async authorize(credentials) {
        // Replace with real user lookup + password verification
        const res = await fetch(`${process.env.API_URL}/api/enterprise/auth/authenticate`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            provider_id: "credentials",
            username: credentials?.email,
            password: credentials?.password,
          }),
        });
        const data = await res.json();
        if (data.result === "success") {
          return { id: data.user_id, email: credentials?.email };
        }
        return null;
      },
    }),
    // Uncomment to enable SSO:
    // LDAPProvider({ ... }),
    // SAMLProvider({ ... }),
    // OIDCProvider({ ... }),
  ],
  callbacks: {
    async jwt({ token, user }: { token: any; user: any }) {
      if (user) {
        token.userId = user.id;
      }
      return token;
    },
    async session({ session, token }: { session: any; token: any }) {
      session.user.id = token.userId;
      return session;
    },
  },
  pages: {
    signIn: "/login",
  },
};

export default NextAuth(authOptions);
