// Enterprise Web Stack — RBAC middleware scaffold
// Generated by CORE-21. Adapt to target project's stack.

import { NextRequest, NextResponse } from "next/server";
import { getToken } from "next-auth/jwt";

interface RBACConfig {
  rolePermissions: Record<string, string[]>;
}

const defaultConfig: RBACConfig = {
  rolePermissions: {
    super_admin: ["*"],
    tenant_admin: [
      "users.create", "users.read", "users.update", "users.delete",
      "roles.assign", "audit.read", "audit.export",
      "reports.view", "reports.create", "reports.export",
      "workflow.create", "workflow.approve", "workflow.reject",
      "import.execute", "export.execute", "settings.manage",
    ],
    manager: [
      "users.read", "audit.read",
      "reports.view", "reports.create", "reports.export",
      "workflow.create", "workflow.approve", "workflow.reject",
      "import.execute", "export.execute",
    ],
    editor: [
      "users.read", "reports.view", "reports.create",
      "workflow.create", "import.execute", "export.execute",
    ],
    viewer: ["users.read", "reports.view"],
    guest: ["reports.view"],
  },
};

export function checkPermission(
  role: string,
  permission: string,
  config: RBACConfig = defaultConfig
): boolean {
  const perms = config.rolePermissions[role] || [];
  if (perms.includes("*")) return true;
  return perms.includes(permission);
}

export function rbacMiddleware(requiredPermission: string) {
  return async (req: NextRequest) => {
    const token = await getToken({ req });
    if (!token) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const userRole = (token as any).role || "guest";
    if (!checkPermission(userRole, requiredPermission)) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    return NextResponse.next();
  };
}
