// Enterprise Web Stack — Workflow engine scaffold
// Generated by CORE-21. Adapt to target project's stack.

export type WorkflowState =
  | "draft"
  | "submitted"
  | "under_review"
  | "needs_revision"
  | "approved"
  | "rejected"
  | "completed"
  | "cancelled";

interface StateConfig {
  name: string;
  initial?: boolean;
  terminal?: boolean;
  transitions: WorkflowState[];
}

const stateMap: Record<WorkflowState, StateConfig> = {
  draft: { name: "Draft", initial: true, transitions: ["submitted"] },
  submitted: {
    name: "Submitted",
    transitions: ["under_review", "rejected", "cancelled"],
  },
  under_review: {
    name: "Under Review",
    transitions: ["approved", "rejected", "needs_revision"],
  },
  needs_revision: {
    name: "Needs Revision",
    transitions: ["submitted", "cancelled"],
  },
  approved: { name: "Approved", transitions: ["completed", "cancelled"] },
  rejected: { name: "Rejected", terminal: true, transitions: [] },
  completed: { name: "Completed", terminal: true, transitions: [] },
  cancelled: { name: "Cancelled", terminal: true, transitions: [] },
};

export interface WorkflowInstance {
  id: string;
  type: string;
  state: WorkflowState;
  data: Record<string, unknown>;
  submitter: string;
  approvers: string[];
  history: Array<{
    action: string;
    actor: string;
    timestamp: number;
    fromState: WorkflowState;
    toState: WorkflowState;
    reason?: string;
  }>;
  tenantId: string;
  createdAt: number;
  updatedAt: number;
}

export function canTransition(
  from: WorkflowState,
  to: WorkflowState
): boolean {
  const config = stateMap[from];
  return config?.transitions.includes(to) ?? false;
}

export function transition(
  instance: WorkflowInstance,
  targetState: WorkflowState,
  actor: string,
  reason?: string
): WorkflowInstance {
  if (!canTransition(instance.state, targetState)) {
    throw new Error(
      `Invalid transition: ${instance.state} → ${targetState}`
    );
  }

  const now = Date.now();
  return {
    ...instance,
    state: targetState,
    updatedAt: now,
    history: [
      ...instance.history,
      {
        action: targetState,
        actor,
        timestamp: now,
        fromState: instance.state,
        toState: targetState,
        reason,
      },
    ],
  };
}
