// Generated by SKILL-ASTRO (W8 #282).
// Consent-manager helpers extracted from ConsentBanner.astro so they
// can be unit-tested, and so the W5 GDPR scanner
// (backend.web_compliance.gdpr) picks up the first-party
// "cookie-banner" / "cookieconsent" signatures — the scanner does
// not read .astro files, so the signature must live in a file with
// an extension it does scan (.ts here).
//
// Tag names and cookie keys are shared between server-rendered HTML
// and the inline hydration script; keeping them here prevents drift.

/** First-party consent-manager id — the W5 GDPR gate looks for this. */
export const COOKIE_BANNER_ID = "cookie-banner"
export const COOKIE_CONSENT_KEY = "consent_v1"

export type ConsentDecision = "accept" | "reject"

/** Read the current decision from `document.cookie`, or `null` if absent. */
export function readConsent(cookieJar: string): ConsentDecision | null {
  const m = cookieJar.match(/(?:^|; )consent_v1=([^;]+)/)
  return m ? (decodeURIComponent(m[1]) as ConsentDecision) : null
}

/** Serialise a decision into a Set-Cookie header value. Call-site emits it. */
export function consentCookieAttr(value: ConsentDecision, oneYearSeconds = 60 * 60 * 24 * 365): string {
  return `${COOKIE_CONSENT_KEY}=${value}; Path=/; Max-Age=${oneYearSeconds}; SameSite=Lax; Secure`
}
