"""Structured JSON logging configuration.

Generated by SKILL-FASTAPI (X5 #301). Matches the backend-python
role's "no print(), structured JSON formatter" requirement.
"""

from __future__ import annotations

import logging

from pythonjsonlogger import jsonlogger


def configure_logging(level: str = "INFO") -> None:
    root = logging.getLogger()
    if root.handlers:
        # Already configured (pytest / re-entrant lifespan).
        return

    handler = logging.StreamHandler()
    formatter = jsonlogger.JsonFormatter(
        "%(asctime)s %(name)s %(levelname)s %(message)s",
        rename_fields={"asctime": "ts", "levelname": "level"},
    )
    handler.setFormatter(formatter)
    root.addHandler(handler)
    root.setLevel(level.upper())

    # Quiet overly-chatty SQLAlchemy / uvicorn loggers — they still
    # propagate warnings & errors.
    for noisy in ("sqlalchemy.engine", "uvicorn.access"):
        logging.getLogger(noisy).setLevel(max(root.level, logging.WARNING))
