/**
 * ProjectReportPanel — B6/UX-04 component tests.
 *
 * Covers:
 *   1. Renders golden fixture with all three sections
 *   2. Sections are collapsible (click toggles)
 *   3. Download triggers correct blob
 *   4. Copy-to-clipboard copies markdown
 *   5. Share button calls POST /report/share and displays URL
 *   6. Error state renders inline
 *   7. Empty state when no run/report provided
 */

import { describe, expect, it, vi, beforeEach } from "vitest"
import { render, screen, waitFor } from "@testing-library/react"
import userEvent from "@testing-library/user-event"

vi.mock("@/lib/api", () => ({
  generateReport: vi.fn(),
  getReport: vi.fn(),
  shareReport: vi.fn(),
}))

import { ProjectReportPanel } from "@/components/omnisight/project-report-panel"
import * as api from "@/lib/api"

const mockGenerate = api.generateReport as ReturnType<typeof vi.fn>
const mockGetReport = api.getReport as ReturnType<typeof vi.fn>
const mockShare = api.shareReport as ReturnType<typeof vi.fn>

const GOLDEN_MARKDOWN = `# Test Project Report

> Report ID: \`rpt-test000001\`
> Generated: 2026-04-15T12:00:00+00:00
> Version: 1.0.0

## 1. Specification

### Parsed Spec Fields

| Field | Value | Confidence | Status |
|-------|-------|------------|--------|
| project_type | web_app | 95% | ✅ |
| framework | nextjs | 92% | ✅ |

### Input Sources

- https://github.com/example/my-app

## 2. Execution

### Workflow Run

- **ID**: \`wf-abc123\`
- **Kind**: invoke
- **Status**: completed

### Steps

| # | Key | Started | Completed | Status |
|---|-----|---------|-----------|--------|
| 1 | \`parse_intent\` | 2025-04-15 12:00:00 UTC | 2025-04-15 12:00:20 UTC | ✅ |
| 2 | \`compile\` | 2025-04-15 12:01:40 UTC | 2025-04-15 12:03:20 UTC | ❌ |

### Retries / Errors

- \`compile\`: TimeoutError: build exceeded 60s

## 3. Outcome

### Deploy URL

https://my-app.omnisight.dev

### Smoke Test Results

- **health-check**: pass

---
*Generated by OmniSight Report Engine v1.0.0*
`

const goldenReport: api.ReportResponse = {
  report_id: "rpt-test000001",
  title: "Test Project Report",
  generated_at: "2026-04-15T12:00:00+00:00",
  markdown: GOLDEN_MARKDOWN,
}

describe("ProjectReportPanel", () => {
  const clipboardWriteText = vi.fn().mockResolvedValue(undefined)

  beforeEach(() => {
    vi.clearAllMocks()
    mockGenerate.mockResolvedValue(goldenReport)
    mockGetReport.mockResolvedValue(goldenReport)
    clipboardWriteText.mockResolvedValue(undefined)
    Object.defineProperty(navigator, "clipboard", {
      value: { writeText: clipboardWriteText },
      writable: true,
      configurable: true,
    })
  })

  it("renders golden fixture with all three sections", async () => {
    render(<ProjectReportPanel runId="wf-abc123" />)
    await waitFor(() => expect(mockGenerate).toHaveBeenCalledWith("wf-abc123", undefined))
    expect(await screen.findByText("1. Specification")).toBeInTheDocument()
    expect(screen.getByText("2. Execution")).toBeInTheDocument()
    expect(screen.getByText("3. Outcome")).toBeInTheDocument()
    expect(screen.getByText("rpt-test000001", { exact: false })).toBeInTheDocument()
  })

  it("fetches by reportId when provided", async () => {
    render(<ProjectReportPanel reportId="rpt-test000001" />)
    await waitFor(() => expect(mockGetReport).toHaveBeenCalledWith("rpt-test000001"))
    expect(await screen.findByText("1. Specification")).toBeInTheDocument()
  })

  it("sections are collapsible", async () => {
    const user = userEvent.setup()
    render(<ProjectReportPanel runId="wf-abc123" />)
    const specBtn = await screen.findByRole("button", { name: /Section 1\. Specification/i })
    expect(specBtn).toHaveAttribute("aria-expanded", "true")
    await user.click(specBtn)
    expect(specBtn).toHaveAttribute("aria-expanded", "false")
    await user.click(specBtn)
    expect(specBtn).toHaveAttribute("aria-expanded", "true")
  })

  it("download triggers correct blob", async () => {
    const user = userEvent.setup()
    const createObjectURL = vi.fn(() => "blob:fake-url")
    const revokeObjectURL = vi.fn()
    Object.assign(URL, { createObjectURL, revokeObjectURL })

    const clickSpy = vi.fn()
    const origCreateElement = document.createElement.bind(document)
    vi.spyOn(document, "createElement").mockImplementation((tag: string) => {
      const el = origCreateElement(tag)
      if (tag === "a") {
        Object.defineProperty(el, "click", { value: clickSpy })
      }
      return el
    })

    render(<ProjectReportPanel runId="wf-abc123" />)
    await screen.findByText("1. Specification")
    const dlBtn = screen.getByRole("button", { name: /download markdown/i })
    await user.click(dlBtn)

    expect(createObjectURL).toHaveBeenCalledWith(expect.any(Blob))
    const blob = (createObjectURL.mock.calls[0] as unknown[])[0] as Blob
    expect(blob.type).toBe("text/markdown;charset=utf-8")
    const text = await blob.text()
    expect(text).toBe(GOLDEN_MARKDOWN)
    expect(clickSpy).toHaveBeenCalled()
    expect(revokeObjectURL).toHaveBeenCalledWith("blob:fake-url")

    vi.restoreAllMocks()
  })

  it("copy-to-clipboard copies markdown", async () => {
    const user = userEvent.setup()
    const writeMock = vi.fn().mockResolvedValue(undefined)
    Object.defineProperty(navigator, "clipboard", {
      value: { writeText: writeMock },
      writable: true,
      configurable: true,
    })
    render(<ProjectReportPanel runId="wf-abc123" />)
    await screen.findByText("1. Specification")
    const copyBtn = screen.getByRole("button", { name: /copy to clipboard/i })
    await user.click(copyBtn)
    expect(writeMock).toHaveBeenCalledWith(GOLDEN_MARKDOWN)
  })

  it("share button calls POST /report/share and displays URL", async () => {
    const user = userEvent.setup()
    mockShare.mockResolvedValue({
      url: "https://omnisight.dev/report/share/rpt-test000001?expires=999&sig=abc",
      expires_in: 86400,
    })
    render(<ProjectReportPanel runId="wf-abc123" />)
    await screen.findByText("1. Specification")
    const shareBtn = screen.getByRole("button", { name: /share report/i })
    await user.click(shareBtn)
    await waitFor(() => expect(mockShare).toHaveBeenCalledWith("rpt-test000001", expect.any(String)))
    expect(await screen.findByText(/rpt-test000001\?expires=999/)).toBeInTheDocument()
    expect(screen.getByRole("button", { name: /copy share url/i })).toBeInTheDocument()
  })

  it("surfaces fetch errors inline", async () => {
    mockGenerate.mockRejectedValue(new Error("API 500: report engine down"))
    render(<ProjectReportPanel runId="wf-abc123" />)
    await waitFor(() => expect(screen.getByText(/report engine down/)).toBeInTheDocument())
  })

  it("shows empty state when no run/report provided", () => {
    render(<ProjectReportPanel />)
    expect(screen.getByText(/No report loaded/)).toBeInTheDocument()
  })

  it("sanitizes XSS payloads in markdown content (FX.2.1)", async () => {
    const xssMarkdown = `# Malicious Report

## 1. Specification

<script>window.__pwned = true</script>

<img src=x onerror="window.__pwned = true">

[click me](javascript:alert('xss'))

### Inline payload

- <iframe src="https://evil.example/"></iframe>
- normal item

## 2. Execution

\`\`\`
ok
\`\`\`

## 3. Outcome

done

---
`
    mockGenerate.mockResolvedValue({
      report_id: "rpt-xss00000001",
      title: "Malicious",
      generated_at: "2026-04-15T12:00:00+00:00",
      markdown: xssMarkdown,
    })

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    delete (window as any).__pwned

    const { container } = render(<ProjectReportPanel runId="wf-xss" />)
    await screen.findByText("1. Specification")

    const specSection = container.querySelector('[data-section="spec"]')!
    expect(specSection.querySelector("script")).toBeNull()
    expect(specSection.querySelector("iframe")).toBeNull()
    expect(specSection.querySelector("img")).toBeNull()
    expect(specSection.querySelector("[onerror]")).toBeNull()
    expect(specSection.querySelector('a[href^="javascript:" i]')).toBeNull()
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    expect((window as any).__pwned).toBeUndefined()
  })
})
