"""Y10 #286 row 1 — multi-tenant + multi-project + multi-user concurrency
stress acceptance test.

Acceptance criterion (TODO §Y10 row 1)::

    多租戶 + 多 project + 多 user 並發壓力：10 tenant × 20 project × 5
    user × 同時跑 workflow_run → 無 cross-talk / 無 deadlock / 無 quota
    mis-attribution.

Three failure modes the test rules out
──────────────────────────────────────
1. **Cross-talk** — a workflow_run started under ``(tenant_A,
   project_A, user_A)`` must NEVER produce a billing row attributed
   to ``(tenant_B, ...)`` or ``(tenant_A, project_B, ...)``. Root
   cause would be a leaked ``ContextVar`` between asyncio tasks, a
   shared module-global pulled out of context, or a connection pool
   release-time reset that doesn't clear per-tenant session state.
2. **Deadlock** — concurrent ``audit.log`` writes serialise on
   ``pg_advisory_xact_lock(hashtext('audit-chain-' || tenant_id))``;
   that lock is per-tenant by design so cross-tenant writes must NOT
   block each other. If a refactor accidentally promoted the key to
   a global string (or shared a key between tenants), the test would
   hang on its 120 s wait_for guard.
3. **Quota mis-attribution** — every ``workflow_run`` finishing must
   produce exactly one ``billing_usage_events`` row carrying the
   correct ``(tenant_id, project_id)`` tuple read straight off the
   ``workflow_runs`` row (not from a request-scope ContextVar that
   may have leaked, and not from a fall-through ``p-<suffix>-default``
   bucket when the run was started against an explicit project).

Test layout
───────────
* **Block A — pure-unit drift guards** (always run): lock the
  acceptance dimensions and the contracts that make the concurrent
  Block B tests load-bearing. If a future refactor promotes the
  audit chain advisory lock to a non-tenant key, or makes
  ``workflow.finish`` read tenant/project from the ContextVar
  instead of the DB row, Block A trips on every CI run including
  ones without a PG service.
* **Block B — PG-required acceptance** (skip without
  ``OMNI_TEST_PG_URL``): drive the actual 10 × 20 × 5 = 1000 task
  fan-out and assert each of the three failure modes is observably
  absent in the resulting ``audit_log`` / ``workflow_runs`` /
  ``billing_usage_events`` triple.

Same skip-pattern as ``test_y9_row5_audit_billing_alignment.py`` so
the test lane gating stays consistent across the Y rows.

Module-global state audit (per implement_phase_step.md Step 1)
────────────────────────────────────────────────────────────────
This row is pure test code — zero new prod code, zero new
module-globals. The fixtures reset
``backend.db_context.set_tenant_id`` / ``set_project_id`` on
teardown so the heavy concurrent fan-out cannot leak into a
following test. The Prometheus cardinality cap counters in
``backend.metrics_labels`` are intentionally per-worker (audit
answer #3) and the test's 200 distinct ``project_id`` values stay
well under the 10 000 default cap, so no ``"other"`` bucket
collapse occurs and the per-row attribution assertions remain
sharp.

Read-after-write timing audit (per implement_phase_step.md Step 1)
────────────────────────────────────────────────────────────────
Each task ``await``s its writers (``audit.log`` /
``workflow.finish``) sequentially before the outer
``asyncio.gather`` returns; the assertions then read against the
fully-quiesced state. The PG advisory lock keyed on
``hashtext('audit-chain-' || tenant_id)`` ensures within-tenant
ordering, while the per-row ``BIGINT GENERATED BY DEFAULT AS
IDENTITY`` on ``billing_usage_events`` (alembic 0039) guarantees
that 1000 concurrent inserters cannot collide on row id —
cross-tenant ordering between rows is observable-time only and not
asserted on (the tests check counts and per-row attribution, not
ordering between unrelated tenants).
"""

from __future__ import annotations

import asyncio
import inspect
import os
import random
import time
from typing import Any

import pytest


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  Acceptance-criterion dimensions (Y10 row 1, TODO §Y10)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


_TENANTS_N = 10
_PROJECTS_PER_TENANT = 20
_USERS_PER_TENANT = 5
# 1 workflow_run per (tenant, project, user) tuple → 10 × 20 × 5 = 1000.
_TOTAL_RUNS = _TENANTS_N * _PROJECTS_PER_TENANT * _USERS_PER_TENANT

_TENANT_PREFIX = "t-y10r1"
_PROJECT_PREFIX = "p-y10r1"
_USER_PREFIX = "u-y10r1"


def _tenant_id(t: int) -> str:
    return f"{_TENANT_PREFIX}-{t:02d}"


def _project_id(t: int, p: int) -> str:
    return f"{_PROJECT_PREFIX}-{t:02d}-{p:02d}"


def _user_id(t: int, u: int) -> str:
    return f"{_USER_PREFIX}-{t:02d}-{u:02d}"


def _user_email(t: int, u: int) -> str:
    return f"u{t:02d}-{u:02d}@y10r1.local"


def _run_id(t: int, p: int, u: int) -> str:
    return f"wf-y10r1-{t:02d}-{p:02d}-{u:02d}"


def _pg_not_available() -> bool:
    return not os.environ.get("OMNI_TEST_PG_URL", "").strip()


_requires_pg = pytest.mark.skipif(
    _pg_not_available(),
    reason="Y10 row 1 multi-tenant concurrency stress integration "
           "tests need an actual PG instance — set OMNI_TEST_PG_URL.",
)


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  Block A — pure-unit drift guards (always run)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


def test_dimensions_match_acceptance_criterion():
    """Lock the (10, 20, 5, 1000) tuple against drift.

    The TODO row literally states ``10 tenant × 20 project × 5
    user`` — if a future refactor lowers any dimension under load
    pressure (e.g. someone pin-pricks the test scale to make CI
    faster) the acceptance criterion silently weakens. This guard
    catches that and forces the change to be discussed in the
    commit message.
    """
    assert _TENANTS_N == 10
    assert _PROJECTS_PER_TENANT == 20
    assert _USERS_PER_TENANT == 5
    assert _TOTAL_RUNS == 1000
    assert (
        _TENANTS_N * _PROJECTS_PER_TENANT * _USERS_PER_TENANT
        == _TOTAL_RUNS
    )


def test_workflow_finish_reads_attribution_from_db_row_not_contextvar():
    """Source-grep: ``workflow.finish`` MUST pass the
    ``(tenant_id, project_id)`` tuple it reads off the
    ``workflow_runs`` row directly to ``billing_usage.record_workflow_run``,
    not from the request-scope ContextVar.

    Why this matters for Y10 row 1: the concurrent fan-out runs
    ``workflow.finish`` from background tasks where the original
    request scope may already have torn down. If a future refactor
    swapped the explicit row-read for a ``current_tenant_id()``
    call, billing rows would silently mis-attribute under
    concurrency (tasks finishing on a stale ContextVar slot picked
    up someone else's tenant).
    """
    from backend import workflow

    src = inspect.getsource(workflow.finish)
    # The fan-out site explicitly threads tenant_id / project_id
    # from the SELECT row (not from set_tenant_id contextvar).
    assert "tenant_id=row[\"tenant_id\"]" in src, (
        "workflow.finish must pass tenant_id=row['tenant_id'] to "
        "record_workflow_run — Y10 row 1 attribution invariant"
    )
    assert "project_id=row[\"project_id\"]" in src, (
        "workflow.finish must pass project_id=row['project_id'] to "
        "record_workflow_run — Y10 row 1 attribution invariant"
    )


def test_audit_chain_lock_is_keyed_per_tenant_not_global():
    """Source-grep: ``audit._log_impl`` advisory lock must hash a
    per-tenant key, NOT a global constant.

    Cross-tenant deadlock prevention: 10 tenants writing audit
    rows concurrently must not serialise on a shared lock — each
    tenant's chain has its own key space. If someone accidentally
    promoted the key to ``"audit-chain"`` (no tenant interpolation)
    the 1000-task fan-out would degrade to single-threaded
    throughput and the timeout guard would trip.
    """
    from backend import audit

    src = inspect.getsource(audit._log_impl)
    assert "pg_advisory_xact_lock(hashtext($1))" in src, (
        "audit._log_impl must use pg_advisory_xact_lock(hashtext($1))"
    )
    # The key must contain the tenant id — search for the f-string
    # that builds 'audit-chain-{tid}'.
    assert 'f"audit-chain-{tid}"' in src, (
        "audit._log_impl advisory lock key must be per-tenant "
        "(f\"audit-chain-{tid}\") — Y10 row 1 deadlock prevention"
    )


def test_billing_resolver_does_not_overwrite_explicit_project():
    """Negative control for the cross-talk hypothesis: if a task
    sets ``set_project_id("p-other")`` in its ContextVar but
    ``workflow.finish`` passes ``project_id="p-explicit"``
    explicitly to ``record_workflow_run``, the resolver must
    return ``"p-explicit"`` — explicit always wins over ContextVar.

    Pure-unit because the resolver is a closed-form function;
    asserting this contract in isolation guarantees Block B's
    1000-task assertion that "every billing row's project_id
    matches the workflow_runs.project_id" holds even under heavy
    contextvar swapping.
    """
    from backend import billing_usage as bu
    from backend.db_context import set_project_id, set_tenant_id

    # Set ContextVar to a different value to prove explicit wins.
    set_tenant_id("t-ctx-leaked")
    set_project_id("p-ctx-leaked")
    try:
        resolved = bu._resolve_project(
            "p-explicit-wins", tenant_id="t-explicit-wins",
        )
        assert resolved == "p-explicit-wins"
        # And the resolver does NOT touch tenant either when explicit.
        assert bu._resolve_tenant("t-explicit-wins") == "t-explicit-wins"
    finally:
        set_tenant_id(None)
        set_project_id(None)


@pytest.mark.asyncio
async def test_contextvar_per_task_isolation_under_gather_no_pg():
    """Pure-asyncio test (no PG): N concurrent tasks each set a
    distinct ``tenant_id`` in their own ContextVar scope and read
    it back after ``await asyncio.sleep(0)`` to force a scheduler
    yield. The ContextVar-per-task guarantee is what the entire
    Y row stack rests on; if it broke, every Block B assertion
    would be silently meaningless.

    Lifted from ``test_multi_tenant_isolation.py`` and made
    asyncio-only here so the contract is checked even on a CI
    runner without PG.
    """
    from backend.db_context import current_tenant_id, set_tenant_id

    async def _task(tid: str) -> str:
        set_tenant_id(tid)
        # Force the scheduler to run other tasks before we read back
        # — this is where a leaky shared dict (instead of a
        # contextvars.ContextVar) would surface as cross-task bleed.
        await asyncio.sleep(0)
        seen = current_tenant_id()
        return f"{tid}|{seen}"

    tids = [f"t-isolation-{i:02d}" for i in range(20)]
    random.shuffle(tids)
    results = await asyncio.gather(*[_task(t) for t in tids])
    for line in results:
        sent, seen = line.split("|", 1)
        assert sent == seen, (
            f"ContextVar leak: task set {sent!r} but read back "
            f"{seen!r} — Y10 row 1 isolation invariant violated"
        )


def test_per_tenant_audit_chain_lock_key_distinct_across_tenants():
    """If two distinct tenant_ids hash to the SAME advisory-lock
    key, audit writes on those two tenants would block each other
    cross-tenant — silently violating the "no deadlock under
    concurrent load" Y10 row 1 acceptance.

    PG's ``hashtext()`` is a 32-bit hash; collisions in a 10-tenant
    test set are astronomically unlikely but the test fixture
    deserves a quick sanity check. We use Python's fingerprint of
    the same algorithm shape — exact equality of the **keys**
    rather than the hashes, since hashtext is server-side.
    """
    keys = {f"audit-chain-{_tenant_id(t)}" for t in range(_TENANTS_N)}
    assert len(keys) == _TENANTS_N, (
        f"per-tenant lock key collision in test fixture: only "
        f"{len(keys)} distinct keys for {_TENANTS_N} tenants"
    )


def test_run_ids_are_globally_unique_across_dimensions():
    """Sanity for the test fixture itself: the (t, p, u) tuple
    space generates 1000 globally unique run_ids. If the helper
    accidentally produced collisions, every concurrent finish()
    would race on the same ``workflow_runs.id`` and the assertion
    "1000 finish → 1000 billing rows" would silently pass with a
    smaller-than-expected number of rows.
    """
    ids = {
        _run_id(t, p, u)
        for t in range(_TENANTS_N)
        for p in range(_PROJECTS_PER_TENANT)
        for u in range(_USERS_PER_TENANT)
    }
    assert len(ids) == _TOTAL_RUNS, (
        f"run_id collision in fixture: {len(ids)} distinct ids "
        f"for {_TOTAL_RUNS} (t, p, u) tuples"
    )


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  Block B — PG-required acceptance: 10 × 20 × 5 = 1000 fan-out
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


@pytest.fixture()
async def _y10_row1_db(pg_test_pool):
    """Truncate the four tables this row writes into + reset the
    request-scope ContextVars on teardown so a heavy fan-out can
    never leak into the next test.

    Tables: ``audit_log`` (chain rows from each task's
    ``audit.log("workflow.started", ...)``), ``workflow_runs`` +
    ``workflow_steps`` (the run rows themselves), and
    ``billing_usage_events`` (the per-finish billing fan-out).
    Parent rows (``tenants`` / ``projects`` / ``users`` /
    ``user_tenant_memberships``) are seeded inside each test and
    torn down via the per-fixture TRUNCATE chain so a botched test
    can't leave dangling FKs.
    """
    pool = pg_test_pool

    async def _truncate_all() -> None:
        async with pool.acquire() as conn:
            await conn.execute(
                "TRUNCATE billing_usage_events RESTART IDENTITY"
            )
            await conn.execute("DELETE FROM workflow_steps")
            await conn.execute("DELETE FROM workflow_runs")
            await conn.execute(
                "TRUNCATE audit_log RESTART IDENTITY CASCADE"
            )
            await conn.execute(
                "DELETE FROM user_tenant_memberships "
                "WHERE tenant_id LIKE $1",
                f"{_TENANT_PREFIX}-%",
            )
            await conn.execute(
                "DELETE FROM users WHERE id LIKE $1",
                f"{_USER_PREFIX}-%",
            )
            await conn.execute(
                "DELETE FROM projects WHERE tenant_id LIKE $1",
                f"{_TENANT_PREFIX}-%",
            )
            await conn.execute(
                "DELETE FROM tenants WHERE id LIKE $1",
                f"{_TENANT_PREFIX}-%",
            )

    await _truncate_all()
    try:
        yield pool
    finally:
        from backend.db_context import set_project_id, set_tenant_id
        set_tenant_id(None)
        set_project_id(None)
        await _truncate_all()


async def _seed_full_y10_row1_fixture(pool: Any) -> None:
    """Insert 10 tenants + 200 projects + 50 users + 50 memberships
    in a single transaction so the seed cost is paid once before
    the concurrent fan-out begins. The assert-on-count after seeding
    catches any FK / UNIQUE drift before the heavy section runs and
    masks the real failure with a downstream NULL.
    """
    async with pool.acquire() as conn:
        async with conn.transaction():
            for t in range(_TENANTS_N):
                tid = _tenant_id(t)
                await conn.execute(
                    "INSERT INTO tenants (id, name, plan) "
                    "VALUES ($1, $2, 'free') "
                    "ON CONFLICT (id) DO NOTHING",
                    tid, f"Y10-Row1 Tenant {t:02d}",
                )
                for p in range(_PROJECTS_PER_TENANT):
                    pid = _project_id(t, p)
                    await conn.execute(
                        "INSERT INTO projects "
                        "(id, tenant_id, product_line, name, slug) "
                        "VALUES ($1, $2, $3, $4, $5) "
                        "ON CONFLICT (tenant_id, product_line, slug) "
                        "DO NOTHING",
                        pid, tid, "embedded",
                        f"Y10R1 P{t:02d}-{p:02d}",
                        f"y10r1-p{t:02d}-{p:02d}",
                    )
                for u in range(_USERS_PER_TENANT):
                    uid = _user_id(t, u)
                    await conn.execute(
                        "INSERT INTO users "
                        "(id, email, name, role, password_hash, "
                        " enabled, tenant_id) "
                        "VALUES ($1, $2, $3, 'member', '', 1, $4) "
                        "ON CONFLICT (id) DO NOTHING",
                        uid, _user_email(t, u), f"User {t:02d}-{u:02d}",
                        tid,
                    )
                    await conn.execute(
                        "INSERT INTO user_tenant_memberships "
                        "(user_id, tenant_id, role, status) "
                        "VALUES ($1, $2, 'member', 'active') "
                        "ON CONFLICT (user_id, tenant_id) DO NOTHING",
                        uid, tid,
                    )

    # Sanity: confirm the seed counts before launching 1000 tasks.
    async with pool.acquire() as conn:
        n_tenants = await conn.fetchval(
            "SELECT COUNT(*) FROM tenants WHERE id LIKE $1",
            f"{_TENANT_PREFIX}-%",
        )
        n_projects = await conn.fetchval(
            "SELECT COUNT(*) FROM projects WHERE tenant_id LIKE $1",
            f"{_TENANT_PREFIX}-%",
        )
        n_users = await conn.fetchval(
            "SELECT COUNT(*) FROM users WHERE id LIKE $1",
            f"{_USER_PREFIX}-%",
        )
        n_memberships = await conn.fetchval(
            "SELECT COUNT(*) FROM user_tenant_memberships "
            "WHERE tenant_id LIKE $1",
            f"{_TENANT_PREFIX}-%",
        )
    assert n_tenants == _TENANTS_N
    assert n_projects == _TENANTS_N * _PROJECTS_PER_TENANT
    assert n_users == _TENANTS_N * _USERS_PER_TENANT
    assert n_memberships == _TENANTS_N * _USERS_PER_TENANT


async def _insert_running_workflow_row(
    pool: Any, *, run_id: str, tenant_id: str, project_id: str,
) -> None:
    """Insert a ``workflow_runs`` row in 'running' state with the
    explicit (tenant_id, project_id) tuple we want to assert on
    after ``workflow.finish``. This mirrors
    ``test_y9_row5_audit_billing_alignment._insert_legacy_workflow_run``
    but always sets BOTH tenant_id and project_id so we can verify
    the explicit-attribution path under concurrency.
    """
    async with pool.acquire() as conn:
        await conn.execute(
            "INSERT INTO workflow_runs "
            "(id, kind, started_at, status, metadata, "
            " tenant_id, project_id) "
            "VALUES ($1, 'invoke', $2, 'running', '{}', $3, $4)",
            run_id, time.time(), tenant_id, project_id,
        )


async def _run_one_workflow_task(
    *, t: int, p: int, u: int,
) -> tuple[str, str, str, str]:
    """One task in the concurrent fan-out.

    Returns ``(run_id, tenant_id, project_id, actor)`` so the
    outer ``asyncio.gather`` can cross-check the result vector
    against the expected attribution table without a second DB
    round-trip.

    Why each task does the full {set_contextvar → insert run →
    audit.log → workflow.finish → reset_contextvar} dance:

    * **set_contextvar** — ``audit.log`` reads ``tenant_id`` from
      ``backend.db_context.current_tenant_id()``; without setting
      it, the audit row would land in ``t-default`` and the
      per-tenant chain assertion would fail.
    * **insert run** — ``workflow.start`` does NOT take an explicit
      ``project_id``; we insert the row directly with the (tenant,
      project) tuple we want to attribute to.
    * **audit.log** — exercises the per-tenant advisory-lock path
      under cross-tenant concurrency (the lock key contains
      ``tenant_id``; cross-tenant tasks must NOT block each other).
    * **workflow.finish** — runs ``UPDATE workflow_runs`` with
      optimistic-lock + the LEFT JOIN read of (tenant, project,
      product_line) + the synchronous fan-out into
      ``billing_usage_events``. This is the load-bearing
      attribution path the Y10 row 1 acceptance hinges on.
    * **reset_contextvar** — finally-block guarantee that a task
      crashing mid-flight cannot leak its tenant slot to a future
      task on the same asyncio loop.
    """
    from backend import audit, workflow
    from backend.db_context import set_project_id, set_tenant_id
    from backend.db_pool import get_pool

    tid = _tenant_id(t)
    pid = _project_id(t, p)
    uid = _user_id(t, u)
    email = _user_email(t, u)
    run_id = _run_id(t, p, u)

    set_tenant_id(tid)
    set_project_id(pid)
    try:
        # Insert the workflow_runs row directly so we own the (t, p)
        # attribution — workflow.start does not write project_id.
        async with get_pool().acquire() as conn:
            await conn.execute(
                "INSERT INTO workflow_runs "
                "(id, kind, started_at, status, metadata, "
                " tenant_id, project_id) "
                "VALUES ($1, 'invoke', $2, 'running', '{}', $3, $4)",
                run_id, time.time(), tid, pid,
            )

        # Per-tenant audit chain write — exercises the per-tenant
        # advisory lock under cross-tenant concurrency.
        await audit.log(
            "workflow.started", "workflow_run", run_id,
            after={"user_id": uid, "project_id": pid},
            actor=email,
        )

        # Drive the load-bearing attribution path.
        await workflow.finish(run_id, status="completed")
    finally:
        set_tenant_id(None)
        set_project_id(None)

    return run_id, tid, pid, email


@_requires_pg
@pytest.mark.asyncio
async def test_concurrent_runs_no_deadlock_within_timeout(_y10_row1_db):
    """Drive 1000 concurrent ``(workflow_run, audit.log,
    workflow.finish)`` triples through ``asyncio.gather`` and assert
    the whole storm completes inside a generous 180 s wall clock.

    This is the deadlock guard. If a future refactor accidentally
    promoted the per-tenant audit advisory lock to a global key
    (or shared a lock between two tenants whose hashtext collided
    after a hash-function swap), this test would hang here and the
    timeout would trip.

    180 s is generous: with ``pg_test_pool`` capped at ``max_size=5``
    the 1000 tasks queue through 5 connections; per-tenant the 100
    audit writes serialise on the per-tenant advisory lock. Locally
    on PG 16 the full storm finishes in 30-60 s; in CI the budget
    is 3× to absorb cold-start variance.
    """
    pool = _y10_row1_db
    await _seed_full_y10_row1_fixture(pool)

    # Build the 1000-task vector + shuffle so the asyncio scheduler
    # cannot accidentally serialise tenant-by-tenant or project-by-
    # project.
    job_specs: list[tuple[int, int, int]] = []
    for t in range(_TENANTS_N):
        for p in range(_PROJECTS_PER_TENANT):
            for u in range(_USERS_PER_TENANT):
                job_specs.append((t, p, u))
    random.shuffle(job_specs)
    assert len(job_specs) == _TOTAL_RUNS

    coros = [_run_one_workflow_task(t=t, p=p, u=u) for (t, p, u) in job_specs]
    started = time.monotonic()
    results = await asyncio.wait_for(
        asyncio.gather(*coros), timeout=180.0,
    )
    elapsed = time.monotonic() - started

    # The wait_for itself enforces no-deadlock; if we reach here the
    # storm completed. The remaining assertions are sanity on the
    # result vector before the per-row attribution checks below.
    assert len(results) == _TOTAL_RUNS
    seen_ids: set[str] = set()
    for run_id, tid, pid, email in results:
        assert run_id not in seen_ids, f"duplicate run_id {run_id!r}"
        seen_ids.add(run_id)
        assert tid.startswith(_TENANT_PREFIX)
        assert pid.startswith(_PROJECT_PREFIX)
    assert len(seen_ids) == _TOTAL_RUNS

    # Wall-clock observation for posterity (no hard assertion — we
    # already passed the 180 s timeout). The print is captured by
    # pytest -s for performance baselining.
    print(
        f"[Y10 row 1] {_TOTAL_RUNS} concurrent workflow_runs "
        f"completed in {elapsed:.2f}s"
    )


@_requires_pg
@pytest.mark.asyncio
async def test_concurrent_runs_billing_attribution_no_cross_talk(
    _y10_row1_db,
):
    """For each of the 1000 finished runs, the
    ``billing_usage_events`` row's ``(tenant_id, project_id)``
    tuple matches the explicit tuple we started the run with — NO
    cross-talk leaked attribution into a different tenant or a
    different project within the same tenant.

    This is the load-bearing assertion for the "無 quota
    mis-attribution" half of Y10 row 1. A regression that read
    tenant/project from the request-scope ContextVar (instead of
    the workflow_runs DB row) would surface here as scattered
    mis-attributions — under heavy concurrency the ContextVar slot
    on a recycled asyncio task could carry whichever tenant the
    last task set (the event-loop guarantee is per-Task, not
    per-coroutine, and a ``finally``-block reset is what protects
    us in this codebase).
    """
    pool = _y10_row1_db
    await _seed_full_y10_row1_fixture(pool)

    job_specs: list[tuple[int, int, int]] = []
    for t in range(_TENANTS_N):
        for p in range(_PROJECTS_PER_TENANT):
            for u in range(_USERS_PER_TENANT):
                job_specs.append((t, p, u))
    random.shuffle(job_specs)

    coros = [_run_one_workflow_task(t=t, p=p, u=u) for (t, p, u) in job_specs]
    results = await asyncio.wait_for(
        asyncio.gather(*coros), timeout=180.0,
    )
    expected = {run_id: (tid, pid) for run_id, tid, pid, _ in results}
    assert len(expected) == _TOTAL_RUNS

    async with pool.acquire() as conn:
        rows = await conn.fetch(
            "SELECT workflow_run_id, tenant_id, project_id "
            "FROM billing_usage_events "
            "WHERE kind = 'workflow_run' "
            "  AND workflow_run_id = ANY($1::text[])",
            list(expected.keys()),
        )

    # Exactly one billing row per finish() — no doubling, no drops.
    assert len(rows) == _TOTAL_RUNS, (
        f"expected {_TOTAL_RUNS} workflow_run billing rows, got "
        f"{len(rows)} — Y10 row 1 quota-attribution invariant"
    )

    mismatches: list[str] = []
    for r in rows:
        run_id = r["workflow_run_id"]
        exp_tid, exp_pid = expected[run_id]
        if r["tenant_id"] != exp_tid or r["project_id"] != exp_pid:
            mismatches.append(
                f"{run_id}: expected ({exp_tid}, {exp_pid}), got "
                f"({r['tenant_id']}, {r['project_id']})"
            )
    assert not mismatches, (
        f"{len(mismatches)} cross-talk mis-attributions under load: "
        f"{mismatches[:5]} ... (truncated)"
    )


@_requires_pg
@pytest.mark.asyncio
async def test_concurrent_runs_per_tenant_audit_chain_intact(
    _y10_row1_db,
):
    """After 1000 concurrent ``audit.log`` writes (100 per tenant,
    interleaved cross-tenant) every tenant's chain still verifies.

    This is the load-bearing assertion for the "audit chain doesn't
    break under concurrent storms" half of Y10 row 1. The chain
    write path holds ``pg_advisory_xact_lock(hashtext('audit-chain-'
    || tenant_id))`` so within-tenant writes serialise, but
    cross-tenant writes parallelise. A bug that shared the lock
    key across tenants would produce racy prev_hash reads → broken
    chains.
    """
    from backend import audit

    pool = _y10_row1_db
    await _seed_full_y10_row1_fixture(pool)

    job_specs: list[tuple[int, int, int]] = []
    for t in range(_TENANTS_N):
        for p in range(_PROJECTS_PER_TENANT):
            for u in range(_USERS_PER_TENANT):
                job_specs.append((t, p, u))
    random.shuffle(job_specs)

    coros = [_run_one_workflow_task(t=t, p=p, u=u) for (t, p, u) in job_specs]
    await asyncio.wait_for(asyncio.gather(*coros), timeout=180.0)

    # Every tenant's chain verifies independently. ``verify_all_chains``
    # walks every distinct tenant_id present in audit_log so we don't
    # have to enumerate manually.
    results = await audit.verify_all_chains()

    broken: list[tuple[str, int]] = []
    for tid, (ok, bad_id) in results.items():
        if not tid.startswith(_TENANT_PREFIX):
            continue  # ignore unrelated tenants from prior leaks
        if not ok:
            broken.append((tid, bad_id or -1))

    assert not broken, (
        f"audit chain broken on {len(broken)} tenants: {broken[:5]} "
        f"... (truncated) — Y10 row 1 cross-tenant chain invariant"
    )

    # And every Y10 row 1 tenant must have produced exactly 100
    # audit rows (1 per workflow_run × 100 runs per tenant).
    expected_per_tenant = _PROJECTS_PER_TENANT * _USERS_PER_TENANT
    async with pool.acquire() as conn:
        for t in range(_TENANTS_N):
            tid = _tenant_id(t)
            n = await conn.fetchval(
                "SELECT COUNT(*) FROM audit_log "
                "WHERE tenant_id = $1 AND action = $2",
                tid, "workflow.started",
            )
            assert n == expected_per_tenant, (
                f"tenant {tid}: expected {expected_per_tenant} "
                f"'workflow.started' audit rows, got {n}"
            )


@_requires_pg
@pytest.mark.asyncio
async def test_concurrent_runs_no_cross_tenant_audit_log_leak(
    _y10_row1_db,
):
    """For each tenant, every audit_log row that bears that
    tenant_id must reference one of that tenant's workflow_runs —
    NOT another tenant's. A leaked ContextVar between asyncio
    tasks would produce audit rows whose ``after_json.user_id``
    references a user from a different tenant; this test
    cross-checks the (tenant_id, after_json.user_id) tuple
    against the known seed map.
    """
    import json

    pool = _y10_row1_db
    await _seed_full_y10_row1_fixture(pool)

    job_specs: list[tuple[int, int, int]] = []
    for t in range(_TENANTS_N):
        for p in range(_PROJECTS_PER_TENANT):
            for u in range(_USERS_PER_TENANT):
                job_specs.append((t, p, u))
    random.shuffle(job_specs)

    coros = [_run_one_workflow_task(t=t, p=p, u=u) for (t, p, u) in job_specs]
    await asyncio.wait_for(asyncio.gather(*coros), timeout=180.0)

    # The (tenant, user) seed map: every user u in tenant t belongs
    # ONLY to tenant t (the seed never cross-memberships).
    expected_users_per_tenant: dict[str, set[str]] = {
        _tenant_id(t): {_user_id(t, u) for u in range(_USERS_PER_TENANT)}
        for t in range(_TENANTS_N)
    }

    async with pool.acquire() as conn:
        rows = await conn.fetch(
            "SELECT tenant_id, after_json FROM audit_log "
            "WHERE action = 'workflow.started' "
            "  AND tenant_id LIKE $1",
            f"{_TENANT_PREFIX}-%",
        )

    leaks: list[str] = []
    for r in rows:
        tid = r["tenant_id"]
        try:
            payload = json.loads(r["after_json"] or "{}")
        except Exception:
            leaks.append(f"{tid}: malformed after_json")
            continue
        uid = payload.get("user_id", "")
        if uid not in expected_users_per_tenant.get(tid, set()):
            leaks.append(f"{tid} carries foreign user_id {uid!r}")

    assert not leaks, (
        f"{len(leaks)} cross-tenant audit-log user_id leaks: "
        f"{leaks[:5]} ... (truncated)"
    )


@_requires_pg
@pytest.mark.asyncio
async def test_concurrent_runs_per_project_billing_count_aligns(
    _y10_row1_db,
):
    """For each (tenant, project) pair, the count of
    ``kind='workflow_run'`` rows in ``billing_usage_events`` is
    exactly ``_USERS_PER_TENANT == 5`` — one per user. This is the
    fine-grained quota-attribution assertion.

    A bug that double-emitted (e.g. a retry adapter firing
    record_workflow_run twice on the same finish) would surface
    as 6+ rows per project. A bug that dropped emissions under
    pool contention would surface as <5 rows. Either case fails
    the Y10 row 1 acceptance.
    """
    pool = _y10_row1_db
    await _seed_full_y10_row1_fixture(pool)

    job_specs: list[tuple[int, int, int]] = []
    for t in range(_TENANTS_N):
        for p in range(_PROJECTS_PER_TENANT):
            for u in range(_USERS_PER_TENANT):
                job_specs.append((t, p, u))
    random.shuffle(job_specs)

    coros = [_run_one_workflow_task(t=t, p=p, u=u) for (t, p, u) in job_specs]
    await asyncio.wait_for(asyncio.gather(*coros), timeout=180.0)

    async with pool.acquire() as conn:
        # GROUP BY (tenant_id, project_id) — should be exactly 200
        # buckets, each with count = 5.
        rows = await conn.fetch(
            "SELECT tenant_id, project_id, COUNT(*) AS n "
            "FROM billing_usage_events "
            "WHERE kind = 'workflow_run' "
            "  AND tenant_id LIKE $1 "
            "GROUP BY tenant_id, project_id "
            "ORDER BY tenant_id, project_id",
            f"{_TENANT_PREFIX}-%",
        )

    # Exactly 200 (tenant, project) buckets.
    expected_buckets = _TENANTS_N * _PROJECTS_PER_TENANT
    assert len(rows) == expected_buckets, (
        f"expected {expected_buckets} (tenant, project) buckets in "
        f"billing breakdown; got {len(rows)}"
    )

    bad: list[str] = []
    for r in rows:
        n = int(r["n"])
        if n != _USERS_PER_TENANT:
            bad.append(
                f"{r['tenant_id']}/{r['project_id']}: "
                f"{n} != {_USERS_PER_TENANT}"
            )
    assert not bad, (
        f"per-project billing count drift on {len(bad)} buckets: "
        f"{bad[:5]} ... (truncated)"
    )


@_requires_pg
@pytest.mark.asyncio
async def test_concurrent_runs_breakdown_endpoint_aligns_per_tenant(
    _y10_row1_db,
):
    """The T6 pricing-page breakdown
    (``billing_usage.breakdown_by_project``) for each tenant returns
    exactly 20 project rows, each with ``workflow_runs == 5``.

    Cross-checks the SUM(...) GROUP BY aggregation behaves
    correctly under heavy load — a regression in
    ``breakdown_by_project`` (e.g. a missing GROUP BY column) would
    produce wildly different counts. This is the operator-facing
    surface of Y10 row 1's "no quota mis-attribution".
    """
    from backend import billing_usage as bu

    pool = _y10_row1_db
    await _seed_full_y10_row1_fixture(pool)

    job_specs: list[tuple[int, int, int]] = []
    for t in range(_TENANTS_N):
        for p in range(_PROJECTS_PER_TENANT):
            for u in range(_USERS_PER_TENANT):
                job_specs.append((t, p, u))
    random.shuffle(job_specs)

    coros = [_run_one_workflow_task(t=t, p=p, u=u) for (t, p, u) in job_specs]
    await asyncio.wait_for(asyncio.gather(*coros), timeout=180.0)

    bad: list[str] = []
    for t in range(_TENANTS_N):
        tid = _tenant_id(t)
        breakdown = await bu.breakdown_by_project(tenant_id=tid)
        if len(breakdown) != _PROJECTS_PER_TENANT:
            bad.append(
                f"{tid}: breakdown len {len(breakdown)} != "
                f"{_PROJECTS_PER_TENANT}"
            )
            continue
        seen_pids = {row["project_id"] for row in breakdown}
        expected_pids = {
            _project_id(t, p) for p in range(_PROJECTS_PER_TENANT)
        }
        if seen_pids != expected_pids:
            bad.append(
                f"{tid}: breakdown projects mismatch — "
                f"missing={expected_pids - seen_pids}, "
                f"extra={seen_pids - expected_pids}"
            )
            continue
        for row in breakdown:
            if row["workflow_runs"] != _USERS_PER_TENANT:
                bad.append(
                    f"{tid}/{row['project_id']}: "
                    f"workflow_runs={row['workflow_runs']} != "
                    f"{_USERS_PER_TENANT}"
                )
    assert not bad, (
        f"breakdown_by_project drift on {len(bad)} entries: "
        f"{bad[:5]} ... (truncated)"
    )


@_requires_pg
@pytest.mark.asyncio
async def test_concurrent_runs_workflow_runs_status_completed(
    _y10_row1_db,
):
    """Every one of the 1000 workflow_runs lands at status
    ``'completed'`` after the storm — proves no run silently
    dropped its finish() under the contention. A pool-saturation
    bug (e.g. ``finish`` swallowed an asyncpg ``ConnectionDoesNotExistError``
    via its best-effort outer try/except) would surface as a
    workflow_runs row stuck at ``status='running'``.
    """
    pool = _y10_row1_db
    await _seed_full_y10_row1_fixture(pool)

    job_specs: list[tuple[int, int, int]] = []
    for t in range(_TENANTS_N):
        for p in range(_PROJECTS_PER_TENANT):
            for u in range(_USERS_PER_TENANT):
                job_specs.append((t, p, u))
    random.shuffle(job_specs)

    coros = [_run_one_workflow_task(t=t, p=p, u=u) for (t, p, u) in job_specs]
    await asyncio.wait_for(asyncio.gather(*coros), timeout=180.0)

    async with pool.acquire() as conn:
        n_total = await conn.fetchval(
            "SELECT COUNT(*) FROM workflow_runs WHERE id LIKE $1",
            "wf-y10r1-%",
        )
        n_completed = await conn.fetchval(
            "SELECT COUNT(*) FROM workflow_runs "
            "WHERE id LIKE $1 AND status = 'completed'",
            "wf-y10r1-%",
        )
        n_running = await conn.fetchval(
            "SELECT COUNT(*) FROM workflow_runs "
            "WHERE id LIKE $1 AND status = 'running'",
            "wf-y10r1-%",
        )

    assert n_total == _TOTAL_RUNS
    assert n_completed == _TOTAL_RUNS, (
        f"expected {_TOTAL_RUNS} 'completed' runs, got {n_completed} "
        f"({n_running} stuck at 'running' — possible swallowed "
        f"finish() failure under concurrency)"
    )
    assert n_running == 0


@_requires_pg
@pytest.mark.asyncio
async def test_smaller_scale_concurrency_smoke(_y10_row1_db):
    """A 3 × 3 × 3 = 27-task smoke version of the same fan-out so
    a CI runner with a slow PG can still rule out regressions
    quickly without the full 30-60 s budget of the 1000-task case.

    If the 1000-task storm trips a transient flake (e.g. asyncpg
    pool exhaustion under cold-start), this 27-task variant still
    catches the structural deadlock / cross-talk regression. The
    dimensions stay in proportion (each tenant has both multiple
    projects AND multiple users) so the contextvar isolation +
    per-tenant lock contract is still exercised.
    """
    from backend import audit

    pool = _y10_row1_db

    # Seed a smaller fixture inline (don't reuse the full helper —
    # it always seeds 10 × 20 × 5).
    smoke_tenants = [f"{_TENANT_PREFIX}-smoke-{t:02d}" for t in range(3)]
    async with pool.acquire() as conn:
        async with conn.transaction():
            for t_idx, tid in enumerate(smoke_tenants):
                await conn.execute(
                    "INSERT INTO tenants (id, name, plan) "
                    "VALUES ($1, $2, 'free') "
                    "ON CONFLICT (id) DO NOTHING",
                    tid, f"Y10R1-smoke-{t_idx}",
                )
                for p_idx in range(3):
                    pid = f"p-y10r1-smoke-{t_idx}-{p_idx}"
                    await conn.execute(
                        "INSERT INTO projects "
                        "(id, tenant_id, product_line, name, slug) "
                        "VALUES ($1, $2, 'embedded', $3, $4) "
                        "ON CONFLICT (tenant_id, product_line, slug) "
                        "DO NOTHING",
                        pid, tid, f"smoke-{t_idx}-{p_idx}",
                        f"smoke-{t_idx}-{p_idx}",
                    )

    async def _smoke_task(tid: str, pid: str, u: int) -> str:
        from backend.db_context import set_project_id, set_tenant_id
        from backend.db_pool import get_pool
        from backend import workflow

        run_id = f"wf-{pid}-u{u}"
        set_tenant_id(tid)
        set_project_id(pid)
        try:
            async with get_pool().acquire() as conn:
                await conn.execute(
                    "INSERT INTO workflow_runs "
                    "(id, kind, started_at, status, metadata, "
                    " tenant_id, project_id) "
                    "VALUES ($1, 'invoke', $2, 'running', '{}', $3, $4)",
                    run_id, time.time(), tid, pid,
                )
            await audit.log(
                "workflow.started", "workflow_run", run_id,
                after={"smoke": True}, actor=f"smoke-u{u}@y10r1.local",
            )
            await workflow.finish(run_id, status="completed")
        finally:
            set_tenant_id(None)
            set_project_id(None)
        return run_id

    coros = []
    for t_idx, tid in enumerate(smoke_tenants):
        for p_idx in range(3):
            pid = f"p-y10r1-smoke-{t_idx}-{p_idx}"
            for u in range(3):
                coros.append(_smoke_task(tid, pid, u))
    random.shuffle(coros)
    run_ids = await asyncio.wait_for(
        asyncio.gather(*coros), timeout=60.0,
    )
    assert len(set(run_ids)) == 27

    # Each tenant's chain verifies; each tenant's smoke runs all
    # finished completed.
    results = await audit.verify_all_chains()
    for tid in smoke_tenants:
        ok, bad = results.get(tid, (False, None))
        assert ok, f"smoke tenant {tid} chain broken at {bad}"

    async with pool.acquire() as conn:
        n_completed = await conn.fetchval(
            "SELECT COUNT(*) FROM workflow_runs "
            "WHERE id LIKE 'wf-p-y10r1-smoke-%' AND status = 'completed'"
        )
        n_billing = await conn.fetchval(
            "SELECT COUNT(*) FROM billing_usage_events "
            "WHERE kind = 'workflow_run' "
            "  AND workflow_run_id LIKE 'wf-p-y10r1-smoke-%'"
        )
    assert n_completed == 27
    assert n_billing == 27

    # Cleanup the smoke-only rows (regular fixture TRUNCATE only
    # cleans the LIKE 'y10r1-%' pattern by tenant_id, which we hit;
    # but the projects table cleanup is via tenant_id LIKE so the
    # smoke projects above DO get cleaned by the fixture teardown).
