"""OP-787 dynamic lessons-learned index contract for the docs-site build."""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

from backend import docs_site_lessons as lessons

REPO_ROOT = Path(__file__).resolve().parents[2]
LESSONS_DIR = REPO_ROOT / "docs" / "sop" / "lessons"
GENERATED_INDEX = REPO_ROOT / "docs" / "sop" / "lessons-learned.md"


def _write_lesson(
    directory: Path,
    *,
    filename: str,
    lesson_id: str,
    ticket: str,
    title: str,
    date: str,
    legacy_lesson: int | None = None,
) -> Path:
    path = directory / filename
    frontmatter = [
        "---",
        f"id: {lesson_id}",
        f"ticket: {ticket}",
        f"title: {title}",
        f"date: {date}",
        "tags: [runner]",
    ]
    if legacy_lesson is not None:
        frontmatter.append(f"legacy_lesson: {legacy_lesson}")
    path.write_text(
        "\n".join(
            [
                *frontmatter,
                "---",
                "",
                f"# {title}",
                "",
                "**Situation**",
                "",
                "A concrete situation.",
                "",
                "**Fix**",
                "",
                "A concrete fix.",
                "",
                "**Verification**",
                "",
                "A concrete verification.",
                "",
                "**Generalisation**",
                "",
                "A concrete generalisation.",
                "",
            ]
        ),
        encoding="utf-8",
    )
    return path


def _legacy_render(records: list[lessons.LessonRecord]) -> str:
    lines = [
        "# Lessons Learned — OmniSight",
        "",
        "<!-- AUTO-GENERATED by scripts/build_lessons_index.py; do not edit by hand. -->",
        "",
        "**Status**: Generated index. Add or edit individual lessons under `docs/sop/lessons/`.",
        "",
        "**Authority**: Owned by operator + AI fleet collectively. Each lesson file must include "
        "`Situation`, `Fix`, `Verification`, and `Generalisation` sections. Vague entries "
        "(`be more careful`, `pay attention`) are auto-rejected by the META retrospective "
        "workflow (per `docs/sop/jira-ticket-conventions.md` §14).",
        "",
        "**How entries land here**:",
        "1. From META retrospective tickets (label `meta:lessons-learned`) once Approved",
        "2. From cross-Phase retrospectives (`docs/retrospectives/YYYY-MM-DD-<slug>.md`) that distil into a generalisable lesson",
        "3. Direct operator append when codifying tribal knowledge",
        "",
        "---",
        "",
        "## Index",
        "",
        "| ID | Date | Ticket | Lesson | Legacy |",
        "|---|---|---|---|---|",
    ]
    for lesson in records:
        legacy = f"L{lesson.legacy_lesson}" if lesson.legacy_lesson is not None else ""
        lines.append(
            f"| {lesson.id} | {lesson.date} | {lesson.ticket} | "
            f"[{lesson.title}]({lesson.relpath}) | {legacy} |"
        )

    note = lessons.legacy_number_note(records)
    if note:
        lines.extend(["", note.rstrip()])

    lines.extend(["", "---", ""])
    for lesson in records:
        lines.extend(
            [
                f"## {lesson.id} — {lesson.title} ({lesson.date})",
                "",
                f"Source: [`{lesson.relpath}`]({lesson.relpath})",
                "",
                lesson.body.rstrip(),
                "",
                "---",
                "",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def _normalise_dynamic_links(text: str, records: list[lessons.LessonRecord]) -> str:
    normalised = text.replace(
        "**Status**: Dynamic docs-site index.",
        "**Status**: Generated index.",
    )
    normalised = normalised.replace(
        "<!-- AUTO-GENERATED by scripts/build_lessons_index.py; do not edit by hand. -->\n\n",
        "",
    )
    for lesson in records:
        normalised = normalised.replace(lesson.docs_site_url, lesson.relpath)
    return normalised


def test_load_lessons_reads_frontmatter_and_sorts_chronologically(tmp_path: Path) -> None:
    _write_lesson(
        tmp_path,
        filename="L-OP-802-second.md",
        lesson_id="L-OP-802",
        ticket="OP-802",
        title="Second",
        date="2026-05-03",
    )
    _write_lesson(
        tmp_path,
        filename="L-OP-801-first.md",
        lesson_id="L-OP-801",
        ticket="OP-801",
        title="First",
        date="2026-05-02",
        legacy_lesson=41,
    )
    _write_lesson(
        tmp_path,
        filename="L-LEGACY-001-legacy.md",
        lesson_id="L-LEGACY-001",
        ticket="LEGACY-001",
        title="Legacy",
        date="2026-05-01",
        legacy_lesson=1,
    )
    (tmp_path / "_TEMPLATE.md").write_text("# ignored\n", encoding="utf-8")

    records = lessons.load_lessons(tmp_path)

    assert [record.id for record in records] == ["L-LEGACY-001", "L-OP-801", "L-OP-802"]
    assert [record.legacy_lesson for record in records] == [1, 41, None]


def test_render_lessons_index_uses_docs_site_urls_and_embeds_sections(tmp_path: Path) -> None:
    _write_lesson(
        tmp_path,
        filename="L-OP-787-dynamic-lessons.md",
        lesson_id="L-OP-787",
        ticket="OP-787",
        title="Dynamic Lessons",
        date="2026-05-08",
        legacy_lesson=42,
    )

    rendered = lessons.build_lessons_index(tmp_path)

    assert "| L-OP-787 | 2026-05-08 | OP-787 | [Dynamic Lessons](/docs/sop/lessons/L-OP-787-dynamic-lessons/) | L42 |" in rendered
    assert "## L-OP-787 — Dynamic Lessons (2026-05-08)" in rendered
    assert "Source: [`" in rendered
    assert "L-OP-787-dynamic-lessons.md)" not in rendered
    assert "**Situation**" in rendered
    assert "**Generalisation**" in rendered


def test_dynamic_lessons_index_is_semantically_equivalent_to_old_generated_index() -> None:
    records = lessons.load_lessons(LESSONS_DIR)
    rendered = lessons.render_lessons_index(records)
    old_rendered = _legacy_render(records)

    assert _normalise_dynamic_links(rendered, records) == old_rendered.replace(
        "<!-- AUTO-GENERATED by scripts/build_lessons_index.py; do not edit by hand. -->\n\n",
        "",
    )
    assert "AUTO-GENERATED by scripts/build_lessons_index.py" not in rendered


def test_repo_lesson_sources_have_frontmatter_and_standard_sections() -> None:
    records = lessons.load_lessons(LESSONS_DIR)

    assert len(records) >= 31
    assert (LESSONS_DIR / "L-OP-741-ci-recovery-needs-a-small-explicit-state-machine.md").exists()
    assert (
        LESSONS_DIR
        / "L-OP-742-test-impact-analysis-must-fail-closed-on-the-conservative-si.md"
    ).exists()
    assert {record.id for record in records} >= {"L-OP-740", "L-OP-741", "L-OP-742"}
    lessons.check_standard_sections(records)


def test_old_build_lessons_index_script_is_noop_and_does_not_write_generated_file() -> None:
    if GENERATED_INDEX.exists():
        GENERATED_INDEX.unlink()

    subprocess.run([sys.executable, "scripts/build_lessons_index.py"], cwd=REPO_ROOT, check=True)

    assert not GENERATED_INDEX.exists()


def test_three_parallel_lesson_files_merge_without_conflict(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    repo.mkdir()
    subprocess.run(["git", "init", "-q", "-b", "main"], cwd=repo, check=True)
    subprocess.run(["git", "config", "user.email", "test@example.invalid"], cwd=repo, check=True)
    subprocess.run(["git", "config", "user.name", "Test User"], cwd=repo, check=True)
    (repo / "docs/sop/lessons").mkdir(parents=True)
    (repo / "docs/sop/lessons/.gitkeep").write_text("", encoding="utf-8")
    subprocess.run(["git", "add", "."], cwd=repo, check=True)
    subprocess.run(["git", "commit", "-q", "-m", "base"], cwd=repo, check=True)

    for ticket in ("OP-801", "OP-802", "OP-803"):
        subprocess.run(["git", "switch", "-q", "-c", ticket, "main"], cwd=repo, check=True)
        path = repo / "docs/sop/lessons" / f"L-{ticket}-parallel.md"
        path.write_text(f"lesson for {ticket}\n", encoding="utf-8")
        subprocess.run(["git", "add", str(path.relative_to(repo))], cwd=repo, check=True)
        subprocess.run(["git", "commit", "-q", "-m", ticket], cwd=repo, check=True)

    subprocess.run(["git", "switch", "-q", "main"], cwd=repo, check=True)
    for ticket in ("OP-801", "OP-802", "OP-803"):
        subprocess.run(["git", "merge", "--no-ff", "--no-edit", ticket], cwd=repo, check=True)

    merged = sorted(path.name for path in (repo / "docs/sop/lessons").glob("L-OP-*.md"))
    assert merged == [
        "L-OP-801-parallel.md",
        "L-OP-802-parallel.md",
        "L-OP-803-parallel.md",
    ]
