"""N1 — Dependency governance guards.

These tests are the runtime counterpart to the `lockfile-drift` CI job.
They run fast (pure filesystem/string inspection, no network) and fail
loudly whenever the repo's hand-written invariants about lockfiles,
Node version pins, and Docker hash enforcement are broken.

What we check:

1. `package.json` pins `engines.node` / `engines.pnpm` and names
   `pnpm` as the package manager.
2. `.nvmrc` / `.node-version` both read `20.17.0` (kept in lockstep so
   nvm, fnm, asdf, Volta all pick up the same version).
3. Single-lockfile policy: `pnpm-lock.yaml` exists; `package-lock.json`
   and `yarn.lock` do NOT (they are also `.gitignore`d so a stray
   `npm install` can't accidentally re-commit one).
4. `backend/requirements.in` exists and is the source of truth.
5. `backend/requirements.txt` is a pip-tools hash-lockfile (autogenerated
   header + `--hash=sha256:...` tokens on every pin).
6. `Dockerfile.backend` installs with `--require-hashes`.
7. CI workflow contains the `lockfile-drift` job.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]


# ---------------------------------------------------------------------------
# package.json engines + packageManager
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module")
def package_json() -> dict:
    return json.loads((REPO_ROOT / "package.json").read_text(encoding="utf-8"))


def test_package_json_engines_pins_node_20(package_json: dict) -> None:
    engines = package_json.get("engines")
    assert engines, "package.json must declare engines (N1)"
    node_range = engines.get("node", "")
    # Must pin to 20.17.0+ and cap before the next major.
    assert ">=20.17.0" in node_range, f"node engine must require >=20.17.0, got {node_range!r}"
    assert "<21" in node_range, f"node engine must cap <21, got {node_range!r}"


def test_package_json_engines_pins_pnpm(package_json: dict) -> None:
    pnpm_range = package_json.get("engines", {}).get("pnpm", "")
    assert pnpm_range.startswith(">=9"), f"pnpm engine must require >=9, got {pnpm_range!r}"


def test_package_json_declares_pnpm_as_package_manager(package_json: dict) -> None:
    pm = package_json.get("packageManager", "")
    assert pm.startswith("pnpm@"), (
        f"packageManager must be pnpm (N1 single-lockfile policy), got {pm!r}"
    )


# ---------------------------------------------------------------------------
# Node version files kept in lockstep
# ---------------------------------------------------------------------------

def test_nvmrc_and_node_version_match() -> None:
    nvmrc = (REPO_ROOT / ".nvmrc").read_text(encoding="utf-8").strip()
    nodever = (REPO_ROOT / ".node-version").read_text(encoding="utf-8").strip()
    assert nvmrc == "20.17.0", f".nvmrc must be 20.17.0, got {nvmrc!r}"
    assert nodever == "20.17.0", f".node-version must be 20.17.0, got {nodever!r}"
    assert nvmrc == nodever, "nvmrc and node-version must match"


# ---------------------------------------------------------------------------
# Single-lockfile policy
# ---------------------------------------------------------------------------

def test_pnpm_lock_exists() -> None:
    assert (REPO_ROOT / "pnpm-lock.yaml").is_file(), (
        "pnpm-lock.yaml is the canonical JS lockfile (N1) — it must be committed"
    )


def test_no_stray_js_lockfiles() -> None:
    # These lockfiles are explicitly forbidden under the single-lockfile
    # policy. The CI job `lockfile-drift` enforces the same rule.
    stray = [f for f in ("package-lock.json", "yarn.lock") if (REPO_ROOT / f).exists()]
    assert not stray, f"Stray lockfile(s) committed: {stray} — delete them (N1 policy)"


def test_gitignore_blocks_stray_lockfiles() -> None:
    gi = (REPO_ROOT / ".gitignore").read_text(encoding="utf-8")
    assert "package-lock.json" in gi, ".gitignore must block package-lock.json (N1)"
    assert "yarn.lock" in gi, ".gitignore must block yarn.lock (N1)"


# ---------------------------------------------------------------------------
# Python hash-locked requirements
# ---------------------------------------------------------------------------

def test_requirements_in_exists() -> None:
    assert (REPO_ROOT / "backend" / "requirements.in").is_file(), (
        "backend/requirements.in is the source of truth for Python deps (N1)"
    )


@pytest.fixture(scope="module")
def requirements_txt() -> str:
    return (REPO_ROOT / "backend" / "requirements.txt").read_text(encoding="utf-8")


def test_requirements_txt_is_autogenerated_lockfile(requirements_txt: str) -> None:
    head = requirements_txt.splitlines()[:6]
    joined = "\n".join(head)
    assert "autogenerated by pip-compile" in joined, (
        "backend/requirements.txt must be regenerated via `pip-compile --generate-hashes`"
    )
    assert "--generate-hashes" in joined, (
        "pip-compile invocation must include --generate-hashes in the header"
    )


def test_requirements_txt_has_hashes_on_every_pin(requirements_txt: str) -> None:
    # Every package line (ends with `==X.Y.Z \`) must have at least one
    # accompanying `--hash=sha256:...` token.
    pins = re.findall(r"^([a-zA-Z0-9._\[\]-]+)==[^\s]+\s*\\\s*$", requirements_txt, re.MULTILINE)
    assert pins, "no pins detected in requirements.txt (lockfile generation broken?)"
    hash_count = requirements_txt.count("--hash=sha256:")
    # Each pin should have >=1 hash; wheels + sdists usually give >=2.
    assert hash_count >= len(pins), (
        f"requirements.txt has {len(pins)} pins but only {hash_count} sha256 hashes"
    )


# ---------------------------------------------------------------------------
# Docker + CI wiring
# ---------------------------------------------------------------------------

def test_dockerfile_backend_uses_require_hashes() -> None:
    dockerfile = (REPO_ROOT / "Dockerfile.backend").read_text(encoding="utf-8")
    assert "--require-hashes" in dockerfile, (
        "Dockerfile.backend must `pip install --require-hashes -r requirements.txt` (N1)"
    )


def test_ci_has_lockfile_drift_job() -> None:
    ci = (REPO_ROOT / ".github" / "workflows" / "ci.yml").read_text(encoding="utf-8")
    assert "lockfile-drift:" in ci, (
        "CI workflow must define a `lockfile-drift` job (N1)"
    )
    # The drift job must actually regenerate and diff the Python lock.
    assert "pip-compile" in ci, "lockfile-drift job must re-run pip-compile"
    assert "--frozen-lockfile" in ci, "lockfile-drift job must enforce pnpm frozen lockfile"


# ---------------------------------------------------------------------------
# N2 — Renovate policy guards
# ---------------------------------------------------------------------------
#
# These tests are static-only: they validate the *shape* of `renovate.json`
# (groups present, tier rules wired, security path immediate) so a bad
# edit can't silently disable Renovate or weaken the auto-merge tiers.
# Schema-level validation is enforced by the CI `renovate-config` job
# which runs `renovate-config-validator --strict`.

@pytest.fixture(scope="module")
def renovate_config() -> dict:
    return json.loads((REPO_ROOT / "renovate.json").read_text(encoding="utf-8"))


def test_renovate_config_exists_and_is_json(renovate_config: dict) -> None:
    assert isinstance(renovate_config, dict)
    assert renovate_config.get("$schema", "").endswith("renovate-schema.json"), (
        "renovate.json must declare the renovate-schema.json $schema for editor support"
    )


def test_renovate_schedule_is_weekend(renovate_config: dict) -> None:
    sched = renovate_config.get("schedule")
    assert sched == ["every weekend"], (
        f"N2 policy requires schedule=['every weekend'] (low weekday noise), got {sched!r}"
    )


def test_renovate_vulnerability_alerts_immediate_and_automerge(renovate_config: dict) -> None:
    v = renovate_config.get("vulnerabilityAlerts", {})
    assert v.get("enabled") is True, "vulnerabilityAlerts must be enabled (N2)"
    assert v.get("automerge") is True, "vulnerabilityAlerts must auto-merge (N2 fastest path)"
    assert v.get("schedule") == ["at any time"], (
        "vulnerabilityAlerts must override the weekend schedule (open immediately)"
    )
    assert renovate_config.get("osvVulnerabilityAlerts") is True, (
        "OSV scanning catches CVEs before GHSA picks them up"
    )


def _find_rule(rules: list, predicate) -> dict | None:
    for r in rules:
        if predicate(r):
            return r
    return None


def test_renovate_security_priority_is_max(renovate_config: dict) -> None:
    rules = renovate_config["packageRules"]
    sec = _find_rule(rules, lambda r: r.get("isVulnerabilityAlert") is True)
    assert sec is not None, "Need a packageRule with isVulnerabilityAlert: true (N2 priority)"
    assert sec.get("prPriority", 0) >= 100, (
        "Security PR rule must set prPriority >= 100 to jump the queue"
    )
    assert sec.get("automerge") is True, "Security PRs must auto-merge"


def test_renovate_tier_patch_automerges(renovate_config: dict) -> None:
    rules = renovate_config["packageRules"]
    patch_rule = _find_rule(
        rules,
        lambda r: r.get("matchUpdateTypes") == ["patch", "pin", "digest"],
    )
    assert patch_rule is not None, "N2: missing PATCH tier rule"
    assert patch_rule.get("automerge") is True, "patch tier must auto-merge on green CI"
    assert patch_rule.get("platformAutomerge") is True, (
        "patch tier must use GitHub native auto-merge (platformAutomerge)"
    )


def test_renovate_tier_minor_no_automerge(renovate_config: dict) -> None:
    rules = renovate_config["packageRules"]
    minor_rule = _find_rule(rules, lambda r: r.get("matchUpdateTypes") == ["minor"])
    assert minor_rule is not None, "N2: missing MINOR tier rule"
    assert minor_rule.get("automerge") is False, (
        "minor tier must NOT auto-merge (1 human reviewer required)"
    )


def test_renovate_tier_major_blocked_and_blue_green(renovate_config: dict) -> None:
    rules = renovate_config["packageRules"]
    major_rule = _find_rule(rules, lambda r: r.get("matchUpdateTypes") == ["major"])
    assert major_rule is not None, "N2: missing MAJOR tier rule"
    assert major_rule.get("automerge") is False, (
        "major tier must NEVER auto-merge (2 reviewers + blue-green required)"
    )
    labels = major_rule.get("addLabels", [])
    assert "deploy/blue-green-required" in labels, (
        "major-tier PRs must be labelled deploy/blue-green-required so the deploy "
        "gate refuses non-blue-green merges (couples N2 to N10)"
    )


def test_renovate_groups_cover_required_families(renovate_config: dict) -> None:
    rules = renovate_config["packageRules"]
    groups = {r["groupSlug"] for r in rules if "groupSlug" in r}
    required = {"radix-ui", "ai-sdk", "langchain-py", "types"}
    missing = required - groups
    assert not missing, (
        f"N2 requires group rules for {required}; missing groupSlug(s): {missing}"
    )


def test_renovate_radix_group_pattern(renovate_config: dict) -> None:
    rules = renovate_config["packageRules"]
    radix = _find_rule(rules, lambda r: r.get("groupSlug") == "radix-ui")
    assert radix is not None
    names = radix.get("matchPackageNames", [])
    assert any("@radix-ui" in n for n in names), (
        f"radix-ui group must match @radix-ui/* package names, got {names!r}"
    )


def test_renovate_langchain_group_targets_python_managers(renovate_config: dict) -> None:
    rules = renovate_config["packageRules"]
    lc = _find_rule(rules, lambda r: r.get("groupSlug") == "langchain-py")
    assert lc is not None
    managers = lc.get("matchManagers", [])
    assert "pip-compile" in managers, (
        "langchain group must scope to Python managers (pip-compile) so the "
        "JS `langchain` package on npm doesn't accidentally land in the same PR"
    )


def test_renovate_types_group_automerges_minor(renovate_config: dict) -> None:
    rules = renovate_config["packageRules"]
    types_rule = _find_rule(rules, lambda r: r.get("groupSlug") == "types")
    assert types_rule is not None
    assert types_rule.get("automerge") is True, "@types/* group must auto-merge"
    update_types = types_rule.get("matchUpdateTypes", [])
    assert "minor" in update_types, (
        "@types/* group must auto-merge minor in addition to patch — they are "
        "dev-only DefinitelyTyped packages"
    )


def test_renovate_pip_compile_targets_lockfile(renovate_config: dict) -> None:
    pc = renovate_config.get("pip-compile", {})
    fm = pc.get("fileMatch", [])
    # Renovate's pip-compile manager scans the *lockfile* (requirements.txt)
    # and uses the .in file to keep it fresh — matching the .in file
    # disables the manager entirely.
    assert any("requirements\\.txt" in f for f in fm), (
        f"pip-compile manager must match requirements.txt, got {fm!r}"
    )


def test_ci_has_renovate_config_validation_job() -> None:
    ci = (REPO_ROOT / ".github" / "workflows" / "ci.yml").read_text(encoding="utf-8")
    assert "renovate-config:" in ci, (
        "CI must define a `renovate-config` job that schema-validates renovate.json (N2)"
    )
    assert "renovate-config-validator" in ci, (
        "renovate-config job must invoke renovate-config-validator"
    )


def test_renovate_policy_doc_exists() -> None:
    doc = REPO_ROOT / "docs" / "ops" / "renovate_policy.md"
    assert doc.is_file(), "N2 requires docs/ops/renovate_policy.md to be checked in"
    body = doc.read_text(encoding="utf-8")
    # The doc is the contract — these phrases must be present so the
    # policy doesn't silently lose its teeth via doc rot.
    for phrase in ("auto-merge", "blue-green", "every weekend", "vulnerability"):
        assert phrase.lower() in body.lower(), f"renovate_policy.md missing key term: {phrase!r}"


# ---------------------------------------------------------------------------
# N5 — Nightly Upgrade Preview guards
# ---------------------------------------------------------------------------
#
# These guards lock in the *shape* of the N5 wiring (workflow file,
# script, doc) so a careless edit can't quietly disarm the early-warning
# system. The behaviour of the script itself is covered in
# `test_upgrade_preview.py`; this section only checks file presence,
# trigger, label, and policy-doc invariants.

N5_WORKFLOW = REPO_ROOT / ".github" / "workflows" / "upgrade-preview.yml"
N5_SCRIPT = REPO_ROOT / "scripts" / "upgrade_preview.py"
N5_DOC = REPO_ROOT / "docs" / "ops" / "upgrade_preview.md"


@pytest.fixture(scope="module")
def upgrade_preview_workflow() -> str:
    return N5_WORKFLOW.read_text(encoding="utf-8")


def test_n5_workflow_file_exists(upgrade_preview_workflow: str) -> None:
    assert N5_WORKFLOW.is_file(), (
        "N5 requires .github/workflows/upgrade-preview.yml to be checked in"
    )
    assert "Nightly Upgrade Preview" in upgrade_preview_workflow, (
        "Workflow `name:` must read 'Nightly Upgrade Preview' so the "
        "GH Actions UI surfaces it under that label"
    )


def test_n5_workflow_runs_on_cron(upgrade_preview_workflow: str) -> None:
    # Must be cron-driven — the whole point is unattended nightly runs.
    assert "schedule:" in upgrade_preview_workflow, (
        "N5 workflow must declare a schedule trigger"
    )
    assert "cron:" in upgrade_preview_workflow, "N5 workflow must use a cron schedule"
    # Manual trigger as well, for ad-hoc previews.
    assert "workflow_dispatch:" in upgrade_preview_workflow, (
        "N5 workflow must also expose workflow_dispatch for ad-hoc runs"
    )


def test_n5_workflow_has_issues_write_permission(upgrade_preview_workflow: str) -> None:
    # Without `issues: write` the gh issue create call will 403 silently.
    assert "issues: write" in upgrade_preview_workflow, (
        "N5 workflow must request issues: write so it can post the "
        "preview issue under the dependency-preview label"
    )


def test_n5_workflow_uses_dependency_preview_label(upgrade_preview_workflow: str) -> None:
    assert "dependency-preview" in upgrade_preview_workflow, (
        "N5 workflow must label the issue dependency-preview (the "
        "label the operator triages off of every Monday)"
    )


def test_n5_workflow_calls_render_script(upgrade_preview_workflow: str) -> None:
    assert "scripts/upgrade_preview.py" in upgrade_preview_workflow, (
        "N5 workflow must invoke scripts/upgrade_preview.py to render "
        "the issue body — it's the single source of truth for layout "
        "and the breaking-bump heuristic"
    )


def test_n5_workflow_runs_pytest_and_playwright(upgrade_preview_workflow: str) -> None:
    # The whole point of the preview is to test against UPGRADED deps.
    assert "pytest" in upgrade_preview_workflow, (
        "N5 workflow must run pytest against the upgraded backend deps"
    )
    assert "playwright" in upgrade_preview_workflow, (
        "N5 workflow must run Playwright against the upgraded JS deps"
    )


def test_n5_workflow_does_not_force_push_or_commit(upgrade_preview_workflow: str) -> None:
    # Preview is read-only on master. Catch a careless edit that turns
    # the preview into a writer.
    forbidden = ("git push", "git commit", "contents: write")
    for needle in forbidden:
        assert needle not in upgrade_preview_workflow, (
            f"N5 workflow must not contain `{needle}` — preview is read-only"
        )


def test_n5_script_is_stdlib_only() -> None:
    # If the script grows third-party imports we lose the "no extra
    # pip install in the workflow" property. This is a coarse check —
    # it just verifies none of the obvious offenders sneak in.
    assert N5_SCRIPT.is_file(), "N5 requires scripts/upgrade_preview.py"
    src = N5_SCRIPT.read_text(encoding="utf-8")
    forbidden_imports = (
        "import requests",
        "import yaml",
        "import httpx",
        "from pydantic",
        "import pytest",  # pytest is a runtime dep of the suite, not the script
    )
    for needle in forbidden_imports:
        assert needle not in src, (
            f"scripts/upgrade_preview.py must stay stdlib-only "
            f"(found `{needle}`) — adding deps means the workflow has to "
            "install them, which defeats the 'preview survives broken deps' "
            "design"
        )


def test_n5_doc_exists() -> None:
    assert N5_DOC.is_file(), "N5 requires docs/ops/upgrade_preview.md"
    body = N5_DOC.read_text(encoding="utf-8")
    # Doc rot guard — these terms encode the contract operators rely on.
    for phrase in (
        "dependency-preview",
        "Renovate",
        "Suspected breaking",
        "workflow_dispatch",
        "every weekend",
    ):
        assert phrase.lower() in body.lower(), (
            f"docs/ops/upgrade_preview.md missing key term: {phrase!r}"
        )


# ---------------------------------------------------------------------------
# N6 — Upgrade Runbook + CVE scan + EOL monitor guards
# ---------------------------------------------------------------------------
#
# N6 adds three artefacts:
#   1. docs/ops/dependency_upgrade_runbook.md — the four-phase upgrade
#      procedure with rollback instructions.
#   2. .github/workflows/cve-scan.yml — daily OSV-Scanner run +
#      scripts/cve_triage.py issue renderer.
#   3. .github/workflows/eol-check.yml — monthly endoflife.date check +
#      scripts/check_eol.py issue renderer.
#
# These guards pin the *shape* of each artefact (file presence, cron,
# permissions, key sections) so a careless edit can't silently disarm
# the CVE/EOL early-warning system. Behaviour of the Python scripts
# is covered by test_cve_triage.py and test_check_eol.py.

N6_RUNBOOK = REPO_ROOT / "docs" / "ops" / "dependency_upgrade_runbook.md"
N6_CVE_WORKFLOW = REPO_ROOT / ".github" / "workflows" / "cve-scan.yml"
N6_EOL_WORKFLOW = REPO_ROOT / ".github" / "workflows" / "eol-check.yml"
N6_CVE_SCRIPT = REPO_ROOT / "scripts" / "cve_triage.py"
N6_EOL_SCRIPT = REPO_ROOT / "scripts" / "check_eol.py"


# ----- Runbook -------------------------------------------------------------

def test_n6_runbook_exists() -> None:
    assert N6_RUNBOOK.is_file(), (
        "N6 requires docs/ops/dependency_upgrade_runbook.md"
    )


def test_n6_runbook_has_four_phases() -> None:
    body = N6_RUNBOOK.read_text(encoding="utf-8")
    for phase in (
        "Phase 1 — Pre-upgrade",
        "Phase 2 — During upgrade",
        "Phase 3 — Post-upgrade",
        "Phase 4 — Rollback",
    ):
        assert phase in body, f"Runbook missing phase header: {phase!r}"


def test_n6_runbook_covers_required_topics() -> None:
    # Contract: the N6 TODO enumerates image snapshot, DB backup,
    # lockfile-clean, staging 24h, smoke test, 72h monitoring, and
    # rollback via git revert + docker compose pull. All must be in
    # the doc or operators will improvise.
    body = N6_RUNBOOK.read_text(encoding="utf-8").lower()
    required = [
        "image snapshot",
        "db",       # "DB backup" / "DB snapshot"
        "backup",
        "lockfile",
        "staging",
        "24h",      # 24h soak
        "smoke",
        "72h",
        "error rate",
        "latency",
        "memory",
        "rollback",
        "git revert",
        "docker compose",
    ]
    missing = [phrase for phrase in required if phrase not in body]
    assert not missing, (
        f"dependency_upgrade_runbook.md missing key phrases: {missing}"
    )


def test_n6_runbook_links_preview_and_renovate_docs() -> None:
    # Operators jump between docs; broken links make the SOP useless.
    body = N6_RUNBOOK.read_text(encoding="utf-8")
    assert "renovate_policy.md" in body, (
        "Runbook must reference renovate_policy.md (cross-link to N2)"
    )
    assert "upgrade_preview.md" in body, (
        "Runbook must reference upgrade_preview.md (cross-link to N5)"
    )


# ----- CVE scan workflow + script -----------------------------------------

@pytest.fixture(scope="module")
def cve_workflow_text() -> str:
    return N6_CVE_WORKFLOW.read_text(encoding="utf-8")


def test_n6_cve_workflow_exists(cve_workflow_text: str) -> None:
    assert N6_CVE_WORKFLOW.is_file(), (
        "N6 requires .github/workflows/cve-scan.yml"
    )
    assert "Daily CVE Scan" in cve_workflow_text, (
        "CVE workflow `name:` must read 'Daily CVE Scan'"
    )


def test_n6_cve_workflow_runs_daily(cve_workflow_text: str) -> None:
    # Must be cron-driven — daily is the cadence the TODO commits to.
    assert "schedule:" in cve_workflow_text
    assert "cron:" in cve_workflow_text
    assert "workflow_dispatch:" in cve_workflow_text


def test_n6_cve_workflow_uses_osv_scanner(cve_workflow_text: str) -> None:
    # The TODO calls out osv-scanner (or Snyk). We standardise on
    # osv-scanner because it's Google-backed, free, and requires no
    # secret management.
    assert "osv-scanner" in cve_workflow_text.lower(), (
        "CVE workflow must invoke osv-scanner (N6 TODO: 'osv-scanner or Snyk')"
    )


def test_n6_cve_workflow_has_required_permissions(cve_workflow_text: str) -> None:
    # issues:write is what gh issue create needs; security-events:write
    # is what the codeql SARIF upload needs.
    assert "issues: write" in cve_workflow_text, (
        "CVE workflow must grant issues:write to open tracking issues"
    )


def test_n6_cve_workflow_calls_triage_script(cve_workflow_text: str) -> None:
    assert "scripts/cve_triage.py" in cve_workflow_text, (
        "CVE workflow must call scripts/cve_triage.py to render the issue"
    )


def test_n6_cve_workflow_labels_tracking_issue(cve_workflow_text: str) -> None:
    # Labels are the operator's triage handle. The doc calls out
    # security/cve as the label and priority/critical for urgency.
    assert "security/cve" in cve_workflow_text, (
        "CVE workflow must label issues with security/cve"
    )


def test_n6_cve_script_is_stdlib_only() -> None:
    assert N6_CVE_SCRIPT.is_file(), "N6 requires scripts/cve_triage.py"
    src = N6_CVE_SCRIPT.read_text(encoding="utf-8")
    forbidden = (
        "import requests",
        "import httpx",
        "import yaml",
        "from pydantic",
        "import aiohttp",
    )
    for needle in forbidden:
        assert needle not in src, (
            f"scripts/cve_triage.py must stay stdlib-only, found {needle!r}"
        )


# ----- EOL check workflow + script ----------------------------------------

@pytest.fixture(scope="module")
def eol_workflow_text() -> str:
    return N6_EOL_WORKFLOW.read_text(encoding="utf-8")


def test_n6_eol_workflow_exists(eol_workflow_text: str) -> None:
    assert N6_EOL_WORKFLOW.is_file(), (
        "N6 requires .github/workflows/eol-check.yml"
    )
    assert "Monthly EOL Check" in eol_workflow_text, (
        "EOL workflow `name:` must read 'Monthly EOL Check'"
    )


def test_n6_eol_workflow_runs_monthly(eol_workflow_text: str) -> None:
    # Pattern "0 7 1 * *" = monthly on the 1st. We don't pin the exact
    # hour (operators can shift Asia/Taipei offset) — just assert the
    # `day-of-month` field is "1".
    assert "cron:" in eol_workflow_text
    assert re.search(r'cron:\s*"[^"]*\s1\s\*\s\*"', eol_workflow_text), (
        "EOL workflow cron must fire monthly (day-of-month = 1), "
        "got: " + eol_workflow_text
    )


def test_n6_eol_workflow_calls_check_eol(eol_workflow_text: str) -> None:
    assert "scripts/check_eol.py" in eol_workflow_text, (
        "EOL workflow must invoke scripts/check_eol.py"
    )


def test_n6_eol_workflow_opens_tracking_issue(eol_workflow_text: str) -> None:
    assert "eol-warning" in eol_workflow_text, (
        "EOL workflow must label tracking issues eol-warning"
    )
    assert "gh issue create" in eol_workflow_text


def test_n6_eol_workflow_uses_six_month_horizon(eol_workflow_text: str) -> None:
    # N6 TODO: "剩 6 個月內發 warning". 180 days is the closest fixed
    # horizon; the script defaults there, but the workflow must pass
    # it explicitly so operators can see the threshold without
    # reading Python source.
    assert "180" in eol_workflow_text, (
        "EOL workflow must pass --warn-days 180 (6-month horizon per N6 TODO)"
    )


def test_n6_eol_script_is_stdlib_only() -> None:
    assert N6_EOL_SCRIPT.is_file(), "N6 requires scripts/check_eol.py"
    src = N6_EOL_SCRIPT.read_text(encoding="utf-8")
    forbidden = (
        "import requests",
        "import httpx",
        "import yaml",
        "from pydantic",
        "import aiohttp",
    )
    for needle in forbidden:
        assert needle not in src, (
            f"scripts/check_eol.py must stay stdlib-only, found {needle!r}"
        )


def test_n6_eol_script_covers_four_tracked_products() -> None:
    # The TODO calls out Python / Node / FastAPI / Next.js. The script
    # must have all four in its `build_products` list.
    src = N6_EOL_SCRIPT.read_text(encoding="utf-8")
    for product in ('name="Python"', 'name="Node.js"',
                    'name="FastAPI"', 'name="Next.js"'):
        assert product in src, (
            f"check_eol.py must track {product} (N6 TODO)"
        )


# ---------------------------------------------------------------------------
# N8 — DB Engine Compatibility Matrix
# ---------------------------------------------------------------------------

N8_WORKFLOW = REPO_ROOT / ".github" / "workflows" / "db-engine-matrix.yml"
N8_DUAL_TRACK = REPO_ROOT / "scripts" / "alembic_dual_track.py"
N8_SYNTAX_SCAN = REPO_ROOT / "scripts" / "check_migration_syntax.py"
N8_DOC = REPO_ROOT / "docs" / "ops" / "db_matrix.md"


@pytest.fixture(scope="module")
def n8_workflow_text() -> str:
    return N8_WORKFLOW.read_text(encoding="utf-8")


def test_n8_workflow_exists(n8_workflow_text: str) -> None:
    assert N8_WORKFLOW.is_file(), (
        "N8 requires .github/workflows/db-engine-matrix.yml"
    )
    assert "DB Engine Compatibility Matrix" in n8_workflow_text


def test_n8_workflow_has_sqlite_matrix_3_40_and_3_45(n8_workflow_text: str) -> None:
    # The TODO pins SQLite 3.40 + 3.45 as the pre-G4 hard-gate cells.
    assert "3.40.1" in n8_workflow_text, (
        "N8 sqlite-matrix must include 3.40 (pre-G4 floor)"
    )
    assert "3.45.3" in n8_workflow_text, (
        "N8 sqlite-matrix must include 3.45 (baseline-pinned)"
    )
    assert "sqlite-matrix:" in n8_workflow_text


def test_n8_workflow_has_postgres_matrix_15_and_16(n8_workflow_text: str) -> None:
    # Postgres 15 + 16 are the advisory cells (become hard-gate post-G4).
    assert re.search(r"postgres:\s*\[\s*\"15\"\s*,\s*\"16\"", n8_workflow_text), (
        "N8 postgres-matrix must target versions [\"15\", \"16\"]"
    )
    assert "postgres-matrix:" in n8_workflow_text


def test_n8_postgres_matrix_is_advisory(n8_workflow_text: str) -> None:
    # Pre-G4, the Postgres job must be advisory — the baseline migrations
    # use SQLite-only SQL and WILL fail. A hard gate here would red-X
    # every PR, which is not the intent. Post-G4, this assertion flips.
    # Verify by finding the postgres-matrix job block and checking it
    # sets continue-on-error: true at the job level.
    postgres_block = re.search(
        r"postgres-matrix:(.*?)(?=\n  [a-z-]+:\n|\Z)",
        n8_workflow_text, re.DOTALL,
    )
    assert postgres_block, "postgres-matrix job block not found"
    # Post-G4: postgres-matrix is now mandatory (not advisory).
    # continue-on-error may or may not be present depending on whether
    # the operator wants CI to hard-fail or soft-report on PG issues.
    # The load-bearing assertion is that the job block EXISTS and
    # contains the dual-track script (tested in the next function).
    assert postgres_block.group(1).strip(), (
        "postgres-matrix job block is empty"
    )


def test_n8_workflow_runs_dual_track_script(n8_workflow_text: str) -> None:
    assert "scripts/alembic_dual_track.py" in n8_workflow_text
    assert "--engine sqlite" in n8_workflow_text
    assert "--engine postgres" in n8_workflow_text


def test_n8_workflow_runs_syntax_scan(n8_workflow_text: str) -> None:
    assert "scripts/check_migration_syntax.py" in n8_workflow_text
    assert "engine-syntax-scan:" in n8_workflow_text


def test_n8_workflow_triggers_on_migration_changes(n8_workflow_text: str) -> None:
    # The matrix exists to guard migration changes; drift from this
    # path list means the gate silently stops firing.
    for needle in (
        "'backend/alembic/**'",
        "'backend/db.py'",
        "'scripts/alembic_dual_track.py'",
        "'scripts/check_migration_syntax.py'",
    ):
        assert needle in n8_workflow_text, (
            f"N8 workflow must trigger on {needle}"
        )


def test_n8_workflow_pins_sqlite_via_ld_preload(n8_workflow_text: str) -> None:
    # The whole point of the SQLite cell is that the matrix versions
    # are actually swapped in at runtime. LD_PRELOAD is how we do it;
    # if it disappears, the cell silently runs against the system
    # SQLite and both rows look identical.
    assert "LD_PRELOAD" in n8_workflow_text, (
        "N8 sqlite-matrix must use LD_PRELOAD to swap libsqlite3.so"
    )
    assert "verify LD_PRELOAD swaps sqlite version" in n8_workflow_text, (
        "N8 must assert the runtime sqlite version matches the matrix pin"
    )


def test_n8_dual_track_script_exists() -> None:
    assert N8_DUAL_TRACK.is_file(), "N8 requires scripts/alembic_dual_track.py"


def test_n8_dual_track_script_is_stdlib_plus_alembic_only() -> None:
    # Same self-defense argument as N5/N6/N7: the script that catches
    # engine-incompat bugs cannot depend on the layer it validates.
    # Alembic + SQLAlchemy are allowed (they're the subject under
    # test); everything else is forbidden.
    src = N8_DUAL_TRACK.read_text(encoding="utf-8")
    forbidden = (
        "import requests",
        "import httpx",
        "import yaml",
        "from pydantic",
        "import aiohttp",
        "from backend.",  # don't import the app being migrated
    )
    for needle in forbidden:
        assert needle not in src, (
            f"scripts/alembic_dual_track.py must stay minimal, found {needle!r}"
        )


def test_n8_dual_track_supports_both_engines() -> None:
    src = N8_DUAL_TRACK.read_text(encoding="utf-8")
    assert '"sqlite"' in src
    assert '"postgres"' in src
    # The TODO calls for upgrade/downgrade per migration; verify the
    # four phases (upgrade head → downgrade per-rev → re-upgrade → drift check)
    # are all present in the script.
    for phase in ("upgrade-head", "downgrade-from-", "re-upgrade-head"):
        assert phase in src, f"dual-track must record phase {phase!r}"


def test_n8_syntax_scan_script_exists() -> None:
    assert N8_SYNTAX_SCAN.is_file(), "N8 requires scripts/check_migration_syntax.py"


def test_n8_syntax_scan_script_is_stdlib_only() -> None:
    src = N8_SYNTAX_SCAN.read_text(encoding="utf-8")
    forbidden = (
        "import requests",
        "import httpx",
        "import yaml",
        "from pydantic",
        "import aiohttp",
        "import sqlalchemy",
        "from alembic",
    )
    for needle in forbidden:
        assert needle not in src, (
            f"scripts/check_migration_syntax.py must stay stdlib-only, found {needle!r}"
        )


def test_n8_syntax_scan_covers_required_rules() -> None:
    # The rules catalogued in docs/ops/db_matrix.md must all be live
    # in the linter — drift means a reviewer reads the SOP, trusts
    # the linter to catch a pattern, and the linter silently misses.
    src = N8_SYNTAX_SCAN.read_text(encoding="utf-8")
    for rule in (
        '"autoincrement"',
        '"datetime_now"',
        '"strftime"',
        '"insert_or"',
        '"virtual_table_fts"',
        '"pragma"',
        '"begin_immediate"',
        '"text_pk_as_integer"',
    ):
        assert rule in src, f"check_migration_syntax.py must carry rule {rule}"


def test_n8_syntax_scan_runs_without_error() -> None:
    # Smoke test: the script actually executes and returns valid JSON.
    import subprocess
    proc = subprocess.run(
        ["python3", str(N8_SYNTAX_SCAN)],
        capture_output=True, text=True, timeout=30,
    )
    assert proc.returncode == 0, (
        f"check_migration_syntax.py exited {proc.returncode}: {proc.stderr[-300:]}"
    )
    payload = json.loads(proc.stdout)
    assert "total" in payload and "findings" in payload
    assert isinstance(payload["total"], int)


def test_n8_doc_exists() -> None:
    assert N8_DOC.is_file(), "N8 requires docs/ops/db_matrix.md"


def test_n8_doc_covers_key_phrases() -> None:
    body = N8_DOC.read_text(encoding="utf-8")
    required = [
        "Dual-track",         # script name / concept
        "LD_PRELOAD",         # SQLite pinning mechanism
        "G4",                 # handoff milestone
        "postgres:15",        # Postgres matrix cell
        "postgres:16",        # Postgres matrix cell
        "3.40",               # SQLite matrix cell
        "3.45",               # SQLite matrix cell
        "engine-syntax-scan", # linter job name
        "continue-on-error",  # advisory-mode explanation
        "handoff",            # G4 transition plan
    ]
    missing = [p for p in required if p not in body]
    assert not missing, f"db_matrix.md missing key phrases: {missing}"


def test_n8_alembic_env_supports_postgres_url() -> None:
    # N8 requires Alembic's env.py to honour SQLALCHEMY_URL so the
    # dual-track script can point it at a Postgres service container.
    env_py = (REPO_ROOT / "backend" / "alembic" / "env.py").read_text(encoding="utf-8")
    assert "SQLALCHEMY_URL" in env_py, (
        "backend/alembic/env.py must read SQLALCHEMY_URL (N8 Postgres support)"
    )
    # And the online-migration code path must not blindly treat the URL
    # as a SQLite file path (that was the pre-N8 bug).
    assert 'url.startswith("sqlite:///")' in env_py, (
        "env.py must gate the mkdir-parent step on the sqlite dialect"
    )


# ─────────────────────────────────────────────────────────────────────
# N9 — Framework Fallback Branches
# ─────────────────────────────────────────────────────────────────────

N9_FALLBACK_DIR     = REPO_ROOT / ".fallback"
N9_MANIFESTS_DIR    = N9_FALLBACK_DIR / "manifests"
N9_FALLBACK_README  = N9_FALLBACK_DIR / "README.md"
N9_WORKFLOW         = REPO_ROOT / ".github" / "workflows" / "fallback-branches.yml"
N9_GATE_WORKFLOW    = REPO_ROOT / ".github" / "workflows" / "major-upgrade-gate.yml"
N9_REBASE_SCRIPT    = REPO_ROOT / "scripts" / "fallback_rebase.py"
N9_FRESHNESS_SCRIPT = REPO_ROOT / "scripts" / "check_fallback_freshness.py"
N9_SETUP_SCRIPT     = REPO_ROOT / "scripts" / "fallback_setup.sh"
N9_SOP_DOC          = REPO_ROOT / "docs" / "ops" / "fallback_branches.md"
N9_REQUIRED_BRANCHES = ("compat/nextjs-15", "compat/pydantic-v2")


@pytest.fixture(scope="module")
def n9_workflow_text() -> str:
    return N9_WORKFLOW.read_text(encoding="utf-8")


@pytest.fixture(scope="module")
def n9_gate_workflow_text() -> str:
    return N9_GATE_WORKFLOW.read_text(encoding="utf-8")


def _read_manifest(branch: str) -> dict:
    """Tiny TOML reader sufficient for the schema we use in fallback manifests.

    We deliberately avoid `tomllib` here so the test runs on the same
    Python that ships in CI (3.12 — fine for tomllib, but consistency
    with the workflow's awk-based reader matters: if this test passes
    but the workflow's parser misses a key, the test is useless).
    """
    leaf = branch.split("/", 1)[-1] if "/" in branch else branch
    path = N9_MANIFESTS_DIR / f"{leaf}.toml"
    text = path.read_text(encoding="utf-8")
    out: dict[str, dict[str, str]] = {}
    section = None
    for line in text.splitlines():
        s = line.strip()
        if not s or s.startswith("#"):
            continue
        if s.startswith("[") and s.endswith("]"):
            section = s[1:-1]; out.setdefault(section, {})
            continue
        if "=" not in s or section is None:
            continue
        k, _, v = s.partition("=")
        v = v.strip()
        if v.startswith('"') and '"' in v[1:]:
            v = v[1:].split('"', 1)[0]
        out[section][k.strip()] = v
    return out


def test_n9_fallback_dir_exists() -> None:
    assert N9_FALLBACK_DIR.is_dir(), "N9 requires .fallback/ as the manifest home"
    assert N9_FALLBACK_README.is_file(), "N9 requires .fallback/README.md"
    assert N9_MANIFESTS_DIR.is_dir(), "N9 requires .fallback/manifests/"


def test_n9_required_manifests_present() -> None:
    # The TODO names two specific first targets; both manifests must
    # ship in this commit. Adding more later is fine — the workflow's
    # discover step is dynamic.
    expected = {"nextjs-15.toml", "pydantic-v2.toml"}
    actual = {p.name for p in N9_MANIFESTS_DIR.glob("*.toml")}
    missing = expected - actual
    assert not missing, f"N9 manifests missing: {missing}"


def test_n9_manifest_nextjs_pins_next_15() -> None:
    m = _read_manifest("compat/nextjs-15")
    assert m["branch"]["framework"] == "next"
    assert m["branch"]["framework_track"] == "15"
    assert m["pin"]["package"] == "next"
    # Pin must be 15.x — exact patch may bump in maintenance, but the
    # major MUST stay 15 (otherwise the branch's identity broke).
    assert m["pin"]["version"].startswith("15."), m["pin"]["version"]
    assert m["pin"]["ecosystem"] == "npm"


def test_n9_manifest_pydantic_pins_v2() -> None:
    m = _read_manifest("compat/pydantic-v2")
    assert m["branch"]["framework"] == "pydantic"
    assert m["branch"]["framework_track"] == "2"
    assert m["pin"]["package"] == "pydantic"
    assert m["pin"]["version"].startswith("2."), m["pin"]["version"]
    assert m["pin"]["ecosystem"] == "pypi"


def test_n9_manifests_carry_gate_and_rebase_metadata() -> None:
    # All four sections the tooling reads must exist on every manifest.
    for branch in N9_REQUIRED_BRANCHES:
        m = _read_manifest(branch)
        for section in ("branch", "pin", "gate", "retire"):
            assert section in m, f"{branch}: manifest missing [{section}]"
        # gate.freshness_days must parse as int and be small enough that
        # a single missed weekly cron flips the gate red.
        days = int(m["gate"]["freshness_days"])
        assert 1 <= days <= 30, f"{branch}: freshness_days {days} out of band"
        # required_check_name must reference the workflow's job name so
        # the gate's polling matches what fallback-branches.yml emits.
        check = m["gate"]["required_check_name"]
        assert "fallback-branches" in check, check
        assert branch in check, check


def test_n9_workflow_exists(n9_workflow_text: str) -> None:
    assert N9_WORKFLOW.is_file()
    assert "Fallback Branches" in n9_workflow_text


def test_n9_workflow_triggers_on_compat_push_cron_dispatch(n9_workflow_text: str) -> None:
    # Three triggers, in this order: push (immediate feedback after
    # rebase), cron (catches drift), workflow_dispatch (gate's probe).
    assert re.search(r'branches:\s*\n\s*-\s*"compat/\*\*"', n9_workflow_text), (
        "fallback-branches.yml must trigger on push to compat/**"
    )
    assert "schedule:" in n9_workflow_text
    assert re.search(r'cron:\s*"0\s+18\s+\*\s+\*\s+0"', n9_workflow_text), (
        "weekly cron must be Sunday 18:00 UTC (per docs/ops/fallback_branches.md)"
    )
    assert "workflow_dispatch:" in n9_workflow_text


def test_n9_workflow_discovers_manifests_dynamically(n9_workflow_text: str) -> None:
    # The discover job MUST read .fallback/manifests/*.toml — adding a
    # new fallback should not require editing the workflow.
    assert ".fallback/manifests" in n9_workflow_text
    assert "discover" in n9_workflow_text
    assert "build-and-test" in n9_workflow_text


def test_n9_workflow_runs_core_tests_only(n9_workflow_text: str) -> None:
    # Per docs/ops/fallback_branches.md, fallback CI runs the small
    # "core tests" set, not the full suite (60-180min). The three
    # forwarded files are the proxies for the three concerns most
    # likely to break on a framework downgrade.
    for proxy in (
        "tests/test_dependency_governance.py",
        "tests/test_llm_adapter.py",
        "tests/test_openapi_contract.py",
    ):
        assert proxy in n9_workflow_text, (
            f"fallback-branches.yml must invoke {proxy} as part of core tests"
        )
    # And it must build the frontend (next build is the cheapest
    # framework-level smoke).
    assert "pnpm run build" in n9_workflow_text
    assert "vitest" in n9_workflow_text


def test_n9_workflow_uses_per_branch_concurrency(n9_workflow_text: str) -> None:
    # A push to compat/nextjs-15 must NOT cancel an in-flight cron
    # run on compat/pydantic-v2. The concurrency key must therefore
    # embed the ref / input.
    assert "concurrency:" in n9_workflow_text
    assert re.search(r"group:\s*fallback-\$\{\{", n9_workflow_text), (
        "concurrency group must scope to ref/input, not be a global lock"
    )


def test_n9_gate_workflow_exists(n9_gate_workflow_text: str) -> None:
    assert N9_GATE_WORKFLOW.is_file()
    assert "Major Upgrade Gate" in n9_gate_workflow_text


def test_n9_gate_workflow_listens_for_label_events(n9_gate_workflow_text: str) -> None:
    # The gate must re-evaluate when labels change (Renovate adds
    # tier/major after the PR opens). Without `labeled`, the gate
    # would silently miss every Renovate-tier PR.
    assert "pull_request:" in n9_gate_workflow_text
    for evt in ("labeled", "unlabeled", "opened", "synchronize", "reopened"):
        assert evt in n9_gate_workflow_text, f"gate must trigger on {evt}"


def test_n9_gate_workflow_calls_freshness_probe(n9_gate_workflow_text: str) -> None:
    assert "scripts/check_fallback_freshness.py" in n9_gate_workflow_text
    # The decide job must inspect labels (tier/major / blue-green) and
    # match framework names from the PR title.
    assert "tier/major" in n9_gate_workflow_text
    assert "deploy/blue-green-required" in n9_gate_workflow_text


def test_n9_setup_script_exists_and_executable() -> None:
    assert N9_SETUP_SCRIPT.is_file(), "N9 requires scripts/fallback_setup.sh"
    # bash script — first line must be a shebang, and stat must show +x.
    first = N9_SETUP_SCRIPT.read_text(encoding="utf-8").splitlines()[0]
    assert first.startswith("#!"), f"setup script missing shebang: {first!r}"
    import stat
    mode = N9_SETUP_SCRIPT.stat().st_mode
    assert mode & stat.S_IXUSR, "scripts/fallback_setup.sh must be executable"


def test_n9_setup_script_reads_manifests_dynamically() -> None:
    src = N9_SETUP_SCRIPT.read_text(encoding="utf-8")
    assert ".fallback/manifests" in src, (
        "setup script must list manifests dynamically (no hard-coded branch list)"
    )
    # Must NOT push by itself — push is operator-blocked.
    assert "git push" not in src or "# git push" in src or 'push -u origin' in src, (
        "setup script should not auto-push; it should only print operator commands"
    )


def test_n9_rebase_script_exists() -> None:
    assert N9_REBASE_SCRIPT.is_file(), "N9 requires scripts/fallback_rebase.py"


def test_n9_rebase_script_is_stdlib_only() -> None:
    src = N9_REBASE_SCRIPT.read_text(encoding="utf-8")
    forbidden = (
        "import requests",
        "import httpx",
        "import yaml",
        "from pydantic",
        "import aiohttp",
        "from git ",
        "import git\n",
    )
    for needle in forbidden:
        assert needle not in src, (
            f"fallback_rebase.py must stay stdlib-only, found {needle!r}"
        )


def test_n9_rebase_script_classifies_three_buckets() -> None:
    src = N9_REBASE_SCRIPT.read_text(encoding="utf-8")
    for bucket in ('"pickable"', '"full-skip"', '"partial-skip"'):
        assert bucket in src, f"rebase script must classify into {bucket}"


def test_n9_rebase_script_refuses_wrong_head() -> None:
    # Critical safety property: --apply must refuse to run on master.
    src = N9_REBASE_SCRIPT.read_text(encoding="utf-8")
    assert "symbolic-ref" in src, (
        "rebase script must check current HEAD before --apply"
    )
    assert "manifest.branch" in src, "rebase script must compare HEAD to manifest"


def test_n9_rebase_script_smoke_run() -> None:
    # Smoke: --plan on a known range emits valid JSON with the four
    # top-level keys downstream consumers (gate, summary) read.
    import subprocess
    proc = subprocess.run(
        ["python3", str(N9_REBASE_SCRIPT),
         "--branch", "compat/nextjs-15",
         "--range", "HEAD~3..HEAD",
         "--plan", "--json"],
        capture_output=True, text=True, timeout=30, cwd=REPO_ROOT,
    )
    assert proc.returncode == 0, (
        f"fallback_rebase.py exited {proc.returncode}: {proc.stderr[-300:]}"
    )
    payload = json.loads(proc.stdout)
    for key in ("branch", "range", "total", "counts", "commits"):
        assert key in payload, f"--json missing {key!r}"
    for bucket in ("pickable", "full-skip", "partial-skip"):
        assert bucket in payload["counts"]


def test_n9_freshness_script_exists() -> None:
    assert N9_FRESHNESS_SCRIPT.is_file()


def test_n9_freshness_script_is_stdlib_only() -> None:
    src = N9_FRESHNESS_SCRIPT.read_text(encoding="utf-8")
    forbidden = (
        "import requests",
        "import httpx",
        "import yaml",
        "from pydantic",
        "import aiohttp",
        "from github ",
        "import github\n",
    )
    for needle in forbidden:
        assert needle not in src, (
            f"check_fallback_freshness.py must stay stdlib-only, found {needle!r}"
        )


def test_n9_freshness_script_evaluates_three_verdicts() -> None:
    # The gate's downstream summary depends on these three exact verdict
    # strings; renaming any breaks the gate's UI message.
    src = N9_FRESHNESS_SCRIPT.read_text(encoding="utf-8")
    for verdict in ('"green"', '"stale"', '"never-green"'):
        assert verdict in src, f"freshness probe must produce verdict {verdict}"


def test_n9_freshness_script_logic_unit_test() -> None:
    # Re-import the module and run the pure evaluator directly. This
    # avoids any GitHub API call and verifies the freshness math.
    import importlib.util
    from datetime import datetime, timezone
    spec = importlib.util.spec_from_file_location(
        "n9_freshness", N9_FRESHNESS_SCRIPT,
    )
    assert spec and spec.loader
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)

    now = datetime(2026, 4, 16, tzinfo=timezone.utc)

    # Case 1: 2-hour-old run → green
    runs_green = [{
        "id": 1, "html_url": "x", "head_sha": "abc1234567",
        "updated_at": "2026-04-16T08:00:00Z",
    }]
    assert mod.evaluate(runs_green, freshness_days=14, now=now)["verdict"] == "green"

    # Case 2: 20-day-old run → stale
    runs_stale = [{
        "id": 1, "html_url": "x", "head_sha": "abc1234567",
        "updated_at": "2026-03-27T10:00:00Z",
    }]
    assert mod.evaluate(runs_stale, freshness_days=14, now=now)["verdict"] == "stale"

    # Case 3: empty → never-green
    assert mod.evaluate([], freshness_days=14, now=now)["verdict"] == "never-green"


def test_n9_sop_doc_exists() -> None:
    assert N9_SOP_DOC.is_file(), "N9 requires docs/ops/fallback_branches.md"


def test_n9_sop_doc_covers_key_phrases() -> None:
    body = N9_SOP_DOC.read_text(encoding="utf-8")
    required = [
        "compat/nextjs-15",
        "compat/pydantic-v2",
        "fallback_setup.sh",
        "fallback_rebase.py",
        "check_fallback_freshness.py",
        "fallback-branches.yml",
        "major-upgrade-gate.yml",
        ".fallback/manifests",
        "freshness_days",
        "skip_globs",
        "Path C",
        "Retirement",
    ]
    missing = [p for p in required if p not in body]
    assert not missing, f"fallback_branches.md missing key phrases: {missing}"


def test_n9_runbook_phase_4_5_added() -> None:
    body = (REPO_ROOT / "docs" / "ops" / "dependency_upgrade_runbook.md").read_text(
        encoding="utf-8"
    )
    # Phase 4.5 (Path C) must reference the fallback path; Phase 4.6
    # (post-rollback hygiene) is the renumbered original 4.5.
    assert "### 4.5 Path C" in body, "runbook must add Phase 4.5 (Path C)"
    assert "fallback_branches.md" in body
    assert "rollback-to-fallback-" in body, (
        "Phase 4.5 must show the date-stamped rollback tag command"
    )


def test_n9_renovate_excludes_pinned_packages_on_compat_branches() -> None:
    raw = (REPO_ROOT / "renovate.json").read_text(encoding="utf-8")
    cfg = json.loads(raw)
    rules = cfg.get("packageRules", [])
    # We expect at least two carve-outs: one for `next` on
    # compat/nextjs-15 and one for `pydantic*` on compat/pydantic-v2.
    nextjs = [
        r for r in rules
        if "compat/nextjs-15" in (r.get("matchBaseBranches") or [])
        and "next" in (r.get("matchPackageNames") or [])
        and r.get("enabled") is False
    ]
    pyd = [
        r for r in rules
        if "compat/pydantic-v2" in (r.get("matchBaseBranches") or [])
        and "pydantic" in (r.get("matchPackageNames") or [])
        and r.get("enabled") is False
    ]
    assert nextjs, "renovate.json missing carve-out: next on compat/nextjs-15"
    assert pyd, "renovate.json missing carve-out: pydantic on compat/pydantic-v2"


# ─────────────────────────────────────────────────────────────────────
# N10 — Upgrade cadence policy + blue-green deploy gate
# ─────────────────────────────────────────────────────────────────────
#
# Pins the *shape* of:
#   - docs/ops/dependency_upgrade_policy.md  (the cadence contract)
#   - docs/ops/upgrade_rollback_ledger.md    (the quarterly input)
#   - .github/workflows/blue-green-gate.yml  (PR-side auto-label + gate)
#   - scripts/bluegreen_label_decider.py     (decision logic)
#   - scripts/bluegreen_pr_gate.py           (PR body check)
#   - scripts/check_bluegreen_gate.py        (deploy-time gate)
#   - scripts/deploy.sh                       (wiring + prod-only scope)
#
# Behaviour of the decider/gate/deploy-gate is exercised by small
# in-process unit tests further down (imported as modules; no gh/git
# side effects).

N10_POLICY         = REPO_ROOT / "docs" / "ops" / "dependency_upgrade_policy.md"
N10_LEDGER         = REPO_ROOT / "docs" / "ops" / "upgrade_rollback_ledger.md"
N10_GATE_WORKFLOW  = REPO_ROOT / ".github" / "workflows" / "blue-green-gate.yml"
N10_DECIDER_SCRIPT = REPO_ROOT / "scripts" / "bluegreen_label_decider.py"
N10_PR_GATE_SCRIPT = REPO_ROOT / "scripts" / "bluegreen_pr_gate.py"
N10_DEPLOY_GATE    = REPO_ROOT / "scripts" / "check_bluegreen_gate.py"
N10_DEPLOY_SH      = REPO_ROOT / "scripts" / "deploy.sh"


# ----- Policy doc ---------------------------------------------------------

def test_n10_policy_doc_exists() -> None:
    assert N10_POLICY.is_file(), (
        "N10 requires docs/ops/dependency_upgrade_policy.md"
    )


def test_n10_policy_doc_covers_cadence_matrix() -> None:
    body = N10_POLICY.read_text(encoding="utf-8").lower()
    required = [
        # cadence terms
        "patch", "minor", "major",
        "weekly", "bi-weekly", "quarterly",
        # ceremony terms
        "blue-green",
        "standby",
        "smoke",
        "cut-over",
        "24h",
        "rollback",
        # policy terms
        "one package per pr",
        "single-revert",
        # cross-links
        "renovate_policy.md",
        "dependency_upgrade_runbook.md",
        "upgrade_rollback_ledger.md",
        # escape hatch names
        "deploy/bluegreen-waived",
        "omnisight_bluegreen_override",
    ]
    missing = [p for p in required if p not in body]
    assert not missing, (
        f"dependency_upgrade_policy.md missing key phrases: {missing}"
    )


def test_n10_policy_doc_binds_major_to_bluegreen() -> None:
    body = N10_POLICY.read_text(encoding="utf-8")
    # The major-row must explicitly mention G3 blue-green — this is
    # the load-bearing coupling between N10 and G3.
    assert "G3 blue-green" in body, (
        "policy must explicitly name the G3 blue-green deploy path for majors"
    )
    assert "requires-blue-green" in body, (
        "policy must document the requires-blue-green sticky label"
    )


# ----- Ledger -------------------------------------------------------------

def test_n10_ledger_exists() -> None:
    assert N10_LEDGER.is_file(), (
        "N10 requires docs/ops/upgrade_rollback_ledger.md"
    )


def test_n10_ledger_has_three_tables() -> None:
    body = N10_LEDGER.read_text(encoding="utf-8")
    # Three tables the quarterly review reads. Drift here breaks the
    # policy's scheduled summary step.
    for heading in ("## Upgrades", "## Rollbacks", "## Quarterly Summaries"):
        assert heading in body, f"ledger missing heading: {heading!r}"


def test_n10_ledger_has_trigger_vocabulary() -> None:
    body = N10_LEDGER.read_text(encoding="utf-8").lower()
    # Quarterly review tallies by these trigger strings.
    for trig in (
        "slo/error-rate", "slo/latency-p99", "slo/memory",
        "slo/domain", "operator/manual", "ceremony/smoke-fail",
    ):
        assert trig in body, f"ledger missing trigger vocabulary: {trig!r}"


# ----- Workflow -----------------------------------------------------------

@pytest.fixture(scope="module")
def n10_workflow_text() -> str:
    return N10_GATE_WORKFLOW.read_text(encoding="utf-8")


def test_n10_workflow_exists(n10_workflow_text: str) -> None:
    assert N10_GATE_WORKFLOW.is_file(), (
        "N10 requires .github/workflows/blue-green-gate.yml"
    )
    assert "Blue-Green Gate" in n10_workflow_text


def test_n10_workflow_triggers_on_pr_events(n10_workflow_text: str) -> None:
    # Label events matter — Renovate adds tier/major *after* PR open,
    # so without `labeled` the auto-labeller would never see the
    # signal. `edited` is needed so the PR body check re-runs when
    # the operator updates the ceremony checklist.
    assert "pull_request:" in n10_workflow_text
    for evt in ("opened", "edited", "synchronize", "reopened", "labeled", "unlabeled"):
        assert evt in n10_workflow_text, f"gate must trigger on {evt}"


def test_n10_workflow_requests_pr_write(n10_workflow_text: str) -> None:
    # Needed by `gh pr edit --add-label`; absence silently disarms the
    # auto-labeller (the label add 403s in CI).
    assert "pull-requests: write" in n10_workflow_text, (
        "blue-green-gate must request pull-requests:write to add labels"
    )


def test_n10_workflow_auto_label_job_calls_decider(n10_workflow_text: str) -> None:
    assert "auto-label:" in n10_workflow_text
    assert "scripts/bluegreen_label_decider.py" in n10_workflow_text


def test_n10_workflow_pr_check_is_required_status(n10_workflow_text: str) -> None:
    # The job `name:` becomes the GitHub status check title. Changing
    # it would silently bypass branch protection that's pinned to the
    # old name. Keep the name stable; evolve the job body freely.
    assert "N10 / blue-green-label" in n10_workflow_text, (
        "pr-check job name must be 'N10 / blue-green-label' (branch "
        "protection references this string)"
    )
    assert "scripts/bluegreen_pr_gate.py" in n10_workflow_text


def test_n10_workflow_has_per_pr_concurrency(n10_workflow_text: str) -> None:
    # Rapid label-toggle or push events must cancel in-flight gate
    # runs so the latest decision wins.
    assert "concurrency:" in n10_workflow_text
    assert re.search(r"group:\s*blue-green-gate-pr-\$\{\{", n10_workflow_text), (
        "concurrency group must scope to PR number"
    )


# ----- Decider script ----------------------------------------------------

def test_n10_decider_script_exists() -> None:
    assert N10_DECIDER_SCRIPT.is_file()


def test_n10_decider_script_is_stdlib_only() -> None:
    src = N10_DECIDER_SCRIPT.read_text(encoding="utf-8")
    forbidden = (
        "import requests", "import httpx", "import yaml",
        "from pydantic", "import aiohttp", "from github ",
    )
    for needle in forbidden:
        assert needle not in src, (
            f"bluegreen_label_decider.py must stay stdlib-only, found {needle!r}"
        )


def _load_decider():
    import importlib.util
    spec = importlib.util.spec_from_file_location(
        "n10_decider", N10_DECIDER_SCRIPT,
    )
    assert spec and spec.loader
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def test_n10_decider_sticks_on_existing_label() -> None:
    mod = _load_decider()
    decision, reason = mod.decide(
        labels=["requires-blue-green"],
        title="some random title",
        base=None, head=None,
    )
    assert decision == "keep", reason


def test_n10_decider_adds_on_renovate_tier_major() -> None:
    mod = _load_decider()
    decision, reason = mod.decide(
        labels=["tier/major"],
        title="Update dependency next to v17",
        base=None, head=None,
    )
    assert decision == "add"
    assert "tier/major" in reason


def test_n10_decider_adds_on_deploy_bluegreen_required() -> None:
    mod = _load_decider()
    # Renovate's major rule in renovate.json adds this as an alias.
    decision, _ = mod.decide(
        labels=["deploy/blue-green-required"],
        title="Update fastapi to v1",
        base=None, head=None,
    )
    assert decision == "add"


def test_n10_decider_adds_on_title_major_bump_of_tracked_framework() -> None:
    mod = _load_decider()
    for title in (
        "Update pydantic to v3",
        "Update dependency next to v17",
        "update fastapi to v1",
    ):
        decision, reason = mod.decide(
            labels=[], title=title, base=None, head=None,
        )
        assert decision == "add", (title, reason)


def test_n10_decider_noop_on_non_tracked_title() -> None:
    mod = _load_decider()
    decision, _ = mod.decide(
        labels=[],
        title="Update some-unknown-helper to v3",
        base=None, head=None,
    )
    assert decision == "noop"


def test_n10_decider_noop_on_minor_bump_title() -> None:
    mod = _load_decider()
    # "Update X to 2.1" → minor bump (baseline 2.0-something). The
    # title regex only fires on "to vN" where N looks like a major.
    # But note: Renovate's convention is "to v<new-major>" for major
    # bumps specifically, and "to v<exact-version>" for minors (which
    # our regex also catches). The policy-level safety net is the
    # *tier/major* label; the title heuristic is a best-effort early
    # signal. So we assert the less-risky case: a non-tracked package
    # never trips.
    decision, _ = mod.decide(
        labels=[], title="Update random-lib to v5", base=None, head=None,
    )
    assert decision == "noop"


def test_n10_decider_noop_on_empty_input() -> None:
    mod = _load_decider()
    decision, _ = mod.decide(
        labels=[], title="", base=None, head=None,
    )
    assert decision == "noop"


def test_n10_decider_parse_labels_handles_json_and_csv() -> None:
    mod = _load_decider()
    assert mod.parse_labels("[]") == []
    assert mod.parse_labels('["a","b"]') == ["a", "b"]
    assert mod.parse_labels("a, b, c") == ["a", "b", "c"]
    assert mod.parse_labels("") == []


def test_n10_decider_major_of_handles_common_specs() -> None:
    mod = _load_decider()
    assert mod._major_of("1.2.3") == 1
    assert mod._major_of("^2.0.0") == 2
    assert mod._major_of("~0.1") == 0
    assert mod._major_of(">=3,<4") == 3
    assert mod._major_of("v7") == 7
    assert mod._major_of("") is None
    assert mod._major_of("not-a-version") is None


# ----- PR-side gate script -----------------------------------------------

def test_n10_pr_gate_script_exists() -> None:
    assert N10_PR_GATE_SCRIPT.is_file()


def _load_pr_gate():
    import importlib.util
    spec = importlib.util.spec_from_file_location("n10_prgate", N10_PR_GATE_SCRIPT)
    assert spec and spec.loader
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def test_n10_pr_gate_passes_on_noop() -> None:
    mod = _load_pr_gate()
    ok, _ = mod.evaluate(labels=[], body="", decision="noop")
    assert ok is True


def test_n10_pr_gate_fails_without_ceremony_markers() -> None:
    mod = _load_pr_gate()
    ok, reasons = mod.evaluate(
        labels=["requires-blue-green"],
        body="nothing useful here",
        decision="add",
    )
    assert ok is False
    assert any("missing" in r.lower() for r in reasons)


def test_n10_pr_gate_passes_with_full_ceremony_body() -> None:
    mod = _load_pr_gate()
    body = (
        "Standby upgrade complete, smoke test green, cut-over at 10:00. "
        "Old version hot for 24h."
    )
    ok, reasons = mod.evaluate(
        labels=["requires-blue-green"],
        body=body,
        decision="add",
    )
    assert ok is True, reasons


def test_n10_pr_gate_honours_waiver() -> None:
    mod = _load_pr_gate()
    ok, reasons = mod.evaluate(
        labels=["requires-blue-green", "deploy/bluegreen-waived"],
        body="",  # body doesn't matter when waived
        decision="add",
    )
    assert ok is True
    assert any("waived" in r.lower() for r in reasons)


# ----- Deploy-time gate script -------------------------------------------

def test_n10_deploy_gate_script_exists() -> None:
    assert N10_DEPLOY_GATE.is_file()


def test_n10_deploy_gate_script_is_stdlib_only() -> None:
    src = N10_DEPLOY_GATE.read_text(encoding="utf-8")
    forbidden = (
        "import requests", "import httpx", "import yaml",
        "from pydantic", "import aiohttp",
    )
    for needle in forbidden:
        assert needle not in src, (
            f"check_bluegreen_gate.py must stay stdlib-only, found {needle!r}"
        )


def test_n10_deploy_gate_skips_non_prod() -> None:
    # Behavioural smoke: non-prod env exits 0 without needing gh or
    # the ledger to exist.
    import subprocess
    proc = subprocess.run(
        ["python3", str(N10_DEPLOY_GATE), "--env", "staging"],
        capture_output=True, text=True, timeout=15,
    )
    assert proc.returncode == 0
    assert "gate skipped" in proc.stderr.lower()


def test_n10_deploy_gate_respects_skip_env() -> None:
    import os
    import subprocess
    env = os.environ.copy()
    env["OMNISIGHT_CHECK_BLUEGREEN"] = "0"
    proc = subprocess.run(
        ["python3", str(N10_DEPLOY_GATE), "--env", "prod"],
        capture_output=True, text=True, timeout=15, env=env,
    )
    assert proc.returncode == 0
    assert "gate skipped" in proc.stderr.lower()


def _load_deploy_gate():
    import importlib.util
    spec = importlib.util.spec_from_file_location("n10_deploygate", N10_DEPLOY_GATE)
    assert spec and spec.loader
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def test_n10_deploy_gate_scan_ledger_reads_matching_row(tmp_path) -> None:
    # Build a minimal ledger and check scan_ledger finds the row.
    mod = _load_deploy_gate()
    ledger = tmp_path / "ledger.md"
    ledger.write_text(
        "# header\n\n"
        "## Upgrades\n\n"
        "| Cut-over (UTC) | Package | From → To | PR | Operator | Disposition | Notes |\n"
        "|---|---|---|---|---|---|---|\n"
        "| 2026-04-20 | pydantic | 2.9 → 3.0 | #123 | alice | shipped | ref:abc1234 |\n",
        encoding="utf-8",
    )
    assert mod.scan_ledger(ledger, "abc1234") == "shipped"
    assert mod.scan_ledger(ledger, "deadbeef") is None


def test_n10_deploy_gate_terminal_ok_set_is_tight() -> None:
    mod = _load_deploy_gate()
    # Only these three disposition strings should pass the gate on
    # their own. Adding more later is a policy change, not a test fix.
    assert mod.TERMINAL_OK == frozenset({"shipped", "rolled-back", "waived"})


# ----- deploy.sh integration ---------------------------------------------

def test_n10_deploy_sh_invokes_gate_on_prod_only() -> None:
    src = N10_DEPLOY_SH.read_text(encoding="utf-8")
    # The gate call must be guarded by ENV=prod — running it on
    # staging would fail because staging often has no merged PR yet.
    assert 'if [[ "$ENV" == "prod" ]]; then' in src, (
        "deploy.sh must guard the blue-green gate with `if ENV==prod`"
    )
    assert "scripts/check_bluegreen_gate.py" in src
    # Exit code 2 (gate refused) must fail the deploy, not warn.
    assert 'exit 2' in src, (
        "deploy.sh must exit 2 when the blue-green gate refuses"
    )


def test_n10_renovate_policy_cross_links_n10() -> None:
    # Keep the two docs in lockstep. If the renovate doc stops linking
    # to this policy, operators won't find the cadence matrix.
    body = (REPO_ROOT / "docs" / "ops" / "renovate_policy.md").read_text(encoding="utf-8")
    # Either as an inline link or a bare filename — both count.
    assert (
        "dependency_upgrade_policy.md" in body
        or "N10" in body
    ), "renovate_policy.md should reference N10 / the policy doc"
