"""W14.10 — alembic 0059 ``web_sandbox_instances`` migration contract.

Locks the load-bearing properties of the W14.10 table-add:

1.  **Structural** — revision ``0059`` chains onto ``0057`` (the
    AS.2.2 ``oauth_tokens`` row is the latest leaf in the auth/user
    chain; appending here keeps that lineage stable and leaves the
    AB-track chain ``0058 → 0181 → 0183 / 0184 → 0185`` untouched);
    the PG branch uses ``DOUBLE PRECISION`` + ``BIGINT GENERATED BY
    DEFAULT AS IDENTITY``; the SQLite branch uses ``REAL`` +
    ``INTEGER PRIMARY KEY AUTOINCREMENT`` and is ``IF NOT EXISTS``-
    guarded for idempotency.

2.  **Functional (SQLite)** — run ``upgrade()`` against an empty DB,
    then assert:
      * the ``web_sandbox_instances`` table exists,
      * every column the W14.10 row spec enumerates is present
        (``sandbox_id`` / ``workspace_id`` / ``started_at`` /
        ``ingress_url`` / ``status`` / ``last_request_at`` /
        ``killed_at`` / ``killed_reason``) plus the bookkeeping
        triplet (``created_at`` / ``updated_at`` / ``version``)
        and the ``id`` IDENTITY,
      * the partial UNIQUE on ``workspace_id`` WHERE status NOT IN
        ('stopped','failed') enforces the cross-worker invariant
        ("at most one live sidecar per workspace") — a second live
        INSERT for the same workspace_id must raise,
      * the same partial UNIQUE permits a fresh live row alongside
        a *terminal* row for the same workspace_id (audit-history
        pattern),
      * the ``status`` CHECK rejects an unknown status string and
        accepts every :class:`backend.web_sandbox.WebSandboxStatus`
        value verbatim,
      * the secondary ``idx_web_sandbox_instances_idle`` and
        ``idx_web_sandbox_instances_sandbox`` indexes were created
        and shape the W14.5 idle reaper / W14.3 ingress lookups.

3.  **Idempotency** — running ``upgrade()`` twice is a no-op:
    ``CREATE TABLE IF NOT EXISTS`` + ``CREATE INDEX IF NOT EXISTS``
    short-circuit on the second pass.

4.  **PG dialect branch** — capture SQL via a stub bind, verify the
    CREATE TABLE uses ``DOUBLE PRECISION`` (not ``REAL``) +
    ``BIGINT GENERATED BY DEFAULT AS IDENTITY`` (not
    ``AUTOINCREMENT``).  The PG-specific CHECK / partial UNIQUE
    syntax matches what the asyncpg + psycopg2 baseline accepts.

5.  **Cross-module drift guard** — the ``status`` CHECK clause in
    the migration source MUST byte-equal the sorted list of
    :class:`backend.web_sandbox.WebSandboxStatus` ``.value`` strings.
    Adding a new status must touch both the enum and this CHECK in
    the same PR.

6.  **Migrator coverage** — belt+braces the broader
    ``test_migrator_schema_coverage`` drift gate by pinning the
    expected entry name + INTEGER IDENTITY membership:
    ``web_sandbox_instances`` MUST be in ``TABLES_IN_ORDER`` AND in
    ``TABLES_WITH_IDENTITY_ID`` (since the PK is INTEGER IDENTITY,
    the sequence must restart after replay).

The schema half of the W14.10 contract; the launcher half (swap
:class:`backend.web_sandbox.WebSandboxManager` from in-memory cache
to PG-backed reads) lands in a separate row.
"""
from __future__ import annotations

import importlib.util
import sqlite3
import sys
from pathlib import Path

import pytest


BACKEND_ROOT = Path(__file__).resolve().parents[1]
MIGRATION_0059 = (
    BACKEND_ROOT / "alembic" / "versions" / "0059_web_sandbox_instances.py"
)


def _load_module(path: Path, name: str):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)  # type: ignore[arg-type]
    sys.modules[name] = module
    spec.loader.exec_module(module)  # type: ignore[union-attr]
    return module


@pytest.fixture(scope="module")
def m0059():
    return _load_module(MIGRATION_0059, "_alembic_test_0059")


# ─── Group 1: structural guards ───────────────────────────────────────────


class TestMigrationFileStructure:
    @pytest.fixture(scope="class")
    def source(self) -> str:
        return MIGRATION_0059.read_text()

    def test_revision_id_is_0059(self, source: str) -> None:
        assert 'revision = "0059"' in source

    def test_down_revision_is_0057(self, source: str) -> None:
        # 0059 chains AFTER 0057 (the AS.2.2 ``oauth_tokens`` table
        # is the latest leaf in the auth/user chain) — appending
        # here keeps the existing 0058/0057 chain stable and lets
        # dev DBs already at 0057 pick up the new table via a normal
        # upgrade-head pass.
        assert 'down_revision = "0057"' in source

    def test_pg_branch_uses_double_precision(self, m0059) -> None:
        # epoch-seconds columns use DOUBLE PRECISION on PG to
        # round-trip ``time.time()`` losslessly; same convention as
        # billing_usage_events / oauth_tokens / sessions.
        assert "DOUBLE PRECISION" in m0059._PG_CREATE_TABLE
        # Sanity: no naked ``REAL`` on the PG path (REAL is the SQLite
        # affinity; on PG it would silently be float4).
        assert " REAL " not in m0059._PG_CREATE_TABLE

    def test_pg_branch_uses_bigint_identity(self, m0059) -> None:
        # Phase-3 G4 PG idiom for INTEGER PK + IDENTITY.  Mirrors the
        # billing_usage_events row's PK shape so the migrator's
        # TABLES_WITH_IDENTITY_ID sequence-restart logic applies.
        assert (
            "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
            in m0059._PG_CREATE_TABLE
        )
        assert "AUTOINCREMENT" not in m0059._PG_CREATE_TABLE

    def test_pg_branch_idempotent(self, m0059) -> None:
        assert (
            "CREATE TABLE IF NOT EXISTS web_sandbox_instances"
            in m0059._PG_CREATE_TABLE
        )
        assert "IF NOT EXISTS" in m0059._PG_INDEX_LIVE_WORKSPACE
        assert "IF NOT EXISTS" in m0059._PG_INDEX_IDLE
        assert "IF NOT EXISTS" in m0059._PG_INDEX_SANDBOX

    def test_pg_partial_unique_uses_status_filter(self, m0059) -> None:
        # The cross-worker invariant lives in the partial UNIQUE
        # predicate.  Terminal rows (stopped / failed) are exempt
        # so the audit history can accumulate.
        assert (
            "WHERE status NOT IN ('stopped', 'failed')"
            in m0059._PG_INDEX_LIVE_WORKSPACE
        )

    def test_sqlite_branch_uses_real(self, m0059) -> None:
        # SQLite has no DOUBLE PRECISION; REAL is the parallel
        # affinity and round-trips ``time.time()`` cleanly.
        assert " REAL" in m0059._SQLITE_CREATE_TABLE
        assert "DOUBLE PRECISION" not in m0059._SQLITE_CREATE_TABLE

    def test_sqlite_branch_uses_autoincrement(self, m0059) -> None:
        # Dialect-shifted dev parity: BIGINT IDENTITY → INTEGER
        # PRIMARY KEY AUTOINCREMENT (matches billing_usage_events
        # precedent).
        assert (
            "INTEGER PRIMARY KEY AUTOINCREMENT" in m0059._SQLITE_CREATE_TABLE
        )

    def test_sqlite_branch_idempotent(self, m0059) -> None:
        assert (
            "CREATE TABLE IF NOT EXISTS web_sandbox_instances"
            in m0059._SQLITE_CREATE_TABLE
        )
        assert "IF NOT EXISTS" in m0059._SQLITE_INDEX_LIVE_WORKSPACE
        assert "IF NOT EXISTS" in m0059._SQLITE_INDEX_IDLE
        assert "IF NOT EXISTS" in m0059._SQLITE_INDEX_SANDBOX

    def test_sqlite_partial_unique_uses_status_filter(self, m0059) -> None:
        assert (
            "WHERE status NOT IN ('stopped', 'failed')"
            in m0059._SQLITE_INDEX_LIVE_WORKSPACE
        )

    def test_status_check_clause_matches_enum_whitelist(self, m0059) -> None:
        # Cross-module drift guard: the ``status`` CHECK string in
        # the migration source MUST byte-equal the sorted list of
        # :class:`backend.web_sandbox.WebSandboxStatus`.value strings.
        # Sorted alphabetically so the CHECK clause is reproducible
        # and the drift-guard test can string-match.
        from backend.web_sandbox import WebSandboxStatus

        sorted_values = sorted(s.value for s in WebSandboxStatus)
        expected_clause = ",".join(f"'{v}'" for v in sorted_values)
        assert expected_clause == m0059._STATUS_VALUES_SQL, (
            "alembic 0059 status CHECK clause "
            f"{m0059._STATUS_VALUES_SQL!r} drifted from "
            f"WebSandboxStatus values {sorted_values!r}"
        )

    def test_required_columns_present_in_both_branches(self, m0059) -> None:
        # The eight columns the W14.10 row enumerates plus the
        # bookkeeping triplet (created_at / updated_at / version)
        # plus the ``id`` IDENTITY.
        required = (
            "id",
            "sandbox_id",
            "workspace_id",
            "started_at",
            "ingress_url",
            "status",
            "last_request_at",
            "killed_at",
            "killed_reason",
            "created_at",
            "updated_at",
            "version",
        )
        for col in required:
            assert col in m0059._PG_CREATE_TABLE, f"PG branch missing {col}"
            assert col in m0059._SQLITE_CREATE_TABLE, (
                f"SQLite branch missing {col}"
            )

    def test_idle_index_is_status_then_last_request_at(self, m0059) -> None:
        # W14.5 idle reaper filters first by "non-terminal" then by
        # age; status MUST be left-most for the index to be useful.
        assert (
            "(status, last_request_at)" in m0059._PG_INDEX_IDLE
        )
        assert (
            "(status, last_request_at)" in m0059._SQLITE_INDEX_IDLE
        )

    def test_sandbox_index_is_non_unique(self, m0059) -> None:
        # sandbox_id repeats across re-launches (deterministic from
        # workspace_id), so the index MUST NOT be UNIQUE.
        assert "UNIQUE" not in m0059._PG_INDEX_SANDBOX
        assert "UNIQUE" not in m0059._SQLITE_INDEX_SANDBOX


# ─── Group 2: functional SQLite upgrade ───────────────────────────────────


class _StubBind:
    """Mimics enough of an alembic context bind for ``conn.exec_driver_sql``."""

    def __init__(self, raw: sqlite3.Connection) -> None:
        self._raw = raw

        class _Dialect:
            name = "sqlite"

        self.dialect = _Dialect()

    def exec_driver_sql(self, sql: str, *args, **kwargs):
        return self._raw.execute(sql)


def _bind(monkeypatch, conn: sqlite3.Connection) -> None:
    from alembic import op as alembic_op

    bind = _StubBind(conn)
    monkeypatch.setattr(alembic_op, "get_bind", lambda: bind)


@pytest.fixture()
def upgraded_db(monkeypatch, m0059) -> sqlite3.Connection:
    conn = sqlite3.connect(":memory:")
    conn.execute("PRAGMA foreign_keys = ON")
    _bind(monkeypatch, conn)
    m0059.upgrade()
    return conn


class TestSqliteUpgradeCreatesTable:
    def test_web_sandbox_instances_table_exists(self, upgraded_db) -> None:
        row = upgraded_db.execute(
            "SELECT name FROM sqlite_master "
            "WHERE type='table' AND name='web_sandbox_instances'"
        ).fetchone()
        assert row is not None

    def test_all_required_columns_present(self, upgraded_db) -> None:
        cols = {
            row[1]
            for row in upgraded_db.execute(
                "PRAGMA table_info(web_sandbox_instances)"
            ).fetchall()
        }
        required = {
            "id",
            "sandbox_id",
            "workspace_id",
            "started_at",
            "ingress_url",
            "status",
            "last_request_at",
            "killed_at",
            "killed_reason",
            "created_at",
            "updated_at",
            "version",
        }
        missing = required - cols
        assert not missing, (
            f"web_sandbox_instances missing columns: {missing}"
        )

    def test_id_column_is_integer_pk(self, upgraded_db) -> None:
        rows = upgraded_db.execute(
            "PRAGMA table_info(web_sandbox_instances)"
        ).fetchall()
        id_row = next(r for r in rows if r[1] == "id")
        # SQLite reports type='INTEGER', pk=1 for the IDENTITY column.
        assert id_row[2] == "INTEGER"
        assert id_row[5] == 1

    def test_partial_unique_rejects_second_live_row(self, upgraded_db) -> None:
        upgraded_db.execute(
            "INSERT INTO web_sandbox_instances "
            "(sandbox_id, workspace_id, started_at, status, "
            " last_request_at, created_at, updated_at) "
            "VALUES (?, ?, ?, ?, ?, ?, ?)",
            ("ws-aaaa", "ws-1", 1.0, "running", 1.0, 1.0, 1.0),
        )
        # Second live row for the same workspace_id must raise — the
        # partial UNIQUE enforces the cross-worker invariant ("at
        # most one live sidecar per workspace").
        with pytest.raises(sqlite3.IntegrityError):
            upgraded_db.execute(
                "INSERT INTO web_sandbox_instances "
                "(sandbox_id, workspace_id, started_at, status, "
                " last_request_at, created_at, updated_at) "
                "VALUES (?, ?, ?, ?, ?, ?, ?)",
                ("ws-aaaa", "ws-1", 2.0, "installing", 2.0, 2.0, 2.0),
            )

    def test_partial_unique_allows_terminal_plus_live(
        self, upgraded_db,
    ) -> None:
        # First launch: live row.
        upgraded_db.execute(
            "INSERT INTO web_sandbox_instances "
            "(sandbox_id, workspace_id, started_at, status, "
            " last_request_at, created_at, updated_at) "
            "VALUES (?, ?, ?, ?, ?, ?, ?)",
            ("ws-aaaa", "ws-1", 1.0, "running", 1.0, 1.0, 1.0),
        )
        # First launch terminates.
        upgraded_db.execute(
            "UPDATE web_sandbox_instances "
            "SET status='stopped', killed_at=?, killed_reason=? "
            "WHERE workspace_id='ws-1'",
            (5.0, "operator_request"),
        )
        # Second launch for the SAME workspace_id must succeed —
        # the partial UNIQUE excludes the now-terminal first row.
        upgraded_db.execute(
            "INSERT INTO web_sandbox_instances "
            "(sandbox_id, workspace_id, started_at, status, "
            " last_request_at, created_at, updated_at) "
            "VALUES (?, ?, ?, ?, ?, ?, ?)",
            ("ws-aaaa", "ws-1", 6.0, "running", 6.0, 6.0, 6.0),
        )
        # Audit history: two rows for the same workspace.
        rows = upgraded_db.execute(
            "SELECT COUNT(*) FROM web_sandbox_instances "
            "WHERE workspace_id='ws-1'"
        ).fetchone()
        assert rows[0] == 2

    def test_partial_unique_allows_terminal_plus_failed(
        self, upgraded_db,
    ) -> None:
        # ``failed`` is also exempt from the partial UNIQUE — a
        # failed launch followed by a successful relaunch is the
        # expected pattern when a docker daemon hiccups.
        upgraded_db.execute(
            "INSERT INTO web_sandbox_instances "
            "(sandbox_id, workspace_id, started_at, status, "
            " last_request_at, created_at, updated_at) "
            "VALUES (?, ?, ?, ?, ?, ?, ?)",
            ("ws-bbbb", "ws-2", 1.0, "failed", 1.0, 1.0, 1.0),
        )
        upgraded_db.execute(
            "INSERT INTO web_sandbox_instances "
            "(sandbox_id, workspace_id, started_at, status, "
            " last_request_at, created_at, updated_at) "
            "VALUES (?, ?, ?, ?, ?, ?, ?)",
            ("ws-bbbb", "ws-2", 2.0, "running", 2.0, 2.0, 2.0),
        )

    def test_status_check_rejects_unknown(self, upgraded_db) -> None:
        with pytest.raises(sqlite3.IntegrityError):
            upgraded_db.execute(
                "INSERT INTO web_sandbox_instances "
                "(sandbox_id, workspace_id, started_at, status, "
                " last_request_at, created_at, updated_at) "
                "VALUES (?, ?, ?, ?, ?, ?, ?)",
                ("ws-x", "ws-x", 1.0, "exploded", 1.0, 1.0, 1.0),
            )

    def test_status_check_accepts_each_enum_value(self, upgraded_db) -> None:
        from backend.web_sandbox import WebSandboxStatus

        # Two distinct workspace_ids per status so the partial
        # UNIQUE doesn't reject a second live row when we cycle
        # through statuses.
        for i, status in enumerate(sorted(s.value for s in WebSandboxStatus)):
            upgraded_db.execute(
                "INSERT INTO web_sandbox_instances "
                "(sandbox_id, workspace_id, started_at, status, "
                " last_request_at, created_at, updated_at) "
                "VALUES (?, ?, ?, ?, ?, ?, ?)",
                (
                    f"ws-stat-{i}",
                    f"ws-stat-{i}",
                    1.0,
                    status,
                    1.0,
                    1.0,
                    1.0,
                ),
            )

    def test_idle_index_exists(self, upgraded_db) -> None:
        row = upgraded_db.execute(
            "SELECT name FROM sqlite_master "
            "WHERE type='index' AND name='idx_web_sandbox_instances_idle'"
        ).fetchone()
        assert row is not None

    def test_sandbox_index_exists(self, upgraded_db) -> None:
        row = upgraded_db.execute(
            "SELECT name FROM sqlite_master "
            "WHERE type='index' AND name='idx_web_sandbox_instances_sandbox'"
        ).fetchone()
        assert row is not None

    def test_workspace_live_unique_index_exists(self, upgraded_db) -> None:
        row = upgraded_db.execute(
            "SELECT name FROM sqlite_master "
            "WHERE type='index' "
            "AND name='idx_web_sandbox_instances_workspace_live'"
        ).fetchone()
        assert row is not None

    def test_default_version_is_zero(self, upgraded_db) -> None:
        upgraded_db.execute(
            "INSERT INTO web_sandbox_instances "
            "(sandbox_id, workspace_id, started_at, status, "
            " last_request_at, created_at, updated_at) "
            "VALUES (?, ?, ?, ?, ?, ?, ?)",
            ("ws-c", "ws-c", 1.0, "pending", 1.0, 1.0, 1.0),
        )
        row = upgraded_db.execute(
            "SELECT version FROM web_sandbox_instances "
            "WHERE workspace_id='ws-c'"
        ).fetchone()
        assert row[0] == 0

    def test_id_is_auto_assigned(self, upgraded_db) -> None:
        upgraded_db.execute(
            "INSERT INTO web_sandbox_instances "
            "(sandbox_id, workspace_id, started_at, status, "
            " last_request_at, created_at, updated_at) "
            "VALUES (?, ?, ?, ?, ?, ?, ?)",
            ("ws-d1", "ws-d1", 1.0, "pending", 1.0, 1.0, 1.0),
        )
        upgraded_db.execute(
            "INSERT INTO web_sandbox_instances "
            "(sandbox_id, workspace_id, started_at, status, "
            " last_request_at, created_at, updated_at) "
            "VALUES (?, ?, ?, ?, ?, ?, ?)",
            ("ws-d2", "ws-d2", 1.0, "pending", 1.0, 1.0, 1.0),
        )
        rows = upgraded_db.execute(
            "SELECT id FROM web_sandbox_instances ORDER BY id"
        ).fetchall()
        # IDENTITY auto-assigns monotonically; we don't pin to (1, 2)
        # because the SQLAlchemy bind reuse may bump the seed.
        assert rows[0][0] < rows[1][0]


# ─── Group 3: idempotency ─────────────────────────────────────────────────


class TestIdempotentReupgrade:
    def test_running_upgrade_twice_no_dup_no_change(
        self, monkeypatch, m0059,
    ) -> None:
        conn = sqlite3.connect(":memory:")
        _bind(monkeypatch, conn)
        m0059.upgrade()
        m0059.upgrade()
        # A second upgrade should not have raised; sanity-check the
        # table still exists with the three indexes.
        idx = sorted(
            row[0]
            for row in conn.execute(
                "SELECT name FROM sqlite_master "
                "WHERE type='index' AND tbl_name='web_sandbox_instances'"
            ).fetchall()
        )
        # PK index is auto-named ``sqlite_autoindex_…`` so we filter
        # to just our explicit indexes.
        named = [n for n in idx if n.startswith("idx_")]
        assert "idx_web_sandbox_instances_workspace_live" in named
        assert "idx_web_sandbox_instances_idle" in named
        assert "idx_web_sandbox_instances_sandbox" in named


# ─── Group 4: PG dialect branch executes ──────────────────────────────────


class TestPgBranchExecutes:
    def test_pg_branch_emits_create_table_and_three_indexes(
        self, monkeypatch, m0059,
    ) -> None:
        from alembic import op as alembic_op

        captured: list[str] = []

        class _PgBind:
            class _Dialect:
                name = "postgresql"

            dialect = _Dialect()

            def exec_driver_sql(self, sql, *a, **k):
                captured.append(sql)

        monkeypatch.setattr(alembic_op, "get_bind", lambda: _PgBind())
        m0059.upgrade()

        # CREATE TABLE + three CREATE INDEX = exactly four statements.
        assert len(captured) == 4
        joined = "\n".join(captured)
        assert (
            "CREATE TABLE IF NOT EXISTS web_sandbox_instances" in joined
        )
        assert "DOUBLE PRECISION" in joined
        assert "BIGINT GENERATED BY DEFAULT AS IDENTITY" in joined
        assert (
            "idx_web_sandbox_instances_workspace_live" in joined
        )
        assert "WHERE status NOT IN ('stopped', 'failed')" in joined
        assert "idx_web_sandbox_instances_idle" in joined
        assert "idx_web_sandbox_instances_sandbox" in joined

    def test_pg_downgrade_drops_indexes_then_table(
        self, monkeypatch, m0059,
    ) -> None:
        from alembic import op as alembic_op

        captured: list[str] = []

        class _PgBind:
            class _Dialect:
                name = "postgresql"

            dialect = _Dialect()

            def exec_driver_sql(self, sql, *a, **k):
                captured.append(sql)

        # ``op.execute`` is the alembic public API used in the
        # downgrade; route it to our bind capture too.
        def _exec(sql):
            captured.append(str(sql))

        monkeypatch.setattr(alembic_op, "get_bind", lambda: _PgBind())
        monkeypatch.setattr(alembic_op, "execute", _exec)
        m0059.downgrade()
        joined = "\n".join(captured)
        assert (
            "DROP INDEX IF EXISTS idx_web_sandbox_instances_sandbox"
            in joined
        )
        assert (
            "DROP INDEX IF EXISTS idx_web_sandbox_instances_idle"
            in joined
        )
        assert (
            "DROP INDEX IF EXISTS "
            "idx_web_sandbox_instances_workspace_live"
            in joined
        )
        assert (
            "DROP TABLE IF EXISTS web_sandbox_instances" in joined
        )
        # All three index drops must precede the table drop —
        # explicit ordering documents intent (PG would let DROP
        # TABLE cascade-drop the indexes, but the staged drop is
        # easier to reason about during a partial-rollback recovery).
        i_tab = joined.find("DROP TABLE IF EXISTS")
        for idx_name in (
            "idx_web_sandbox_instances_sandbox",
            "idx_web_sandbox_instances_idle",
            "idx_web_sandbox_instances_workspace_live",
        ):
            i_idx = joined.find(f"DROP INDEX IF EXISTS {idx_name}")
            assert 0 <= i_idx < i_tab, (
                f"{idx_name} drop must precede table drop"
            )


# ─── Group 5: migrator drift guard ───────────────────────────────────────


class TestMigratorListsTable:
    """The Phase-3 G4 lesson: any new table MUST be added to the
    migrator's ``TABLES_IN_ORDER`` or the next prod cutover loses
    its data silently.  Plus: any INTEGER-PK table MUST be added to
    ``TABLES_WITH_IDENTITY_ID`` or the post-replay sequence-restart
    skips it and the next live INSERT collides with a preserved id.
    This class belt+braces the broader ``test_migrator_schema_coverage``
    drift gate by pinning both expected memberships."""

    @staticmethod
    def _load_migrator():
        import importlib.util as _u

        repo_root = Path(__file__).resolve().parents[2]
        spec = _u.spec_from_file_location(
            "migrate_sqlite_to_pg",
            repo_root / "scripts" / "migrate_sqlite_to_pg.py",
        )
        mig = _u.module_from_spec(spec)
        sys.modules["migrate_sqlite_to_pg"] = mig
        spec.loader.exec_module(mig)
        return mig

    def test_web_sandbox_instances_in_tables_in_order(self) -> None:
        mig = self._load_migrator()
        assert "web_sandbox_instances" in mig.TABLES_IN_ORDER

    def test_web_sandbox_instances_in_identity_id_set(self) -> None:
        # PK is BIGINT GENERATED BY DEFAULT AS IDENTITY on PG /
        # INTEGER PRIMARY KEY AUTOINCREMENT on SQLite — the sequence
        # must restart after replay so the next live insert doesn't
        # collide with a preserved id.
        mig = self._load_migrator()
        assert "web_sandbox_instances" in mig.TABLES_WITH_IDENTITY_ID

    def test_web_sandbox_instances_no_fk_so_position_is_late(self) -> None:
        # No FK to any other table; placement near the end with the
        # other operational / audit tables (after billing_usage_events
        # / catalog_entries / install_jobs / catalog_subscriptions)
        # is the row's documented intent.
        mig = self._load_migrator()
        order = list(mig.TABLES_IN_ORDER)
        idx = order.index("web_sandbox_instances")
        # Must be after the catalog tables (BS.1.1 lineage).
        assert idx > order.index("catalog_entries")
        assert idx > order.index("install_jobs")
        assert idx > order.index("catalog_subscriptions")
