"""OP-745 lessons-learned per-file migration contract."""

from __future__ import annotations

import importlib.util
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
LESSONS_DIR = REPO_ROOT / "docs" / "sop" / "lessons"


def _load_script(name: str):
    path = REPO_ROOT / "scripts" / name
    sys.path.insert(0, str(path.parent))
    spec = importlib.util.spec_from_file_location(name.removesuffix(".py"), path)
    assert spec is not None and spec.loader is not None
    mod = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = mod
    spec.loader.exec_module(mod)
    return mod


def test_per_lesson_files_have_frontmatter_and_standard_sections() -> None:
    build = _load_script("build_lessons_index.py")
    lessons = build.load_lessons()

    assert len(lessons) >= 31
    assert (LESSONS_DIR / "L-OP-741-ci-recovery-needs-a-small-explicit-state-machine.md").exists()
    assert (
        LESSONS_DIR
        / "L-OP-742-test-impact-analysis-must-fail-closed-on-the-conservative-si.md"
    ).exists()

    for lesson in lessons:
        for key in ("id", "ticket", "title", "date", "tags"):
            assert lesson.frontmatter[key]
        assert lesson.body.lstrip().startswith("# ")
    build.check_standard_sections(lessons)


def test_lessons_index_is_byte_identical_when_regenerated() -> None:
    build = _load_script("build_lessons_index.py")
    rendered = build.render_index(build.load_lessons())

    assert rendered.startswith("# Lessons Learned")
    assert "AUTO-GENERATED by scripts/build_lessons_index.py" in rendered
    assert "L-OP-740" in rendered


def test_migration_recovers_concurrent_lessons_from_known_conflicting_commits() -> None:
    build = _load_script("build_lessons_index.py")
    migrate = _load_script("migrate_lessons_to_per_file.py")
    supplemental = migrate._supplemental_lessons()
    index = build.render_index(build.load_lessons())

    assert [lesson.ticket for lesson in supplemental] == ["OP-741", "OP-742"]
    assert {lesson.legacy_lesson for lesson in supplemental} == {29, 30}
    for lesson in supplemental:
        assert lesson.title in index


def test_three_parallel_lesson_files_merge_without_conflict(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    repo.mkdir()
    subprocess.run(["git", "init", "-q", "-b", "main"], cwd=repo, check=True)
    subprocess.run(["git", "config", "user.email", "test@example.invalid"], cwd=repo, check=True)
    subprocess.run(["git", "config", "user.name", "Test User"], cwd=repo, check=True)
    (repo / "docs/sop/lessons").mkdir(parents=True)
    (repo / "docs/sop/lessons/.gitkeep").write_text("", encoding="utf-8")
    subprocess.run(["git", "add", "."], cwd=repo, check=True)
    subprocess.run(["git", "commit", "-q", "-m", "base"], cwd=repo, check=True)

    for ticket in ("OP-801", "OP-802", "OP-803"):
        subprocess.run(["git", "switch", "-q", "-c", ticket, "main"], cwd=repo, check=True)
        path = repo / "docs/sop/lessons" / f"L-{ticket}-parallel.md"
        path.write_text(f"lesson for {ticket}\n", encoding="utf-8")
        subprocess.run(["git", "add", str(path.relative_to(repo))], cwd=repo, check=True)
        subprocess.run(["git", "commit", "-q", "-m", ticket], cwd=repo, check=True)

    subprocess.run(["git", "switch", "-q", "main"], cwd=repo, check=True)
    for ticket in ("OP-801", "OP-802", "OP-803"):
        subprocess.run(["git", "merge", "--no-ff", "--no-edit", ticket], cwd=repo, check=True)

    merged = sorted(path.name for path in (repo / "docs/sop/lessons").glob("L-OP-*.md"))
    assert merged == [
        "L-OP-801-parallel.md",
        "L-OP-802-parallel.md",
        "L-OP-803-parallel.md",
    ]
