"""Scaffold: customer IPCAM wired to the prebuilt rtsp-onvif-server (R5.3, OP-2164).

The ipcam pack's other scaffolds *generate* an RTSP/ONVIF stack from
scratch. This one does the opposite — and is the strategic point of the
`omnisight/rtsp-onvif-server` sub-project: a customer IPCAM product
*reuses* the tested, packaged server instead of regenerating it.

Given a product name, a target SoC, a pinned server release tag, and a
packaging system (Yocto via the R5.1 meta-layer, or Buildroot via the
R5.2 external tree), this renders the integration artifacts:

  * a product manifest pinning the server release + board HAL profile,
  * the on-device ``config.yaml`` (device identity + the board profile),
  * a packaging glue snippet (Yocto image-install / Buildroot defconfig),
  * a smoke checklist (ONVIF discovery -> GetStreamUri -> RTSP DESCRIBE).

Pure-Python / stdlib so it renders offline in CI.

Usage:
    from prebuilt_rtsp_onvif_integration import (
        Packaging, render_integration,
    )

    art = render_integration(
        product="acme-doorcam",
        soc="rk3588",
        release_tag="v0.1.0",
        packaging=Packaging.YOCTO,
        manufacturer="Acme",
        model="DoorCam-1",
    )
    print(art.manifest)        # dict, pins server + profile
    print(art.config_yaml)     # str, /etc/rtsp-onvif-server/config.yaml
    print(art.packaging_glue)  # str, layer/defconfig snippet
"""
from __future__ import annotations

import enum
from dataclasses import dataclass, field

SERVER_REPO = "omnisight/rtsp-onvif-server"

# SoC -> the HAL profile id shipped by the server (hal/profiles/<id>.yaml).
# Boards without a dedicated profile fall back to generic-v4l2 (the CI
# reference); a real board profile is a server-side R6 bring-up.
_SOC_PROFILE = {
    "rk3588": "rk3588",
    "rk3576": "rk3576",
    "qcs6490": "qcs6490",
    "rv1126": "rv1126",
}
_DEDICATED_PROFILE_SOCS = frozenset(_SOC_PROFILE)


class Packaging(enum.Enum):
    YOCTO = "yocto"
    BUILDROOT = "buildroot"


@dataclass
class IntegrationArtifacts:
    manifest: dict
    config_yaml: str
    packaging_glue: str
    smoke_checklist: list[str] = field(default_factory=list)


def profile_for_soc(soc: str) -> str:
    """HAL profile id for @soc, or the generic-v4l2 fallback."""
    return _SOC_PROFILE.get(soc, "generic-v4l2")


def soc_has_dedicated_profile(soc: str) -> bool:
    return soc in _DEDICATED_PROFILE_SOCS


def render_config_yaml(*, manufacturer: str, model: str, profile: str,
                       onvif_port: int = 8080, rtsp_port: int = 8554) -> str:
    profiles_dir = "/usr/share/rtsp-onvif-server/hal/profiles"
    return (
        "# Generated by the ipcam prebuilt-server integration (R5.3).\n"
        "# Fill in serial + admin password before shipping.\n"
        "schema_version: 1\n"
        "device:\n"
        f"  manufacturer: {manufacturer}\n"
        f"  model: {model}\n"
        "  firmware_version: 0.1.0\n"
        "  serial: CHANGE-ME\n"
        "rtsp:\n"
        f"  port: {rtsp_port}\n"
        "  interface: 0.0.0.0\n"
        "  users:\n"
        "    - name: admin\n"
        "      password: CHANGE-ME\n"
        "      role: admin\n"
        "onvif:\n"
        f"  port: {onvif_port}\n"
        "recording:\n"
        "  enabled: false\n"
        "  dir: /var/lib/rtsp-onvif-server/recordings\n"
        "  segment_seconds: 60\n"
        "hal:\n"
        f"  profile: {profile}\n"
        f"  profiles_dir: {profiles_dir}\n"
    )


def _yocto_glue(release_tag: str) -> str:
    return (
        "# Yocto: add the meta-layer (R5.1) and pin the release.\n"
        "# bitbake-layers add-layer .../meta-omnisight-rtsp-onvif\n"
        'IMAGE_INSTALL:append = " rtsp-onvif-server"\n'
        f'SRCREV:pn-rtsp-onvif-server = "{release_tag}"\n'
    )


def _buildroot_glue(release_tag: str) -> str:
    return (
        "# Buildroot: point BR2_EXTERNAL at packaging/buildroot (R5.2) and\n"
        "# enable the package; pin the release in your defconfig.\n"
        "BR2_PACKAGE_RTSP_ONVIF_SERVER=y\n"
        f'BR2_PACKAGE_RTSP_ONVIF_SERVER_VERSION="{release_tag}"\n'
    )


def render_integration(*, product: str, soc: str, release_tag: str,
                       packaging: Packaging, manufacturer: str,
                       model: str) -> IntegrationArtifacts:
    if not product:
        raise ValueError("product name is required")
    if not release_tag:
        raise ValueError("release_tag is required (pin the server release)")
    if not isinstance(packaging, Packaging):
        raise TypeError("packaging must be a Packaging enum")

    profile = profile_for_soc(soc)
    manifest = {
        "product": product,
        "soc": soc,
        "server": {
            "repo": SERVER_REPO,
            "release_tag": release_tag,
            "packaging": packaging.value,
        },
        "hal_profile": profile,
        "hal_profile_verified": soc_has_dedicated_profile(soc),
    }

    glue = (_yocto_glue if packaging is Packaging.YOCTO else _buildroot_glue)(
        release_tag)

    checklist = [
        "ONVIF WS-Discovery: device appears in ONVIF Device Manager",
        "Device GetDeviceInformation returns the configured identity",
        "Media GetStreamUri returns rtsp://<dev>:8554/onvif/main",
        "RTSP DESCRIBE on the stream URI returns 200 + SDP",
    ]
    if not soc_has_dedicated_profile(soc):
        checklist.insert(
            0,
            f"WARNING: {soc} has no dedicated HAL profile — using "
            "generic-v4l2 (software encode). Add a board profile + HIL "
            "verify (server R6) before production.",
        )

    return IntegrationArtifacts(
        manifest=manifest,
        config_yaml=render_config_yaml(
            manufacturer=manufacturer, model=model, profile=profile),
        packaging_glue=glue,
        smoke_checklist=checklist,
    )


if __name__ == "__main__":
    art = render_integration(
        product="acme-doorcam", soc="rk3588", release_tag="v0.1.0",
        packaging=Packaging.YOCTO, manufacturer="Acme", model="DoorCam-1")
    import json

    print(json.dumps(art.manifest, indent=2))
    print(art.config_yaml)
    print(art.packaging_glue)
    print("\n".join(art.smoke_checklist))
