// Generated by SKILL-ASTRO (W8 #282).
// Vitest — unit tests for CMS source adapters, webhook verifiers,
// and content helpers. happy-dom is fast enough for our scope
// (Astro uses Vite under the hood; no special setup needed).

import { defineConfig } from "vitest/config"

export default defineConfig({
  test: {
    environment: "happy-dom",
    globals: true,
    setupFiles: ["./tests/unit/setup.ts"],
    include: ["tests/unit/**/*.test.{ts,tsx}"],
    coverage: {
      provider: "v8",
      reporter: ["text", "html", "lcov"],
      exclude: ["**/node_modules/**", "**/.astro/**", "**/dist/**", "**/e2e/**"],
    },
  },
  resolve: {
    alias: {
      "@": new URL("./src", import.meta.url).pathname,
    },
  },
})
