<!--
Generated by SKILL-NUXT (W7 #281).
Top-level app shell — the `<NuxtLayout>` wrapper picks up
`layouts/default.vue` by convention, and `<NuxtPage>` renders the
route matched from `pages/`. This is the idiomatic Nuxt 4 entry
point; frontend-vue role requires the pages-based router idiom.
-->

<template>
  <NuxtLayout>
    <NuxtPage />
  </NuxtLayout>
</template>
