// Generated by SKILL-NUXT (W7 #281).
// Vitest — unit tests for components + Pinia stores + composables.
// happy-dom is faster than jsdom and Nuxt-compatible for our scope.

import { defineConfig } from "vitest/config"

export default defineConfig({
  test: {
    environment: "happy-dom",
    globals: true,
    setupFiles: ["./tests/unit/setup.ts"],
    include: ["tests/unit/**/*.test.{ts,tsx}"],
    coverage: {
      provider: "v8",
      reporter: ["text", "html", "lcov"],
      exclude: ["**/node_modules/**", "**/.nuxt/**", "**/.output/**", "**/e2e/**"],
    },
  },
  resolve: {
    alias: {
      "~": new URL("./", import.meta.url).pathname,
      "@": new URL("./", import.meta.url).pathname,
    },
  },
})
