// Generated by SKILL-NUXT (W7 #281). DRIZZLE=on.
// Drizzle/Postgres client helper. Nitro workers intentionally keep
// separate per-process pools; each worker derives the pool from the
// same DATABASE_URL env var and Postgres coordinates consistency.

import { drizzle } from "drizzle-orm/postgres-js"
import postgres from "postgres"

import * as schema from "../drizzle/schema"

function createDb() {
  const connectionString = process.env.DATABASE_URL
  if (!connectionString) {
    throw new Error("DATABASE_URL must be configured")
  }

  const client = postgres(connectionString, { max: 1 })
  return drizzle(client, { schema })
}

let cachedDb: ReturnType<typeof createDb> | null = null

export function getDb() {
  cachedDb = cachedDb ?? createDb()
  return cachedDb
}
