// Generated by SKILL-NUXT (W7 #281). POSTMARK=on.
// Postmark server tokens stay server-side; never expose them through
// NUXT_PUBLIC_* env vars.

import * as postmark from "postmark"

export async function sendContactEmail(input: {
  fromEmail: string
  subject: string
  body: string
}) {
  const token = process.env.POSTMARK_SERVER_TOKEN
  const to = process.env.CONTACT_TO_EMAIL
  const from = process.env.POSTMARK_FROM_EMAIL
  if (!token || !to || !from) {
    throw new Error(
      "POSTMARK_SERVER_TOKEN, CONTACT_TO_EMAIL, and POSTMARK_FROM_EMAIL must be configured",
    )
  }

  const client = new postmark.ServerClient(token)
  return client.sendEmail({
    From: from,
    To: to,
    ReplyTo: input.fromEmail,
    Subject: input.subject,
    TextBody: input.body,
  })
}
