<!--
Generated by SKILL-ASTRO (W8 #282). ISLANDS=svelte.
Example island component. Astro ships this with its own JS bundle
but only hydrates when the client: directive fires (client:visible
by default in the MDX seed). Everything outside the island tree
stays static HTML.
-->

<script lang="ts">
  export let initial: number = 0
  let count = initial
  function increment() {
    count += 1
  }
</script>

<section aria-labelledby="counter-heading">
  <h2 id="counter-heading">Counter</h2>
  <button type="button" aria-label="increment counter" on:click={increment}>
    Count: {count}
  </button>
</section>
