// Generated by SKILL-ASTRO (W8 #282). ISLANDS=react.
// Example island component. Astro ships this with its own JS bundle
// but only hydrates when the client: directive fires
// (client:visible by default in the MDX seed). Everything outside
// the island tree stays static HTML.

import { useState } from "react"

export default function Counter({ initial = 0 }) {
  const [count, setCount] = useState(initial)
  return (
    <section aria-labelledby="counter-heading">
      <h2 id="counter-heading">Counter</h2>
      <button
        type="button"
        aria-label="increment counter"
        onClick={() => setCount((c) => c + 1)}
      >
        Count: {count}
      </button>
    </section>
  )
}
