<!--
Generated by SKILL-ASTRO (W8 #282). ISLANDS=vue.
Example island component. Astro ships this with its own JS bundle
but only hydrates when the client: directive fires (client:visible
by default in the MDX seed). Everything outside the island tree
stays static HTML.
-->

<script setup lang="ts">
import { ref } from "vue"

interface Props {
  initial?: number
}
const props = withDefaults(defineProps<Props>(), { initial: 0 })
const count = ref(props.initial)
function increment() {
  count.value += 1
}
</script>

<template>
  <section aria-labelledby="counter-heading">
    <h2 id="counter-heading">Counter</h2>
    <button
      type="button"
      aria-label="increment counter"
      @click="increment"
    >
      Count: {{ count }}
    </button>
  </section>
</template>
