"use server"

// Generated by SKILL-NEXTJS (W6 #280).
// Server Actions — invoked from Client Components via form submission
// or directly. Runs on the server only; env secrets are safe here.

export async function recordEvent(eventName: string, payload: unknown) {
  const backend = process.env.BACKEND_URL || "http://localhost:8000"
  const res = await fetch(`${backend}/api/v1/events`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ event: eventName, payload }),
  })
  if (!res.ok) throw new Error(`recordEvent failed: ${res.status}`)
  return res.json()
}
