// Generated by SKILL-NEXTJS (W6 #280).
// Server Component — data fetching happens here.
// Interactive bits get delegated to Client Components.
// (see components/Counter.tsx)

import { Counter } from "@/components/Counter"

async function loadStats() {
  const backend = process.env.BACKEND_URL || "http://localhost:8000"
  try {
    const res = await fetch(`${backend}/api/v1/health`, {
      next: { revalidate: 60 },
    })
    if (!res.ok) throw new Error(`backend ${res.status}`)
    return (await res.json()) as { status: string; version?: string }
  } catch {
    return { status: "unreachable", version: "n/a" }
  }
}

export default async function Home() {
  const stats = await loadStats()

  return (
    <main id="main" role="main">
      <h1>{"{{"}} project_name {"}}"}</h1>
      <p>Backend: {stats.status} ({stats.version})</p>
      <Counter initial={0} />
    </main>
  )
}
