// Generated by SKILL-NEXTJS (W6 #280).
// Health probe — intentionally does not depend on the backend so that
// cold-start liveness checks stay green even when the upstream is
// warming up. Returns 200 with a stable schema.

import { NextResponse } from "next/server"

export const runtime = "edge"
export const dynamic = "force-dynamic"

export async function GET() {
  return NextResponse.json({
    status: "ok",
    service: "nextjs",
    at: new Date().toISOString(),
  })
}
