// Generated by SKILL-GO-SERVICE (X6 #302).
//
// Structured JSON logger built on the stdlib `log/slog` — the
// backend-go role default (Go 1.21+). Anti-pattern: printing via
// fmt.Println in production code. Every handler takes *slog.Logger
// from this package and attaches request-scoped fields with With().

package logging

import (
	"log/slog"
	"os"
)

// New returns a JSON-formatted slog.Logger at the requested level.
// Unknown levels fall back to info — Settings.Validate() already
// rejected malformed values, so this branch is defensive, not hot.
func New(level string) *slog.Logger {
	var lvl slog.Level
	switch level {
	case "debug":
		lvl = slog.LevelDebug
	case "warn":
		lvl = slog.LevelWarn
	case "error":
		lvl = slog.LevelError
	default:
		lvl = slog.LevelInfo
	}
	handler := slog.NewJSONHandler(os.Stdout, &slog.HandlerOptions{
		Level:     lvl,
		AddSource: false,
	})
	return slog.New(handler)
}
