// Generated by SKILL-NUXT (W7 #281).
// Pinia store unit tests — proves the store behaviour is stable
// across renders. Because nuxt scaffolder sets up a fresh Pinia
// in tests/unit/setup.ts, each test starts from count=0.

import { describe, it, expect } from "vitest"
import { useCounterStore } from "@/stores/counter"

describe("useCounterStore", () => {
  it("starts at zero", () => {
    const store = useCounterStore()
    expect(store.count).toBe(0)
  })

  it("increments via action", () => {
    const store = useCounterStore()
    store.increment()
    store.increment()
    expect(store.count).toBe(2)
  })

  it("doubled getter reflects state", () => {
    const store = useCounterStore()
    store.count = 7
    expect(store.doubled).toBe(14)
  })

  it("reset action returns to zero", () => {
    const store = useCounterStore()
    store.count = 99
    store.reset()
    expect(store.count).toBe(0)
  })
})
