// Generated by SKILL-NUXT (W7 #281).
// Vitest setup — installs a fresh Pinia instance per test run so
// stores start from state initial. Imported via vitest.config.ts
// setupFiles.

import { beforeEach } from "vitest"
import { createPinia, setActivePinia } from "pinia"

beforeEach(() => {
  setActivePinia(createPinia())
})
