// Generated by SKILL-RUST-CLI (X7 #303).
//
// Error plumbing. Scaffold keeps the split minimal:
//   * `anyhow::Result` is the working alias in `main` / command
//     entry points — we want ergonomic `?` with context.
//   * Library-internal modules that want a concrete error type use
//     `thiserror` derives on their own enum — kept here as a
//     documented seed (`CliError`) rather than sprinkled.
//
// The cli-tooling role anti-pattern "over-use of unwrap() in
// library code" is the driver: library modules should surface
// Result<_, ConcreteError>; only main/commands collapse to anyhow.

use thiserror::Error;

/// Seed error for library modules. Extend per-crate as concrete
/// variants accrue; `anyhow::Error` wraps it transparently at the
/// CLI boundary.
#[derive(Debug, Error)]
pub enum CliError {
    #[error("configuration error: {0}")]
    Config(String),

    #[error("I/O error: {0}")]
    Io(#[from] std::io::Error),

    #[error("serialization error: {0}")]
    Serde(#[from] serde_json::Error),
}

pub type Result<T> = std::result::Result<T, CliError>;
