// Generated by SKILL-RUST-CLI (X7 #303).
//
// tracing-subscriber wiring. Two knobs drive the subscriber shape:
//   * `level` — "error" | "warn" | "info" | "debug" | "trace" —
//     fed from Cli::verbosity().
//   * `json` — when true, emit JSON lines on stderr (machine
//     consumption). When false, use the default human formatter
//     and honour is_terminal() for ANSI colour gating (the
//     cli-tooling role forbids hard-coded ANSI escapes).
//
// The role rule "logs → stderr, data → stdout" is enforced by
// always writing to stderr regardless of --json. --json only
// affects stdout command output, not log formatting.

use anyhow::{Context, Result};
use is_terminal::IsTerminal;
use tracing_subscriber::{fmt, EnvFilter};

pub fn init(level: &str, json: bool, quiet: bool) -> Result<()> {
    // When --quiet we still want errors visible — "error" filter.
    // The cli-tooling role rule says `--quiet` silences "everything
    // below WARN"; we go one step further and allow ERROR only,
    // since a hard failure has to surface somehow.
    let filter_spec = if quiet { "error" } else { level };

    // RUST_LOG env var overrides the flag-derived level so operators
    // can peek without re-invoking with -v flags.
    let filter = EnvFilter::try_from_default_env()
        .unwrap_or_else(|_| EnvFilter::new(filter_spec));

    let use_ansi = !json && std::io::stderr().is_terminal();

    if json {
        fmt()
            .with_env_filter(filter)
            .json()
            .with_current_span(false)
            .with_writer(std::io::stderr)
            .try_init()
            .map_err(|e| anyhow::anyhow!("tracing init failed: {e}"))
            .context("subscriber init (json)")?;
    } else {
        fmt()
            .with_env_filter(filter)
            .with_ansi(use_ansi)
            .with_writer(std::io::stderr)
            .try_init()
            .map_err(|e| anyhow::anyhow!("tracing init failed: {e}"))
            .context("subscriber init (fmt)")?;
    }

    Ok(())
}
