// Generated by SKILL-NEXTJS (W6 #280).

import { describe, it, expect } from "vitest"
import { render, screen, fireEvent } from "@testing-library/react"
import { Counter } from "@/components/Counter"

describe("Counter", () => {
  it("renders with initial value", () => {
    render(<Counter initial={3} />)
    expect(screen.getByRole("button")).toHaveTextContent("Count: 3")
  })

  it("increments on click", () => {
    render(<Counter initial={0} />)
    const btn = screen.getByRole("button")
    fireEvent.click(btn)
    fireEvent.click(btn)
    expect(btn).toHaveTextContent("Count: 2")
  })

  it("exposes accessible label", () => {
    render(<Counter />)
    expect(screen.getByRole("button", { name: /increment counter/i })).toBeInTheDocument()
  })
})
