// Generated by SKILL-NEXTJS (W6 #280).

import { afterEach, describe, it, expect, vi } from "vitest"
import { render, screen, fireEvent } from "@testing-library/react"
import { TodoApp } from "@/components/TodoApp"

describe("TodoApp", () => {
  afterEach(() => {
    vi.restoreAllMocks()
  })

  it("renders seeded tasks and remaining count", () => {
    render(
      <TodoApp
        initialTodos={[
          { id: "one", title: "Done task", done: true },
          { id: "two", title: "Open task", done: false },
        ]}
      />,
    )

    expect(screen.getByText("Done task")).toBeInTheDocument()
    expect(screen.getByText("Open task")).toBeInTheDocument()
    expect(screen.getByText("1 remaining")).toBeInTheDocument()
  })

  it("adds, toggles, and deletes a task", () => {
    vi.spyOn(Date, "now").mockReturnValue(1234)

    render(<TodoApp />)

    fireEvent.change(screen.getByLabelText(/new task/i), {
      target: { value: "Call design partner" },
    })
    fireEvent.click(screen.getByRole("button", { name: /add/i }))

    const task = screen.getByLabelText("Call design partner")
    expect(task).toBeInTheDocument()
    expect(screen.getByText("1 remaining")).toBeInTheDocument()

    fireEvent.click(task)
    expect(screen.getByText("0 remaining")).toBeInTheDocument()

    fireEvent.click(screen.getByRole("button", { name: /delete/i }))
    expect(screen.queryByText("Call design partner")).not.toBeInTheDocument()
  })
})
