# OmniSight camera Yocto layer configuration.

BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "omnisight-camera"
BBFILE_PATTERN_omnisight-camera = "^${LAYERDIR}/"
BBFILE_PRIORITY_omnisight-camera = "6"

LAYERSERIES_COMPAT_omnisight-camera = "scarthgap"
