// Generated by SKILL-ASTRO (W8 #282).
// Smoke E2E — confirms a cold boot of the generated site serves
// the home page, the blog route renders from the content collection,
// and the RSS feed is wired. If any fails, the W2 simulate-track
// Playwright gate will also fail.

import { test, expect } from "@playwright/test"

test("home page renders heading and lists posts", async ({ page }) => {
  await page.goto("/")
  await expect(page.getByRole("main")).toBeVisible()
  await expect(page.getByRole("heading", { level: 1 })).toBeVisible()
  await expect(page.getByRole("heading", { name: "Recent posts" })).toBeVisible()
})

test("hello-world blog post renders from MDX", async ({ page }) => {
  await page.goto("/blog/hello-world")
  await expect(page.getByRole("heading", { name: /Hello, World/ })).toBeVisible()
})

test("rss feed is reachable", async ({ request }) => {
  const res = await request.get("/rss.xml")
  expect(res.status()).toBe(200)
  const body = await res.text()
  expect(body).toContain("<rss")
})

test("about page navigates via pages-based router", async ({ page }) => {
  await page.goto("/")
  await page.getByRole("link", { name: "About" }).click()
  await expect(page).toHaveURL(/\/about$/)
  await expect(page.getByRole("heading", { name: "About" })).toBeVisible()
})
