"""Phase-3 P1 — PG schema sync: tables/columns that ``backend/db.py``
created at runtime on SQLite but never got a corresponding alembic
migration.

Why this migration is needed
────────────────────────────
The project runs TWO schema-creation paths:

  1. ``backend/db.py::init()`` — a monolithic ``CREATE TABLE IF NOT
     EXISTS`` string executed on the aiosqlite connection at boot +
     ``_migrate()`` which does ad-hoc ``ALTER TABLE ADD COLUMN`` on
     older databases.
  2. ``alembic upgrade head`` — used by CI's pg-matrix and by any
     PostgreSQL-backed deployment.

Path #1 is the canonical schema for SQLite (happens on every boot,
idempotent). Path #2 should mirror it exactly — but over ~6 phases,
several schema additions landed via #1 only and never got a
corresponding ``alembic/versions/0xxx_*.py``. The result: a fresh
``alembic upgrade head`` against Postgres produces a schema **missing
7 whole tables + 6 columns** relative to the SQLite reality.

The F3 drift guard (``backend/tests/test_migrator_schema_coverage.py``)
catches migrator-vs-SQLite drift but did NOT catch
alembic-vs-SQLite drift. This migration + the companion extension to
that test (column-parity assertion) locks the third leg down.

What this migration does
────────────────────────
Creates 7 tables on PG (no-op on SQLite via ``IF NOT EXISTS``):

  * ``bootstrap_state``     — first-boot wizard checkpoint (B9)
  * ``dag_plans``           — Phase 56-DAG-B planner output
  * ``iq_runs``             — Phase 63-D nightly IQ benchmark results
  * ``mfa_backup_codes``    — K3 TOTP/WebAuthn backup codes
  * ``password_history``    — K7 password-reuse prevention
  * ``prompt_versions``     — Phase 60 prompt lineage / rollback
  * ``user_mfa``            — K3 MFA secret + WebAuthn credential

Adds 7 columns that ``_migrate()`` ALTER-added on SQLite only:

  * ``sessions.ua_hash``
  * ``users.must_change_password``
  * ``workflow_runs.dag_plan_id``
  * ``workflow_runs.successor_run_id``
  * ``workflow_steps.dag_task_id``
  * ``episodic_memory.decayed_score``
  * ``episodic_memory.last_used_at``

Retrofits ``event_log.id`` from plain ``INTEGER PRIMARY KEY`` to
``GENERATED BY DEFAULT AS IDENTITY``. Rationale: on SQLite plain
``INTEGER PRIMARY KEY`` auto-allocates via rowid aliasing, but the
``alembic_pg_compat`` shim's AUTOINCREMENT rewrite only fires when
the ``AUTOINCREMENT`` keyword is literally present. The 0001 baseline
declared ``event_log.id INTEGER PRIMARY KEY`` (no ``AUTOINCREMENT``),
so PG got a plain integer column with no default — every
``INSERT INTO event_log (event_type, ...)`` without explicit id
would fail on PG with a NOT-NULL violation. Caught during Phase-3
real-cutover dry-run. Follow-up: tighten the compat shim to handle
bare ``INTEGER PRIMARY KEY`` too so future migrations can't recreate
this gap (separate commit).

Dialect handling
────────────────
SQLite does not support ``ALTER TABLE ... ADD COLUMN IF NOT EXISTS``
(it is a PostgreSQL extension). On a legacy SQLite instance the
columns already exist — they were added by ``db.py::_migrate()``.
So on SQLite we make this migration a no-op for the ALTER TABLE
steps (the tables are covered by ``IF NOT EXISTS`` in their CREATE
statements and so are safe).

On PostgreSQL the columns are genuinely missing after
``alembic upgrade head`` today, so we use the native
``ADD COLUMN IF NOT EXISTS`` (PG 9.6+). The ``IF NOT EXISTS`` is a
belt-and-braces guard against operators who manually added the
columns out of band — the migration stays idempotent either way.

Revision ID: 0016
Revises: 0015
Create Date: 2026-04-20
"""
from __future__ import annotations

from alembic import op

revision = "0016"
down_revision = "0015"
branch_labels = None
depends_on = None


def upgrade() -> None:
    conn = op.get_bind()

    # ─── Tables ────────────────────────────────────────────────────────
    # Table DDL is identical on both dialects — AUTOINCREMENT /
    # ``datetime('now')`` / unquoted identifiers get rewritten by
    # ``alembic_pg_compat.install_pg_compat`` at cursor-execute time
    # when the bind is PG.

    # K3 — MFA secret / WebAuthn credential per user. One row per
    # enrolled method; ``method`` discriminates 'totp' vs 'webauthn'.
    conn.exec_driver_sql(
        """
        CREATE TABLE IF NOT EXISTS user_mfa (
            id              TEXT PRIMARY KEY,
            user_id         TEXT NOT NULL,
            method          TEXT NOT NULL,
            secret          TEXT NOT NULL DEFAULT '',
            credential      TEXT NOT NULL DEFAULT '',
            name            TEXT NOT NULL DEFAULT '',
            verified        INTEGER NOT NULL DEFAULT 0,
            created_at      TEXT NOT NULL DEFAULT (datetime('now')),
            last_used       TEXT,
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
        )
        """
    )
    conn.exec_driver_sql(
        "CREATE INDEX IF NOT EXISTS idx_user_mfa_user ON user_mfa(user_id)"
    )

    # K3 — TOTP/WebAuthn backup codes (hashed). One-time use, the
    # ``used`` flag flips to 1 on redemption.
    conn.exec_driver_sql(
        """
        CREATE TABLE IF NOT EXISTS mfa_backup_codes (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id         TEXT NOT NULL,
            code_hash       TEXT NOT NULL,
            used            INTEGER NOT NULL DEFAULT 0,
            created_at      TEXT NOT NULL DEFAULT (datetime('now')),
            used_at         TEXT,
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
        )
        """
    )
    conn.exec_driver_sql(
        "CREATE INDEX IF NOT EXISTS idx_mfa_backup_user "
        "ON mfa_backup_codes(user_id)"
    )

    # K7 — password history for reuse prevention. Keep the last N
    # hashes per user (retention policy enforced at application layer).
    conn.exec_driver_sql(
        """
        CREATE TABLE IF NOT EXISTS password_history (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id         TEXT NOT NULL,
            password_hash   TEXT NOT NULL,
            created_at      TEXT NOT NULL DEFAULT (datetime('now')),
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
        )
        """
    )
    conn.exec_driver_sql(
        "CREATE INDEX IF NOT EXISTS idx_password_history_user "
        "ON password_history(user_id)"
    )

    # Phase 60 — prompt version lineage. ``role`` is one of
    # active|canary|archive; a (path, version) pair is unique so the
    # promoter can assert "exactly one active per path" at write time.
    conn.exec_driver_sql(
        """
        CREATE TABLE IF NOT EXISTS prompt_versions (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            path            TEXT NOT NULL,
            version         INTEGER NOT NULL,
            role            TEXT NOT NULL DEFAULT 'archive',
            body            TEXT NOT NULL,
            body_sha256     TEXT NOT NULL,
            success_count   INTEGER NOT NULL DEFAULT 0,
            failure_count   INTEGER NOT NULL DEFAULT 0,
            created_at      REAL NOT NULL,
            promoted_at     REAL,
            rolled_back_at  REAL,
            rollback_reason TEXT,
            UNIQUE(path, version)
        )
        """
    )
    conn.exec_driver_sql(
        "CREATE INDEX IF NOT EXISTS idx_prompt_versions_path_role "
        "ON prompt_versions(path, role)"
    )

    # Phase 56-DAG-B — DAG planner output + mutation chain.
    # ``parent_plan_id`` self-links the prior round so the orchestrator
    # can walk back without a separate lineage table.
    conn.exec_driver_sql(
        """
        CREATE TABLE IF NOT EXISTS dag_plans (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            dag_id          TEXT NOT NULL,
            run_id          TEXT,
            parent_plan_id  INTEGER,
            json_body       TEXT NOT NULL,
            status          TEXT NOT NULL DEFAULT 'pending',
            mutation_round  INTEGER NOT NULL DEFAULT 0,
            validation_errors TEXT,
            created_at      REAL NOT NULL,
            updated_at      REAL NOT NULL
        )
        """
    )
    conn.exec_driver_sql(
        "CREATE INDEX IF NOT EXISTS idx_dag_plans_dag_id ON dag_plans(dag_id)"
    )
    conn.exec_driver_sql(
        "CREATE INDEX IF NOT EXISTS idx_dag_plans_run_id ON dag_plans(run_id)"
    )
    conn.exec_driver_sql(
        "CREATE INDEX IF NOT EXISTS idx_dag_plans_status ON dag_plans(status)"
    )

    # Phase 63-D — nightly IQ benchmark results. One row per
    # (run, model, benchmark); ``truncated_at_question`` non-null when
    # the token-budget cap aborted early.
    conn.exec_driver_sql(
        """
        CREATE TABLE IF NOT EXISTS iq_runs (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            ts              REAL NOT NULL,
            model           TEXT NOT NULL,
            benchmark       TEXT NOT NULL,
            weighted_score  REAL NOT NULL,
            pass_count      INTEGER NOT NULL,
            total_count     INTEGER NOT NULL,
            tokens_used     INTEGER NOT NULL DEFAULT 0,
            truncated_at_question TEXT
        )
        """
    )
    conn.exec_driver_sql(
        "CREATE INDEX IF NOT EXISTS idx_iq_runs_model_ts ON iq_runs(model, ts)"
    )
    conn.exec_driver_sql(
        "CREATE INDEX IF NOT EXISTS idx_iq_runs_ts ON iq_runs(ts)"
    )

    # B9 — first-boot wizard checkpoint. TEXT PK is deliberate (the
    # step name), so the migrator MUST NOT list this in
    # ``TABLES_WITH_IDENTITY_ID`` — asserted by the F3 / column-parity
    # test in ``test_migrator_schema_coverage.py``.
    conn.exec_driver_sql(
        """
        CREATE TABLE IF NOT EXISTS bootstrap_state (
            step            TEXT PRIMARY KEY,
            completed_at    TEXT NOT NULL DEFAULT (datetime('now')),
            actor_user_id   TEXT,
            metadata        TEXT NOT NULL DEFAULT '{}'
        )
        """
    )

    # ─── Column drift (dialect-aware) ─────────────────────────────────
    # SQLite legacy rows already have these columns via
    # ``db.py::_migrate()``. A plain ``ALTER TABLE ... ADD COLUMN``
    # would duplicate-error on SQLite. PG supports
    # ``ADD COLUMN IF NOT EXISTS`` (9.6+); SQLite does not. Split on
    # dialect name to keep the migration idempotent on both sides.
    is_pg = conn.dialect.name == "postgresql"

    def _add(sql: str) -> None:
        """Add a column. On PG use ``IF NOT EXISTS`` so the migration
        is idempotent against out-of-band ops; on SQLite no-op (the
        column already exists via ``_migrate()``, which is itself
        idempotent via try/except)."""
        if is_pg:
            conn.exec_driver_sql(sql.replace(" ADD COLUMN ", " ADD COLUMN IF NOT EXISTS "))

    # K4 — session rotation + UA binding. Non-null DEFAULT '' so
    # existing rows remain valid; the app recomputes on next request.
    _add("ALTER TABLE sessions ADD COLUMN ua_hash TEXT NOT NULL DEFAULT ''")

    # K1 — force password change for default-credential admins.
    _add(
        "ALTER TABLE users ADD COLUMN must_change_password "
        "INTEGER NOT NULL DEFAULT 0"
    )

    # Phase 56-DAG-B — two-way link between workflow_runs ↔ dag_plans.
    _add("ALTER TABLE workflow_runs ADD COLUMN dag_plan_id INTEGER")
    _add("ALTER TABLE workflow_runs ADD COLUMN successor_run_id TEXT")
    _add("ALTER TABLE workflow_steps ADD COLUMN dag_task_id TEXT")

    # Phase 63-E — memory quality decay. Per-row decayed score +
    # timestamp; the decay worker filters by last_used_at so the
    # matching index is worth its keep on PG too.
    _add(
        "ALTER TABLE episodic_memory ADD COLUMN decayed_score "
        "REAL NOT NULL DEFAULT 0.0"
    )
    _add("ALTER TABLE episodic_memory ADD COLUMN last_used_at TEXT")
    conn.exec_driver_sql(
        "CREATE INDEX IF NOT EXISTS idx_episodic_last_used "
        "ON episodic_memory(last_used_at)"
    )

    # ─── event_log.id IDENTITY retrofit (PG only) ──────────────────────
    # See docstring. On SQLite the column is already rowid-aliased
    # auto-increment; on PG we need an IDENTITY sequence or the app
    # can't insert without specifying id.
    if is_pg:
        # Guard with an inspection — if a future migration (or a manual
        # DBA) already attached IDENTITY, the second ADD would raise
        # ``column "id" of relation "event_log" is already an identity
        # column``. Cheaper than catching the exception.
        already_identity = conn.exec_driver_sql(
            "SELECT attidentity FROM pg_attribute "
            "WHERE attrelid = 'public.event_log'::regclass "
            "AND attname = 'id'"
        ).scalar()
        if already_identity == "":
            conn.exec_driver_sql(
                "ALTER TABLE event_log "
                "ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY"
            )


def downgrade() -> None:
    # On SQLite ``DROP COLUMN`` is supported only in 3.35+ and is not
    # generally safe (sqlite drops are physical-table rewrites). This
    # downgrade is PG-only in practice — CI's ``postgres-matrix`` is
    # the only place that exercises downgrade → upgrade cycles.
    conn = op.get_bind()
    is_pg = conn.dialect.name == "postgresql"

    if is_pg:
        # Drop the event_log identity first — reverse of upgrade.
        already_identity = conn.exec_driver_sql(
            "SELECT attidentity FROM pg_attribute "
            "WHERE attrelid = 'public.event_log'::regclass "
            "AND attname = 'id'"
        ).scalar()
        if already_identity == "d":
            conn.exec_driver_sql(
                "ALTER TABLE event_log ALTER COLUMN id DROP IDENTITY"
            )
        conn.exec_driver_sql("DROP INDEX IF EXISTS idx_episodic_last_used")
        conn.exec_driver_sql(
            "ALTER TABLE episodic_memory DROP COLUMN IF EXISTS last_used_at"
        )
        conn.exec_driver_sql(
            "ALTER TABLE episodic_memory DROP COLUMN IF EXISTS decayed_score"
        )
        conn.exec_driver_sql(
            "ALTER TABLE workflow_steps DROP COLUMN IF EXISTS dag_task_id"
        )
        conn.exec_driver_sql(
            "ALTER TABLE workflow_runs DROP COLUMN IF EXISTS successor_run_id"
        )
        conn.exec_driver_sql(
            "ALTER TABLE workflow_runs DROP COLUMN IF EXISTS dag_plan_id"
        )
        conn.exec_driver_sql(
            "ALTER TABLE users DROP COLUMN IF EXISTS must_change_password"
        )
        conn.exec_driver_sql(
            "ALTER TABLE sessions DROP COLUMN IF EXISTS ua_hash"
        )

    # ``DROP TABLE IF EXISTS`` is safe on both dialects.
    for t in (
        "bootstrap_state",
        "iq_runs",
        "dag_plans",
        "prompt_versions",
        "password_history",
        "mfa_backup_codes",
        "user_mfa",
    ):
        conn.exec_driver_sql(f"DROP TABLE IF EXISTS {t}")
