"""Y9 #285 row 3 — per-(tenant_id, project_id) billing usage events.

Adds a single append-only ``billing_usage_events`` table that records
every billable activity tagged with the ``(tenant_id, project_id)``
tuple so the T4 usage aggregator can roll up costs per project and the
T6 pricing page can render a per-project breakdown.

Why this table is separate from ``token_usage``
────────────────────────────────────────────────
``token_usage`` (alembic 0001 + 0024 + 0025) is a **per-model rollup**
keyed by ``model TEXT PRIMARY KEY``. It tracks lifetime input/output
tokens, cost, request count, etc. *aggregated across the entire host*.
That shape is the right one for the operator-facing "model spend
dashboard" but it is wrong for billing — the rollup loses tenant +
project provenance the moment a second tenant calls the same model.

``billing_usage_events`` is the **append-only fact table** that keeps
the per-event ``(tenant_id, project_id)`` tuple. Every billable
activity writes one row; the T4 aggregator + T6 breakdown view read
it back and group by whatever dimension they need (tenant, project,
day, kind, model). The two tables are NOT redundant — ``token_usage``
keeps its shape for cross-tenant operator dashboards, this table is
the billing source of truth.

Three event kinds (constrained by CHECK)
─────────────────────────────────────────
* ``llm_call`` — one row per LLM invocation. Carries
  ``model`` + ``input_tokens`` + ``output_tokens`` +
  ``cache_read_tokens`` + ``cache_create_tokens`` + ``cost_usd``.
* ``workflow_run`` — one row per completed workflow_run (status
  ``completed`` / ``failed`` / ``halted``). Carries
  ``workflow_run_id`` + ``workflow_kind`` + ``workflow_status`` +
  ``duration_ms`` (in ``metadata_json``). Cost is 0.0 (the underlying
  LLM calls inside the run already have their own ``llm_call``
  rows; the ``workflow_run`` row is for run-count + duration billing
  signals only — never double-counts spend).
* ``workspace_gb_hour`` — one row per per-tenant-per-project
  workspace disk-usage sample emitted at every workspace-GC sweep.
  Carries ``gb_hours`` (the integral of GB × hours since the prior
  sample). Cost is 0.0 (storage is billed via plan tiers, not
  per-hour multipliers — Y9 row 3 only mandates the *measurement*
  plumbing; the rate × quantity step lives in T4).

Schema decisions
────────────────
* **``id BIGINT GENERATED BY DEFAULT AS IDENTITY``** via the
  ``alembic_pg_compat`` shim's ``INTEGER PRIMARY KEY AUTOINCREMENT``
  rewrite. Same convention as ``audit_log`` — high-volume
  fact-table cardinality justifies a 64-bit id space, the shim handles
  SQLite's ``rowid``-aliasing the same way.
* **``project_id NOT NULL DEFAULT 'p-default-default'``**. Y1 row 7
  (alembic 0038) made ``workflow_runs.project_id`` *NULL-able* so
  pre-Y1 legacy rows could keep their ``NULL``. For billing we WANT
  every event tagged — a ``NULL`` project leaks spend into
  unattributable buckets. The default ``'p-default-default'`` is the
  deterministic projection of ``t-default``'s default project from
  alembic 0037, so callers that omit ``project_id`` (legacy code paths
  + the LLM call-back when the request handler did not set the
  project ContextVar) still attribute to a known bucket. This matches
  the Y9 row 5 acceptance criterion: "billing 用量聚合與 workflow_run
  對齊不會漏掉 project_id IS NULL 的舊資料（走 'default' project
  歸因）".
* **``tenant_id NOT NULL DEFAULT 't-default'``**. Same rationale —
  every event is tagged. ``t-default`` is the platform tenant from
  I1 alembic 0012; cron / system-issued events that have no request
  context fall here.
* **``occurred_at REAL NOT NULL``** (UNIX seconds, like ``audit_log.ts``).
  Float not text so ``WHERE occurred_at >= $1 AND occurred_at <= $2``
  range scans use the b-tree index without a string cast.
* **``CHECK (kind IN (...))``** — three known values; a new kind
  needs a migration + the CHECK extension. Keeping the set closed
  catches a typo in ``record_workflow_run('worflow_run', ...)`` at
  insert time rather than during the breakdown query.
* **``cost_usd REAL NOT NULL DEFAULT 0.0``** — the dollar amount the
  emitter has computed (LLM calls multiply tokens × ``pricing.yaml``
  rates at write time so a later YAML update doesn't retroactively
  re-bill historical events; mirrors the
  ``token_usage.cost`` policy locked in by Z.3 #292 checkbox 7).
* **``quantity REAL NOT NULL DEFAULT 1.0``** — generic count field.
  ``llm_call`` rows leave it at 1.0 (one call); ``workflow_run`` rows
  leave it at 1.0 (one run); ``workspace_gb_hour`` rows set it to
  ``gb * hours_since_prior_sample`` so a downstream ``SUM(quantity)``
  group-by-(tenant,project,month) yields the GB-hour total directly.
* **``metadata_json TEXT NOT NULL DEFAULT '{}'``** — extension slot
  for kind-specific fields the Y9 contract doesn't enumerate yet
  (e.g. provider, model context-window-pct, workflow plan_id, GC
  reason). Read-side aggregators ignore it; write-side emitters can
  add new keys without a schema migration.

Indexes
───────
1. ``idx_billing_usage_events_tenant_project_time`` on
   ``(tenant_id, project_id, occurred_at DESC)`` — primary read path
   (per-project breakdown for a tenant in a time window).
2. ``idx_billing_usage_events_tenant_kind_time`` on
   ``(tenant_id, kind, occurred_at DESC)`` — secondary read path
   (per-kind breakdown for a tenant — "how much LLM spend vs how
   much storage" pie slice).

Drift guard
───────────
Y9 row 5 acceptance criterion mandates a drift test that holds
``backend.billing_usage.ALL_USAGE_KINDS`` against this CHECK
constraint's allowed set. The test lives in
``backend/tests/test_billing_usage_y9_row3.py::test_kind_check_constraint_matches_module_constants``.

Module-global / cross-worker state audit
────────────────────────────────────────
Pure DDL migration. No in-memory cache, no module-level singleton.
Runs once at ``alembic upgrade head`` time during the offline cutover
window — there is no "every worker" question because every worker
boots after the upgrade and sees the post-create table.

Read-after-write timing audit
─────────────────────────────
No code reads ``billing_usage_events`` until the Y9 row 3 emitter
plumbing in ``backend.billing_usage`` (this commit) and the
``/api/v1/admin/usage/breakdown`` endpoint (this commit). Both ship
in the same commit as the migration, so there is no observable
ordering between the schema and the readers.

Production readiness gate
─────────────────────────
* No new Python / OS package — production image needs no rebuild.
* New ``billing_usage_events`` table added to migrator's
  ``TABLES_IN_ORDER`` (no FK on it from any other table — placement
  near the ``token_usage`` row keeps related billing tables
  co-located in the dump).
* Production status after this commit: **dev-only**. Next gate is
  ``deployed-active`` — operator runs ``alembic upgrade head`` on the
  prod PG instance, then any subsequent LLM call / workflow_run
  completion / workspace-GC sweep starts populating the table
  automatically.

Revision ID: 0039
Revises: 0038
Create Date: 2026-04-26
"""
from __future__ import annotations

from alembic import op


revision = "0039"
down_revision = "0038"
branch_labels = None
depends_on = None


_CREATE_TABLE = """
CREATE TABLE IF NOT EXISTS billing_usage_events (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    occurred_at         REAL NOT NULL,
    tenant_id           TEXT NOT NULL DEFAULT 't-default',
    project_id          TEXT NOT NULL DEFAULT 'p-default-default',
    kind                TEXT NOT NULL,
    model               TEXT,
    input_tokens        INTEGER,
    output_tokens       INTEGER,
    cache_read_tokens   INTEGER,
    cache_create_tokens INTEGER,
    workflow_run_id     TEXT,
    workflow_kind       TEXT,
    workflow_status     TEXT,
    cost_usd            REAL NOT NULL DEFAULT 0.0,
    quantity            REAL NOT NULL DEFAULT 1.0,
    metadata_json       TEXT NOT NULL DEFAULT '{}',
    CHECK (kind IN ('llm_call', 'workflow_run', 'workspace_gb_hour'))
)
"""


_INDEXES = (
    "CREATE INDEX IF NOT EXISTS idx_billing_usage_events_tenant_project_time "
    "ON billing_usage_events(tenant_id, project_id, occurred_at)",
    "CREATE INDEX IF NOT EXISTS idx_billing_usage_events_tenant_kind_time "
    "ON billing_usage_events(tenant_id, kind, occurred_at)",
)


def upgrade() -> None:
    bind = op.get_bind()
    bind.exec_driver_sql(_CREATE_TABLE)
    for stmt in _INDEXES:
        bind.exec_driver_sql(stmt)


def downgrade() -> None:
    bind = op.get_bind()
    for idx in (
        "idx_billing_usage_events_tenant_kind_time",
        "idx_billing_usage_events_tenant_project_time",
    ):
        bind.exec_driver_sql(f"DROP INDEX IF EXISTS {idx}")
    bind.exec_driver_sql("DROP TABLE IF EXISTS billing_usage_events")
