"""W14.10 — ``web_sandbox_instances`` table for cross-worker preview state.

Lays the persistent home for the W14 epic's per-workspace
``omnisight-web-preview`` sidecar bookkeeping.  Today
:class:`backend.web_sandbox.WebSandboxManager` keeps a per-uvicorn-worker
``dict[workspace_id → WebSandboxInstance]`` plus an ``RLock`` — fine for
the dev path (one worker, one operator) but does not survive uvicorn
worker restarts and forces the W14.5 idle reaper to operate only on the
sandboxes the *same* worker launched.  Production runs ``uvicorn
--workers N`` so a sidecar launched on worker A is invisible to the
W14.5 reaper running on worker B.

Row boundary
────────────
W14.10 owns:

  1. The ``web_sandbox_instances`` table (this file).
  2. The migrator ``TABLES_IN_ORDER`` + ``TABLES_WITH_IDENTITY_ID`` updates
     (sibling edit, same row).
  3. The SQLite parity CREATE TABLE in :mod:`backend.db` (sibling edit,
     same row) so dev-mode ``backend.db.init`` produces the same shape.

W14.10 explicitly does NOT own:

  - The :class:`WebSandboxManager` swap from in-memory cache to
    PG-backed reads (separate row).  The table's role today is:
    a target schema the W14.10-aware launcher will write into in a
    later row, plus the drift-guard locks that keep the schema +
    migrator + SQLite mirror in lock-step.  Until the launcher swap
    lands, the column shape is the contract — no production caller
    INSERTs into the table.

Column rationale
────────────────

* ``id`` (BIGINT GENERATED BY DEFAULT AS IDENTITY on PG / INTEGER
  PRIMARY KEY AUTOINCREMENT on SQLite): one row per *launch attempt*
  for ``workspace_id``.  A workspace whose sidecar dies and restarts
  produces multiple rows — the table is an audit log of every launch
  the cross-worker fleet has issued, not just the live one.  Audit
  history is load-bearing for W14.11 R28 / R30 risk-register triage
  ("how many times in the last 24h did the operator hit the iframe
  panel and trigger a relaunch?").  PK is INTEGER so the migrator's
  ``TABLES_WITH_IDENTITY_ID`` reset logic applies — see the parallel
  edit in this row.

* ``sandbox_id`` (TEXT, NOT NULL): the deterministic
  :func:`backend.web_sandbox.format_sandbox_id` output — ``ws-{12hex}``
  hashed from ``workspace_id``.  Same workspace ⇒ same sandbox_id
  across re-launches.  Indexed (non-unique) so the W14.3 CF Tunnel
  ingress rule lookups (``preview-{sandbox_id}.{tunnel_host}``) can
  resolve to the *current* live row in O(log n).

* ``workspace_id`` (TEXT, NOT NULL): operator-supplied workspace key.
  The partial UNIQUE index below enforces "at most one live sidecar
  per workspace" *across all uvicorn workers* — this is the cross-
  worker invariant W14.10 exists to deliver.  Also indexed via the
  partial UNIQUE so ``GET /web-sandbox/preview/{workspace_id}`` is
  cheap.

* ``started_at`` (DOUBLE PRECISION / REAL, NOT NULL): POSIX epoch
  seconds when the launcher emitted ``docker run``.  Maps 1:1 to
  :attr:`WebSandboxInstance.started_at` once the launcher wires up.
  NOT NULL because every row exists *because* a launch attempt was
  made — there is no "row exists but sandbox never launched" state
  (failed-pre-docker is recorded as ``status='failed'`` with a
  ``started_at`` of the same launch-attempt timestamp).

* ``ingress_url`` (TEXT, NULLable): the W14.3 CF Tunnel public URL
  (``https://preview-{sandbox_id}.{tunnel_host}``) when the
  :class:`backend.cf_ingress.CFIngressManager` is wired in;
  ``NULL`` when launching against the W14.2 host-port path
  (``http://127.0.0.1:{host_port}/``).  The host-port URL is a
  derived value (``host`` + ``host_port``) so it's not stored — the
  ingress URL is the only one whose shape can't be reconstructed
  from other columns.

* ``status`` (TEXT, NOT NULL, CHECKed): one of the six
  :class:`backend.web_sandbox.WebSandboxStatus` enum values.  CHECK
  byte-equals the enum's ``.value`` strings; the drift-guard test
  re-derives the CHECK from the enum to fail red on rename.

* ``last_request_at`` (DOUBLE PRECISION / REAL, NOT NULL): bumped
  every time the W14.6 frontend touches ``/web-sandbox/preview/{ws}/touch``
  AND every time an operator click hits the launcher; the W14.5 idle
  reaper reads this to decide what to collect.  Indexed via
  ``idx_web_sandbox_instances_idle`` so the reaper's
  ``WHERE status IN ('running','installing') AND
        last_request_at < now() - 1800`` scan stays cheap.

* ``killed_at`` (DOUBLE PRECISION / REAL, NULLable): POSIX epoch
  seconds when the manager's ``stop()`` ran; ``NULL`` while the row
  is still in a non-terminal status.  Maps to
  :attr:`WebSandboxInstance.stopped_at`.  Named ``killed_at`` per
  the W14.10 row spec (the W14 row literally says "killed_at" — the
  in-memory class field is ``stopped_at`` for historical reasons,
  but the persistent schema follows the row spec verbatim so the
  W14.11 risk-register query templates can grep for ``killed_at``
  unambiguously).

* ``killed_reason`` (TEXT, NULLable): one of ``idle_timeout``
  (W14.5), ``operator_request``, ``cgroup_oom`` (W14.9), and any
  future explicit reason the launcher records.  Free-form string
  rather than enum-CHECKed because the literals are owned by
  multiple sibling rows (W14.5 / W14.9) and a CHECK clause here
  would force a multi-row PR for any new reason.  The drift-guard
  test asserts the *current* literal set still matches the row's
  documented vocabulary.

* ``created_at`` / ``updated_at`` (DOUBLE PRECISION / REAL, NOT NULL):
  bookkeeping triplet matching ``oauth_tokens`` / ``llm_credentials`` /
  ``git_accounts``.  POSIX seconds; caller sets both at INSERT and
  bumps ``updated_at`` on every UPDATE.

* ``version`` (INTEGER, NOT NULL DEFAULT 0): optimistic-lock counter,
  same J2 / Q.7 lineage every other table ships day-1.  The future
  launcher swap will use ``If-Match: version=N`` against this column
  to keep two workers concurrently mutating the same row from
  clobbering each other's last-write.

Indices
───────

* **Partial UNIQUE on ``workspace_id`` WHERE status NOT IN ('stopped',
  'failed')** — the cross-worker invariant.  Two workers racing to
  launch the same workspace will both attempt INSERT; PG / SQLite
  reject the loser with a UNIQUE-violation, which the launcher
  catches and folds into idempotent recovery (read back the existing
  row).  Terminal rows (``stopped`` / ``failed``) are exempt so the
  audit history can keep N old rows for the same workspace alongside
  the one live row.

* **``(status, last_request_at)``** — shapes the W14.5 idle reaper's
  scan.  ``status`` is left-most because the reaper filters first by
  "non-terminal" then by age.

* **``sandbox_id``** — non-unique; supports W14.3 CF ingress lookup
  by hostname (the inverse mapping from public URL back to row).

Why the table holds *audit history*, not just current state
───────────────────────────────────────────────────────────
The trade-off is "fewer rows, simpler UPSERT" vs "complete audit
trail for triage".  W14.11's R28-R30 risk register specifically
needs the trail: "how many launches in the last hour did
``cgroup_oom`` kill?" / "how often does the operator manually kill
a sandbox before the W14.5 idle reaper would have?"  Both questions
are unanswerable if every relaunch overwrites the previous row.
INTEGER IDENTITY PK + partial-UNIQUE-on-live shape gives both
properties: cheap "find the live row" + complete history of the
killed ones.

Module-global / cross-worker state audit
────────────────────────────────────────
Pure DDL migration — no module-level state, no in-memory cache.
Every worker reads the same DDL state from PG / SQLite so the table
is visible atomically post-commit.  **Answer #1** of SOP §1 — every
worker reads the same DDL state from the same DB.

The TABLE itself is the cross-worker coordination primitive: once
the launcher swap lands, the partial-UNIQUE index becomes the
serialiser that picks one winner among racing concurrent launches
across the worker fleet.  That's the SOP §1 **answer #2** for the
W14.2 launcher row's TODO ("PG/docker coordination") — but landing
the schema is W14.10's job; landing the launcher swap is a separate
row.

Read-after-write timing audit
─────────────────────────────
The CREATE TABLE happens inside the alembic upgrade transaction.
``scripts/deploy.sh`` closes the asyncpg pool before alembic upgrade
and reopens it after, so runtime workers never see a half-shaped
schema.  No concurrent writer exists during the migration window.

Production readiness gate
─────────────────────────
* No new Python / OS package — production image needs no rebuild.
  The migration uses only SQL primitives already supported by the
  asyncpg + psycopg2 baseline (Phase-3 G4) and aiosqlite.
* New table added — ``scripts/migrate_sqlite_to_pg.py::TABLES_IN_ORDER``
  is updated in this same row to include ``web_sandbox_instances``
  (replays after no other table because no FK; placed near the end
  with the other operational tables).  PK is INTEGER IDENTITY so the
  table IS in ``TABLES_WITH_IDENTITY_ID`` (sequence reset after
  cutover).  The drift guard ``test_migrator_schema_coverage``
  enforces both.
* SQLite dev parity: :mod:`backend.db`'s ``_SCHEMA`` constant
  receives the same CREATE TABLE so ``backend.db.init`` (the dev
  bootstrap path) produces a column-byte-identical table.  The
  ``test_migrator_schema_coverage::test_alembic_pg_matches_sqlite_column_by_column``
  PG-mode test catches any drift between the two halves.
* Production status of THIS commit: **dev-only**.  Next gate:
  ``deployed-inactive`` once the alembic chain (… → 0058 → 0057 → 0059)
  is run against prod PG.  ``deployed-active`` requires the
  WebSandboxManager swap (separate row) to start writing rows.

Chain ordering
──────────────
``down_revision`` is set to ``"0057"`` — chains AFTER the AS.2.2
``oauth_tokens`` table, which is currently the most recent leaf in
the auth/user chain (0058 → 0057 in chronological landing order,
despite the numeric inversion — see 0057's docstring for the
rationale).  The AB-track chain (``0058 → 0181 → 0183 / 0184 → 0185``)
is a separate lineage and remains unchanged; appending here keeps
the existing multi-head shape stable.

Revision ID: 0059
Revises: 0057
Create Date: 2026-05-03
"""
from __future__ import annotations

from alembic import op


revision = "0059"
down_revision = "0057"
branch_labels = None
depends_on = None


# ─── Status enum literals ────────────────────────────────────────────────
# MUST byte-equal :class:`backend.web_sandbox.WebSandboxStatus`.value.
# Sorted alphabetically so the CHECK clause is reproducible across
# both dialects and the drift-guard test can string-match.
_STATUS_VALUES_SQL = (
    "'failed','installing','pending','running','stopped','stopping'"
)


# ─── PG branch ───────────────────────────────────────────────────────────


# JSONB / DOUBLE PRECISION conventions match the ``billing_usage_events``
# (alembic 0039) parent template.  ``IF NOT EXISTS`` is belt+braces
# against operator hand-creation out of band.  ``BIGINT GENERATED BY
# DEFAULT AS IDENTITY`` is the Phase-3 G4 PG idiom for INTEGER PK
# + IDENTITY (legacy SQLite rendered ``INTEGER PRIMARY KEY AUTOINCREMENT``;
# the migrator's TABLES_WITH_IDENTITY_ID sequence-restart logic resets
# the IDENTITY after replay).
_PG_CREATE_TABLE = (
    "CREATE TABLE IF NOT EXISTS web_sandbox_instances (\n"
    "    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n"
    "    sandbox_id        TEXT NOT NULL,\n"
    "    workspace_id      TEXT NOT NULL,\n"
    "    started_at        DOUBLE PRECISION NOT NULL,\n"
    "    ingress_url       TEXT,\n"
    "    status            TEXT NOT NULL\n"
    f"                            CHECK (status IN ({_STATUS_VALUES_SQL})),\n"
    "    last_request_at   DOUBLE PRECISION NOT NULL,\n"
    "    killed_at         DOUBLE PRECISION,\n"
    "    killed_reason     TEXT,\n"
    "    created_at        DOUBLE PRECISION NOT NULL,\n"
    "    updated_at        DOUBLE PRECISION NOT NULL,\n"
    "    version           INTEGER NOT NULL DEFAULT 0\n"
    ")"
)

# Cross-worker invariant: at most one live sidecar per workspace.
# Terminal rows (stopped / failed) are exempt so the audit history can
# accumulate without colliding with the live row.  Two workers racing
# the same workspace's launch both attempt INSERT; PG rejects the loser
# with unique_violation, which the launcher catches and folds into
# idempotent "read back the existing row" recovery.
_PG_INDEX_LIVE_WORKSPACE = (
    "CREATE UNIQUE INDEX IF NOT EXISTS idx_web_sandbox_instances_workspace_live "
    "ON web_sandbox_instances (workspace_id) "
    "WHERE status NOT IN ('stopped', 'failed')"
)

# W14.5 idle reaper scan: "non-terminal rows whose last_request_at is
# older than now() - idle_timeout".  status is left-most because the
# reaper filters first by "non-terminal" then by age.
_PG_INDEX_IDLE = (
    "CREATE INDEX IF NOT EXISTS idx_web_sandbox_instances_idle "
    "ON web_sandbox_instances (status, last_request_at)"
)

# W14.3 CF Tunnel ingress hostname-to-row lookup.  Non-unique because
# the same sandbox_id repeats across re-launches (sandbox_id is
# deterministic from workspace_id), and we want to find the *latest*
# row for triage.
_PG_INDEX_SANDBOX = (
    "CREATE INDEX IF NOT EXISTS idx_web_sandbox_instances_sandbox "
    "ON web_sandbox_instances (sandbox_id)"
)


# ─── SQLite branch ───────────────────────────────────────────────────────


# Dialect-shifted dev parity: BIGINT IDENTITY → INTEGER PRIMARY KEY
# AUTOINCREMENT (matches ``billing_usage_events`` precedent).  DOUBLE
# PRECISION → REAL.  Otherwise byte-identical column shape.
_SQLITE_CREATE_TABLE = (
    "CREATE TABLE IF NOT EXISTS web_sandbox_instances (\n"
    "    id                INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    sandbox_id        TEXT NOT NULL,\n"
    "    workspace_id      TEXT NOT NULL,\n"
    "    started_at        REAL NOT NULL,\n"
    "    ingress_url       TEXT,\n"
    "    status            TEXT NOT NULL\n"
    f"                            CHECK (status IN ({_STATUS_VALUES_SQL})),\n"
    "    last_request_at   REAL NOT NULL,\n"
    "    killed_at         REAL,\n"
    "    killed_reason     TEXT,\n"
    "    created_at        REAL NOT NULL,\n"
    "    updated_at        REAL NOT NULL,\n"
    "    version           INTEGER NOT NULL DEFAULT 0\n"
    ")"
)

# SQLite supports partial indexes since 3.8.0 (2014); the syntax is
# identical to PG.  Keeps the dev-mode dialect parity tight.
_SQLITE_INDEX_LIVE_WORKSPACE = (
    "CREATE UNIQUE INDEX IF NOT EXISTS idx_web_sandbox_instances_workspace_live "
    "ON web_sandbox_instances (workspace_id) "
    "WHERE status NOT IN ('stopped', 'failed')"
)

_SQLITE_INDEX_IDLE = (
    "CREATE INDEX IF NOT EXISTS idx_web_sandbox_instances_idle "
    "ON web_sandbox_instances (status, last_request_at)"
)

_SQLITE_INDEX_SANDBOX = (
    "CREATE INDEX IF NOT EXISTS idx_web_sandbox_instances_sandbox "
    "ON web_sandbox_instances (sandbox_id)"
)


# ─── upgrade / downgrade ─────────────────────────────────────────────────


def upgrade() -> None:
    conn = op.get_bind()
    if conn.dialect.name == "postgresql":
        conn.exec_driver_sql(_PG_CREATE_TABLE)
        conn.exec_driver_sql(_PG_INDEX_LIVE_WORKSPACE)
        conn.exec_driver_sql(_PG_INDEX_IDLE)
        conn.exec_driver_sql(_PG_INDEX_SANDBOX)
        return

    # SQLite path.  ``CREATE TABLE IF NOT EXISTS`` keeps the migration
    # idempotent on dev DBs that already saw it; the test suite re-binds
    # the migration against a hand-built schema and we want the second
    # call to be a no-op.
    conn.exec_driver_sql(_SQLITE_CREATE_TABLE)
    conn.exec_driver_sql(_SQLITE_INDEX_LIVE_WORKSPACE)
    conn.exec_driver_sql(_SQLITE_INDEX_IDLE)
    conn.exec_driver_sql(_SQLITE_INDEX_SANDBOX)


def downgrade() -> None:
    # Safe drop — until the WebSandboxManager swap to PG-backed reads
    # lands (separate row), this table is empty.  After that, operators
    # must back up ``web_sandbox_instances`` before downgrading or the
    # cross-worker preview state is lost; the table is the only
    # persistent home for sandbox lifecycle history, so a downgrade is
    # by definition a "drop the cross-worker preview tracking entirely"
    # operation that reverts the fleet to per-worker in-memory caches.
    op.execute("DROP INDEX IF EXISTS idx_web_sandbox_instances_sandbox")
    op.execute("DROP INDEX IF EXISTS idx_web_sandbox_instances_idle")
    op.execute(
        "DROP INDEX IF EXISTS idx_web_sandbox_instances_workspace_live"
    )
    op.execute("DROP TABLE IF EXISTS web_sandbox_instances")
