// Generated by SKILL-NUXT (W7 #281).
// Canonical typed wrapper around $fetch that points at the backend
// configured in runtimeConfig. Use this from `<script setup>` rather
// than raw `fetch()` — frontend-vue role anti-patterns forbid direct
// fetch inside component setup (breaks SSR hydration consistency).

export function useBackend() {
  const config = useRuntimeConfig()
  const base = config.backendUrl as string

  return {
    get<T>(path: string, init?: RequestInit): Promise<T> {
      return $fetch<T>(`${base}${path}`, { method: "GET", ...init })
    },
    post<T>(path: string, body: unknown, init?: RequestInit): Promise<T> {
      return $fetch<T>(`${base}${path}`, {
        method: "POST",
        body,
        ...init,
      })
    },
    put<T>(path: string, body: unknown, init?: RequestInit): Promise<T> {
      return $fetch<T>(`${base}${path}`, {
        method: "PUT",
        body,
        ...init,
      })
    },
    del<T>(path: string, init?: RequestInit): Promise<T> {
      return $fetch<T>(`${base}${path}`, { method: "DELETE", ...init })
    },
  }
}
