// Generated by SKILL-NEXTJS (W6 #280).
// Catch-all proxy to the OmniSight backend. Complements the
// next.config.mjs rewrite — this handler covers methods that
// rewrites do not handle cleanly (e.g. streaming responses).

import { NextRequest, NextResponse } from "next/server"

export const runtime = "nodejs"

async function forward(req: NextRequest, slug: string[]) {
  const backend = process.env.BACKEND_URL || "http://localhost:8000"
  const url = `${backend}/api/v1/${slug.join("/")}${req.nextUrl.search}`
  const init: RequestInit = {
    method: req.method,
    headers: req.headers,
    body: ["GET", "HEAD"].includes(req.method) ? undefined : await req.text(),
  }
  const upstream = await fetch(url, init)
  return new NextResponse(upstream.body, {
    status: upstream.status,
    headers: upstream.headers,
  })
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ slug: string[] }> }) {
  return forward(req, (await ctx.params).slug)
}
export async function POST(req: NextRequest, ctx: { params: Promise<{ slug: string[] }> }) {
  return forward(req, (await ctx.params).slug)
}
export async function PUT(req: NextRequest, ctx: { params: Promise<{ slug: string[] }> }) {
  return forward(req, (await ctx.params).slug)
}
export async function DELETE(req: NextRequest, ctx: { params: Promise<{ slug: string[] }> }) {
  return forward(req, (await ctx.params).slug)
}
