"use client"

// Generated by SKILL-NEXTJS (W6 #280).
// Client Component — only needed for interactivity. Pure data reads
// belong in the parent Server Component, per W3 frontend-react role.

import { useState } from "react"

export function Counter({ initial = 0 }: { initial?: number }) {
  const [count, setCount] = useState(initial)

  return (
    <section aria-labelledby="counter-heading">
      <h2 id="counter-heading">Counter</h2>
      <button
        type="button"
        onClick={() => setCount((n) => n + 1)}
        aria-label="increment counter"
      >
        Count: {count}
      </button>
    </section>
  )
}
