"use client"

// Generated by SKILL-NEXTJS (W6 #280).
// FS.7.4 todo example. State is intentionally component-local; no
// module-global cache is introduced by the generated app.

import type { FormEvent } from "react"
import { useMemo, useState } from "react"

type Todo = {
  id: string
  title: string
  done: boolean
}

type TodoAppProps = {
  initialTodos?: Todo[]
}

export function TodoApp({ initialTodos = [] }: TodoAppProps) {
  const [todos, setTodos] = useState<Todo[]>(initialTodos)
  const [title, setTitle] = useState("")

  const remaining = useMemo(
    () => todos.filter((todo) => !todo.done).length,
    [todos],
  )

  function addTodo(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    const trimmed = title.trim()
    if (!trimmed) return

    setTodos((current) => [
      ...current,
      {
        id: `todo-${Date.now()}-${current.length}`,
        title: trimmed,
        done: false,
      },
    ])
    setTitle("")
  }

  function toggleTodo(id: string) {
    setTodos((current) =>
      current.map((todo) =>
        todo.id === id ? { ...todo, done: !todo.done } : todo,
      ),
    )
  }

  function deleteTodo(id: string) {
    setTodos((current) => current.filter((todo) => todo.id !== id))
  }

  return (
    <section aria-labelledby="todo-list-heading">
      <h2 id="todo-list-heading">Tasks</h2>
      <p aria-live="polite">{remaining} remaining</p>

      <form onSubmit={addTodo} aria-label="Add todo">
        <label htmlFor="todo-title">New task</label>
        <input
          id="todo-title"
          name="title"
          value={title}
          onChange={(event) => setTitle(event.target.value)}
          placeholder="Follow up with beta users"
        />
        <button type="submit">Add</button>
      </form>

      <ul>
        {todos.map((todo) => (
          <li key={todo.id}>
            <label>
              <input
                type="checkbox"
                checked={todo.done}
                onChange={() => toggleTodo(todo.id)}
              />
              <span>{todo.title}</span>
            </label>
            <button type="button" onClick={() => deleteTodo(todo.id)}>
              Delete
            </button>
          </li>
        ))}
      </ul>
    </section>
  )
}
