// Generated by SKILL-RUST-CLI (X7 #303).
//
// build.rs — injects the short git SHA into the binary so
// `--version` can print `{name} {semver} ({git_sha})` per the
// cli-tooling role rule #1. Uses std::process only; no external
// build-dependency crate. Falls back to the literal string
// "unknown" when the tree is not a git clone (e.g. release tarball
// build). Also wires cargo rebuild-on-HEAD-change so a new commit
// actually refreshes the string.

use std::process::Command;

fn main() {
    let sha = Command::new("git")
        .args(["rev-parse", "--short=7", "HEAD"])
        .output()
        .ok()
        .filter(|o| o.status.success())
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .map(|s| s.trim().to_string())
        .unwrap_or_else(|| "unknown".to_string());

    println!("cargo:rustc-env=BUILD_GIT_SHA={sha}");
    println!("cargo:rerun-if-changed=.git/HEAD");
    println!("cargo:rerun-if-changed=.git/index");
}
