<!--
Generated by SKILL-NUXT (W7 #281). AUTH=clerk.
Example use of @clerk/nuxt composables. Drop this component into any
page to show Clerk sign-in / signed-in states. Clerk auto-injects
`useAuth()` and `useUser()` when `@clerk/nuxt` is listed in
nuxt.config.ts modules.
-->

<script setup lang="ts">
const { isSignedIn } = useAuth()
const { user } = useUser()
</script>

<template>
  <header role="banner">
    <template v-if="isSignedIn">
      <p>Hello, {{ user?.firstName ?? "there" }}!</p>
      <ClientOnly>
        <SignOutButton />
      </ClientOnly>
    </template>
    <template v-else>
      <ClientOnly>
        <SignInButton mode="modal" />
      </ClientOnly>
    </template>
  </header>
</template>
