// Generated by SKILL-NEXTJS (W6 #280). TRPC=on.
// tRPC fetch adapter — routes /api/trpc/* into the root router.

import { fetchRequestHandler } from "@trpc/server/adapters/fetch"
import { appRouter } from "@/server/trpc"

const handler = (req: Request) =>
  fetchRequestHandler({
    endpoint: "/api/trpc",
    req,
    router: appRouter,
    createContext: () => ({}),
  })

export { handler as GET, handler as POST }
