# OP-1940 / P0.C.2a: Rockchip RK35xx overlay for uvcvideo-xu-dispatcher.
# Toolchain metadata mirrors configs/embedded_catalog/cross-toolchain.yaml:
# rockchip-rk35xx-aarch64-gcc-11 covers rk3576/rk3588 via aarch64-linux-gnu.

ROCKCHIP_RK35XX_TOOLCHAIN_ID ?= "rockchip-rk35xx-aarch64-gcc-11"
ROCKCHIP_RK35XX_TARGET_TRIPLE ?= "aarch64-linux-gnu"
ROCKCHIP_RK35XX_SYSROOT ?= "${RECIPE_SYSROOT}"

COMPATIBLE_MACHINE_rk3576 = "rk3576"
COMPATIBLE_MACHINE_rk3588 = "rk3588"

PACKAGE_ARCH_rk3576 = "${MACHINE_ARCH}"
PACKAGE_ARCH_rk3588 = "${MACHINE_ARCH}"

export ROCKCHIP_RK35XX_TOOLCHAIN_ID
export ROCKCHIP_RK35XX_TARGET_TRIPLE
export ROCKCHIP_RK35XX_SYSROOT

EXTRA_OEMAKE_append_rk3576 = " TOOLCHAIN_ID=${ROCKCHIP_RK35XX_TOOLCHAIN_ID} TARGET_TRIPLE=${ROCKCHIP_RK35XX_TARGET_TRIPLE} SYSROOT=${ROCKCHIP_RK35XX_SYSROOT}"
EXTRA_OEMAKE_append_rk3588 = " TOOLCHAIN_ID=${ROCKCHIP_RK35XX_TOOLCHAIN_ID} TARGET_TRIPLE=${ROCKCHIP_RK35XX_TARGET_TRIPLE} SYSROOT=${ROCKCHIP_RK35XX_SYSROOT}"

TARGET_CFLAGS_append_rk3576 = " --sysroot=${ROCKCHIP_RK35XX_SYSROOT}"
TARGET_CFLAGS_append_rk3588 = " --sysroot=${ROCKCHIP_RK35XX_SYSROOT}"
TARGET_LDFLAGS_append_rk3576 = " --sysroot=${ROCKCHIP_RK35XX_SYSROOT}"
TARGET_LDFLAGS_append_rk3588 = " --sysroot=${ROCKCHIP_RK35XX_SYSROOT}"
