#!/usr/bin/env python3
"""OP-111 - audit configured and documented MCP server inventory."""
from __future__ import annotations

import ast
import re
import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
MCP_INTEGRATION = REPO_ROOT / "backend" / "agents" / "mcp_integration.py"
OUTPUT = REPO_ROOT / "docs" / "operations" / "mcp-inventory.md"
TOKEN_RE = re.compile(r"OMNISIGHT_MCP_[A-Z0-9_]+_TOKEN")


@dataclass(frozen=True)
class ServerRow:
    server_name: str
    purpose: str
    auth_type: str
    status: str


MANUAL_ROWS: tuple[ServerRow, ...] = (
    ServerRow(
        "mcp-atlassian",
        "JIRA issue workflow and comments for runner coordination.",
        "Per-agent Atlassian auth outside backend MCP registry.",
        "Documented in ADR/migration plan; no OMNISIGHT_MCP token alias in backend registry.",
    ),
    ServerRow(
        "mcp-gitlab",
        "GitLab repository/project integration for future fleet workflows.",
        "Per-agent GitLab auth outside backend MCP registry.",
        "Documented in migration plan; no OMNISIGHT_MCP token alias in backend registry.",
    ),
    ServerRow(
        "mcp-gerrit",
        "Custom FastMCP bridge for Gerrit review and submit workflows.",
        "Custom Gerrit credentials; not an Anthropic managed MCP token.",
        "Documented as custom Phase 3 server; no backend registry entry yet.",
    ),
    ServerRow(
        "local tool dispatcher",
        "In-process OmniSight Read/Write/Edit/Bash/tool routing; included for completeness.",
        "Local process permissions; not MCP.",
        "Active local runtime path, not part of mcp_servers payload.",
    ),
)


def _literal_dict(tree: ast.Module, name: str) -> dict[str, str]:
    for node in tree.body:
        if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            if node.target.id == name and isinstance(node.value, ast.Dict):
                return {
                    ast.literal_eval(k): ast.literal_eval(v)
                    for k, v in zip(node.value.keys, node.value.values)
                    if k is not None
                }
    return {}


def _catalog_descriptions(tree: ast.Module) -> dict[str, str]:
    descriptions: dict[str, str] = {}
    for node in tree.body:
        value = None
        if isinstance(node, ast.Assign) and any(isinstance(t, ast.Name) and t.id == "DEFAULT_REMOTE_MCP_CATALOG" for t in node.targets):
            value = node.value
        if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            if node.target.id == "DEFAULT_REMOTE_MCP_CATALOG":
                value = node.value
        if not isinstance(value, ast.Tuple):
            continue
        for entry in value.elts:
            if not isinstance(entry, ast.Call):
                continue
            values = {
                kw.arg: ast.literal_eval(kw.value)
                for kw in entry.keywords
                if kw.arg in {"name", "description"}
            }
            if "name" in values:
                descriptions[values["name"]] = " ".join(values.get("description", "").split())
    return descriptions


def discover_rows(source: Path = MCP_INTEGRATION) -> list[ServerRow]:
    """Read mcp_integration.py and return deterministic inventory rows."""
    text = source.read_text(encoding="utf-8")
    tree = ast.parse(text)
    alias_by_name = _literal_dict(tree, "ENV_TOKEN_VAR_BY_NAME")
    found_tokens = set(TOKEN_RE.findall(text))
    descriptions = _catalog_descriptions(tree)

    rows: list[ServerRow] = []
    for name in sorted(descriptions):
        env_var = alias_by_name.get(name)
        status = (
            f"Configured by backend registry via {env_var}."
            if env_var in found_tokens
            else "Cataloged, but no token alias found by audit."
        )
        rows.append(
            ServerRow(
                name,
                descriptions[name],
                f"Bearer/OAuth token from {env_var}." if env_var else "No token alias found.",
                status,
            )
        )
    rows.extend(MANUAL_ROWS)
    return rows


def _cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def render_markdown(rows: list[ServerRow]) -> str:
    lines = [
        "# MCP Server Inventory",
        "",
        "Generated by `scripts/audit_mcp_servers.py` from `backend/agents/mcp_integration.py` plus documented fleet entries.",
        "",
        "| server name | purpose | auth-type | status |",
        "|---|---|---|---|",
    ] + [
        f"| {_cell(r.server_name)} | {_cell(r.purpose)} | {_cell(r.auth_type)} | {_cell(r.status)} |"
        for r in rows
    ]
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    markdown = render_markdown(discover_rows())
    OUTPUT.write_text(markdown, encoding="utf-8")
    sys.stdout.write(markdown)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
