#!/usr/bin/env python3
"""Build the generated lessons-learned index from per-lesson files."""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
LESSONS_DIR = REPO_ROOT / "docs" / "sop" / "lessons"
INDEX_PATH = REPO_ROOT / "docs" / "sop" / "lessons-learned.md"
TEMPLATE_NAME = "_TEMPLATE.md"
REQUIRED_KEYS = ("id", "ticket", "title", "date", "tags")


@dataclass(frozen=True)
class Lesson:
    path: Path
    frontmatter: dict[str, str]
    body: str

    @property
    def relpath(self) -> str:
        return self.path.relative_to(REPO_ROOT).as_posix()

    @property
    def legacy_lesson(self) -> int | None:
        raw = self.frontmatter.get("legacy_lesson", "").strip()
        return int(raw) if raw.isdigit() else None


def _parse_frontmatter(text: str, path: Path) -> tuple[dict[str, str], str]:
    if not text.startswith("---\n"):
        raise ValueError(f"{path}: missing front-matter block")
    try:
        raw_frontmatter, body = text[4:].split("\n---\n", 1)
    except ValueError as exc:
        raise ValueError(f"{path}: unterminated front-matter block") from exc

    frontmatter: dict[str, str] = {}
    for lineno, line in enumerate(raw_frontmatter.splitlines(), start=2):
        if not line.strip():
            continue
        key, sep, value = line.partition(":")
        if not sep:
            raise ValueError(f"{path}:{lineno}: invalid front-matter line")
        frontmatter[key.strip()] = value.strip()

    missing = [key for key in REQUIRED_KEYS if key not in frontmatter]
    if missing:
        raise ValueError(f"{path}: missing front-matter keys: {', '.join(missing)}")
    return frontmatter, body


def load_lessons(lessons_dir: Path = LESSONS_DIR) -> list[Lesson]:
    lessons: list[Lesson] = []
    for path in sorted(lessons_dir.glob("*.md")):
        if path.name == TEMPLATE_NAME:
            continue
        frontmatter, body = _parse_frontmatter(path.read_text(encoding="utf-8"), path)
        lessons.append(Lesson(path=path, frontmatter=frontmatter, body=body.rstrip() + "\n"))
    return sorted(
        lessons,
        key=lambda lesson: (
            lesson.frontmatter["date"],
            lesson.frontmatter["ticket"],
            lesson.frontmatter["id"],
            lesson.path.name,
        ),
    )


def _legacy_note(lessons: list[Lesson]) -> str:
    numbered = [lesson.legacy_lesson for lesson in lessons if lesson.legacy_lesson is not None]
    if not numbered:
        return ""

    counts = {number: numbered.count(number) for number in sorted(set(numbered))}
    duplicates = [f"L{number}" for number, count in counts.items() if count > 1]
    missing = [f"L{number}" for number in range(1, max(numbered) + 1) if number not in counts]
    if not duplicates and not missing:
        return "Legacy sequential lesson numbers are retained only as migration metadata.\n"

    parts: list[str] = []
    if duplicates:
        parts.append(f"duplicate legacy numbers from concurrent patchsets: {', '.join(duplicates)}")
    if missing:
        parts.append(f"missing legacy numbers: {', '.join(missing)}")
    return (
        "Legacy sequential lesson numbers are retained only as migration metadata; "
        + "; ".join(parts)
        + ".\n"
    )


def render_index(lessons: list[Lesson]) -> str:
    lines = [
        "# Lessons Learned — OmniSight",
        "",
        "<!-- AUTO-GENERATED by scripts/build_lessons_index.py; do not edit by hand. -->",
        "",
        "**Status**: Generated index. Add or edit individual lessons under `docs/sop/lessons/`.",
        "",
        "**Authority**: Owned by operator + AI fleet collectively. Each lesson file must include "
        "`Situation`, `Fix`, `Verification`, and `Generalisation` sections. Vague entries "
        "(`be more careful`, `pay attention`) are auto-rejected by the META retrospective "
        "workflow (per `docs/sop/jira-ticket-conventions.md` §14).",
        "",
        "**How entries land here**:",
        "1. From META retrospective tickets (label `meta:lessons-learned`) once Approved",
        "2. From cross-Phase retrospectives (`docs/retrospectives/YYYY-MM-DD-<slug>.md`) that distil into a generalisable lesson",
        "3. Direct operator append when codifying tribal knowledge",
        "",
        "---",
        "",
        "## Index",
        "",
        "| ID | Date | Ticket | Lesson | Legacy |",
        "|---|---|---|---|---|",
    ]

    for lesson in lessons:
        fm = lesson.frontmatter
        legacy = f"L{lesson.legacy_lesson}" if lesson.legacy_lesson is not None else ""
        lines.append(
            f"| {fm['id']} | {fm['date']} | {fm['ticket']} | "
            f"[{fm['title']}]({lesson.relpath}) | {legacy} |"
        )

    note = _legacy_note(lessons)
    if note:
        lines.extend(["", note.rstrip()])

    lines.extend(["", "---", ""])
    for lesson in lessons:
        fm = lesson.frontmatter
        lines.extend(
            [
                f"## {fm['id']} — {fm['title']} ({fm['date']})",
                "",
                f"Source: [`{lesson.relpath}`]({lesson.relpath})",
                "",
                lesson.body.rstrip(),
                "",
                "---",
                "",
            ]
        )

    return "\n".join(lines).rstrip() + "\n"


def check_standard_sections(lessons: list[Lesson]) -> None:
    for lesson in lessons:
        body = lesson.body
        missing = [
            section
            for section in ("Situation", "Fix", "Verification", "Generalisation")
            if not re.search(rf"^\*\*{section}(?:\*\*|\s*\([^)]*\)\*\*)", body, flags=re.MULTILINE)
        ]
        if missing:
            raise ValueError(f"{lesson.relpath}: missing sections: {', '.join(missing)}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the generated index is stale")
    args = parser.parse_args()

    lessons = load_lessons()
    check_standard_sections(lessons)
    rendered = render_index(lessons)
    if args.check:
        current = INDEX_PATH.read_text(encoding="utf-8")
        if current != rendered:
            raise SystemExit("docs/sop/lessons-learned.md is stale; run scripts/build_lessons_index.py")
        return 0

    INDEX_PATH.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
