"""N8 — Engine-specific SQL linter for Alembic migrations.

Scans every file under ``backend/alembic/versions/`` and flags SQL
patterns that work on SQLite but either fail or silently change
behaviour on Postgres. The intent is *not* to block the PR today (the
baseline migration is full of SQLite idioms and G4 hasn't landed yet);
the intent is to surface each landmine as a GitHub Actions annotation
so a reviewer sees it *before* clicking merge.

Findings are emitted in three channels:

    1. ``::warning file=...,line=...::`` annotations (rendered in the
       PR "Files changed" sidebar).
    2. A markdown table appended to ``$GITHUB_STEP_SUMMARY`` so the
       run page shows an aggregate count per category.
    3. stdout JSON for programmatic consumers.

Stdlib-only: the linter must stay runnable even when a dep upgrade
breaks the very migration it is trying to lint. See N5 / N6 / N7 for
the same self-defense argument.

Exit codes:
    0 — no findings, or findings but we're in advisory (default) mode
    1 — findings and ``--strict`` was passed (post-G4 hard gate)

Usage:

    python3 scripts/check_migration_syntax.py
    python3 scripts/check_migration_syntax.py --strict   # hard gate
    python3 scripts/check_migration_syntax.py --only 0012 0013
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
VERSIONS_DIR = REPO_ROOT / "backend" / "alembic" / "versions"

# Each rule is (key, human label, compiled regex, fix-hint).  Keep the
# regexes targeted — false positives drown the signal, which is the
# whole reason past attempts at "lint every SQL quirk" failed.
#
# The regex corpus is deliberately SQLite-->Postgres oriented; MySQL
# / MSSQL are out of scope for OmniSight.
RULES: list[tuple[str, str, re.Pattern[str], str]] = [
    ("autoincrement",
     "AUTOINCREMENT is SQLite-only",
     re.compile(r"\bAUTOINCREMENT\b", re.IGNORECASE),
     "Use GENERATED BY DEFAULT AS IDENTITY (or SERIAL) on Postgres."),

    ("datetime_now",
     "datetime('now') is SQLite-only",
     re.compile(r"datetime\s*\(\s*'now'", re.IGNORECASE),
     "Use CURRENT_TIMESTAMP or NOW() — both work on SQLite>=3.23 and Postgres."),

    ("strftime",
     "strftime() is SQLite-only",
     re.compile(r"\bstrftime\s*\(", re.IGNORECASE),
     "Prefer EXTRACT(EPOCH FROM ...) or TO_CHAR on Postgres; unify at the "
     "application layer if possible."),

    ("insert_or",
     "INSERT OR ... is SQLite-only conflict syntax",
     re.compile(r"INSERT\s+OR\s+(IGNORE|REPLACE|ABORT|FAIL|ROLLBACK)\b",
                re.IGNORECASE),
     "Use INSERT ... ON CONFLICT (col) DO NOTHING / DO UPDATE on Postgres."),

    ("virtual_table_fts",
     "CREATE VIRTUAL TABLE (FTS5) is SQLite-only",
     re.compile(r"CREATE\s+VIRTUAL\s+TABLE", re.IGNORECASE),
     "FTS5 has no Postgres equivalent; use tsvector + GIN index or "
     "wrap the create in a sqlite-dialect guard."),

    ("pragma",
     "PRAGMA statements are SQLite-only",
     re.compile(r"\bPRAGMA\s+[a-z_]+", re.IGNORECASE),
     "PRAGMA is a SQLite-specific meta-statement. Skip / guard by dialect."),

    ("begin_immediate",
     "BEGIN IMMEDIATE is SQLite-only",
     re.compile(r"\bBEGIN\s+IMMEDIATE\b", re.IGNORECASE),
     "Postgres uses default transactions; drop IMMEDIATE or use "
     "SELECT ... FOR UPDATE for lock semantics."),

    ("text_pk_as_integer",
     "INTEGER PRIMARY KEY without AUTOINCREMENT relies on SQLite rowid aliasing",
     re.compile(r"INTEGER\s+PRIMARY\s+KEY\b(?!\s+AUTOINCREMENT)", re.IGNORECASE),
     "On Postgres this just creates an INTEGER column — make intent "
     "explicit with GENERATED BY DEFAULT AS IDENTITY or BIGSERIAL."),
]


def _scan_file(path: Path) -> list[dict]:
    """Scan one migration file; return a list of findings.

    Each finding = {file, line, rule, label, snippet, hint}."""
    findings: list[dict] = []
    try:
        source = path.read_text(encoding="utf-8")
    except OSError as exc:
        # We report but do not raise — a permission issue should not
        # mask everything else.
        return [{"file": str(path.relative_to(REPO_ROOT)),
                 "line": 0, "rule": "read-error",
                 "label": f"cannot read: {exc}",
                 "snippet": "", "hint": ""}]

    lines = source.splitlines()
    for rule_key, label, pattern, hint in RULES:
        for match in pattern.finditer(source):
            # Convert byte offset → line number (1-indexed).
            line_no = source.count("\n", 0, match.start()) + 1
            snippet = lines[line_no - 1].strip() if line_no <= len(lines) else ""
            findings.append({
                "file": str(path.relative_to(REPO_ROOT)),
                "line": line_no,
                "rule": rule_key,
                "label": label,
                "snippet": snippet[:160],
                "hint": hint,
            })
    return findings


def _emit_annotations(findings: list[dict]) -> None:
    """Emit `::warning ...` annotations. No-op outside CI."""
    if os.environ.get("GITHUB_ACTIONS") != "true":
        return
    for f in findings:
        # Collapse the snippet to a single safe line for annotation text.
        msg = f"{f['label']} — {f['hint']}"
        print(f"::warning file={f['file']},line={f['line']},"
              f"title=engine-specific SQL ({f['rule']})::{msg}")


def _emit_summary(findings: list[dict]) -> None:
    """Append a markdown table to the job summary so the run page
    shows an at-a-glance count per rule per file."""
    summary_path = os.environ.get("GITHUB_STEP_SUMMARY")
    if not summary_path:
        return

    by_rule: dict[str, int] = {}
    by_file: dict[str, int] = {}
    for f in findings:
        by_rule[f["rule"]] = by_rule.get(f["rule"], 0) + 1
        by_file[f["file"]] = by_file.get(f["file"], 0) + 1

    lines: list[str] = []
    lines.append("## N8 engine-specific SQL scan")
    lines.append("")
    if not findings:
        lines.append("_No findings. Migrations look Postgres-portable._")
    else:
        lines.append(f"**Total findings:** {len(findings)}")
        lines.append("")
        lines.append("| Rule | Count |")
        lines.append("|---|---|")
        for rule, n in sorted(by_rule.items(), key=lambda x: -x[1]):
            lines.append(f"| `{rule}` | {n} |")
        lines.append("")
        lines.append("| File | Count |")
        lines.append("|---|---|")
        for fname, n in sorted(by_file.items(), key=lambda x: -x[1]):
            lines.append(f"| `{fname}` | {n} |")

    with open(summary_path, "a", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--strict", action="store_true",
                    help="exit 1 on any finding (post-G4 hard gate)")
    ap.add_argument("--only", nargs="+", default=None,
                    help="restrict scan to revision IDs, e.g. --only 0012 0013")
    args = ap.parse_args()

    if not VERSIONS_DIR.is_dir():
        print(f"error: no versions dir at {VERSIONS_DIR}", file=sys.stderr)
        return 2

    targets: list[Path] = []
    for entry in sorted(VERSIONS_DIR.glob("*.py")):
        if args.only and entry.stem.split("_", 1)[0] not in args.only:
            continue
        targets.append(entry)

    findings: list[dict] = []
    for f in targets:
        findings.extend(_scan_file(f))

    _emit_annotations(findings)
    _emit_summary(findings)
    print(json.dumps({"total": len(findings), "findings": findings}, indent=2))

    if args.strict and findings:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
