#!/usr/bin/env python3
"""Z.7.7 / Z.7.9 — CI budget guard for the nightly LLM live-test run.

Usage:
    python scripts/ci_budget_guard.py <pytest-json-report.json>

Reads the pytest-json-report JSON (generated by ``pytest --json-report``)
and estimates the total USD cost of the run using:
  - Per-model token pricing constants (worst-case upper bound)
  - Test count × max-tokens-per-test × cost-per-token

Exits 0 when estimated cost <= OMNISIGHT_CI_MAX_COST_USD (default $0.50).
Exits 1 and prints a budget-exceeded diagnostic when the estimate is over.

Why static estimation rather than actual token counts:
  The pytest-json-report does not capture LLM token counts — those live
  inside the provider SDK response objects and are not captured by the
  test reporter. We could instrument each test to write token counts to a
  temp file, but that adds fragile fixture coupling to every test class.
  Instead we use a conservative worst-case estimate:
    tokens_per_test × tests_run × highest_unit_price_among_CI_models

  The guard fires on "could cost more than $0.50 if every call maxed out
  tokens" rather than "definitely cost more than $0.50". In practice the
  live tests are tiny tool-call probes (< 300 output tokens each), so the
  actual spend is well under 10 % of the guard threshold.

  Z.7.9 (dedicated budget guard row) will add per-call token tracking via
  a LangChain callback and replace this static estimator.
"""

from __future__ import annotations

import json
import os
import sys

# ── Pricing constants (USD per 1 000 000 tokens, worst-case for CI models) ──
# Anthropic claude-3-haiku-20240307 — cheapest Haiku tier
_ANTHROPIC_INPUT_PER_MTK = 0.25
_ANTHROPIC_OUTPUT_PER_MTK = 1.25
# OpenAI gpt-3.5-turbo
_OPENAI_INPUT_PER_MTK = 0.50
_OPENAI_OUTPUT_PER_MTK = 1.50
# Google gemini-1.5-flash-latest
_GOOGLE_INPUT_PER_MTK = 0.075
_GOOGLE_OUTPUT_PER_MTK = 0.30

# Conservative per-test token budget: each live test sends ~1 round-trip
# with a short system + user prompt (≤300 input) and expects a tool-call
# response (≤200 output). Use 2× buffer for the multi-turn / streaming
# tests that make two round-trips.
_MAX_INPUT_TOKENS_PER_TEST = 600
_MAX_OUTPUT_TOKENS_PER_TEST = 400

# Budget threshold — override with OMNISIGHT_CI_MAX_COST_USD env var.
_DEFAULT_BUDGET_USD = 0.50


def _highest_input_cost() -> float:
    return max(_ANTHROPIC_INPUT_PER_MTK, _OPENAI_INPUT_PER_MTK, _GOOGLE_INPUT_PER_MTK)


def _highest_output_cost() -> float:
    return max(_ANTHROPIC_OUTPUT_PER_MTK, _OPENAI_OUTPUT_PER_MTK, _GOOGLE_OUTPUT_PER_MTK)


def estimate_cost(tests_run: int) -> float:
    """Return worst-case USD cost for ``tests_run`` actual (non-skipped) tests."""
    input_cost = (_MAX_INPUT_TOKENS_PER_TEST / 1_000_000) * _highest_input_cost() * tests_run
    output_cost = (_MAX_OUTPUT_TOKENS_PER_TEST / 1_000_000) * _highest_output_cost() * tests_run
    return input_cost + output_cost


def _count_tests(report_path: str) -> tuple[int, int, int]:
    """Return (tests_run, tests_passed, tests_skipped) from the JSON report.

    ``tests_run`` excludes skipped tests — those don't hit the provider APIs.
    """
    try:
        with open(report_path, encoding="utf-8") as f:
            data = json.load(f)
    except FileNotFoundError:
        print(f"[budget-guard] WARNING: report not found at {report_path!r} — assuming 0 tests ran")
        return 0, 0, 0
    except json.JSONDecodeError as exc:
        print(f"[budget-guard] WARNING: could not parse report JSON: {exc} — assuming 0 tests ran")
        return 0, 0, 0

    # pytest-json-report format: {"tests": [...], "summary": {"passed": N, "skipped": M, ...}}
    summary = data.get("summary", {})
    passed = int(summary.get("passed", 0))
    failed = int(summary.get("failed", 0))
    skipped = int(summary.get("skipped", 0))
    tests_run = passed + failed  # skipped tests don't call the API
    return tests_run, passed, skipped


def main() -> int:
    if len(sys.argv) < 2:
        print("Usage: ci_budget_guard.py <pytest-json-report.json>", file=sys.stderr)
        return 2

    report_path = sys.argv[1]
    budget = float(os.environ.get("OMNISIGHT_CI_MAX_COST_USD", str(_DEFAULT_BUDGET_USD)))

    tests_run, tests_passed, tests_skipped = _count_tests(report_path)
    estimated = estimate_cost(tests_run)

    print(f"[budget-guard] tests_run={tests_run}  tests_passed={tests_passed}  tests_skipped={tests_skipped}")
    print(f"[budget-guard] worst-case estimated cost: ${estimated:.4f} USD  (budget: ${budget:.2f} USD)")

    if estimated > budget:
        print(
            f"[budget-guard] FAIL — estimated cost ${estimated:.4f} exceeds budget ${budget:.2f}. "
            "Use cheaper CI models, reduce token limits, or raise OMNISIGHT_CI_MAX_COST_USD.",
            file=sys.stderr,
        )
        # Write GitHub Actions annotation
        print(f"::error::LLM live-test budget exceeded: estimated ${estimated:.4f} > limit ${budget:.2f}")
        return 1

    print(f"[budget-guard] PASS — estimated cost ${estimated:.4f} is within budget ${budget:.2f}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
