"""G4 #4 (HA-04) — SQLite → PostgreSQL data migration with audit_log hash chain verification.

Migrates every table in the OmniSight SQLite database to an empty
PostgreSQL database created by ``alembic upgrade head`` against the
same revision (head = 0015 at time of writing). The schema is *not*
touched by this script: Alembic owns DDL, this owns DML.

Why this is its own script and not "just dump + restore":

1.  **Hash-chain preservation is the whole point.** ``audit_log``
    rows carry a per-tenant Merkle-style chain
    (``curr_hash = sha256(prev_hash || canonical(row))``). Any reorder,
    row drop, or float-to-float rewrite of ``ts`` would silently shatter
    tamper-evidence for every downstream row. Off-the-shelf tools
    (``pgloader``, ``sqlite3-to-postgres`` PyPI packages) reorder rows
    by primary key and rewrite types without asking. We walk rows in
    ``ORDER BY id ASC`` and insert them with their exact original id,
    ts, prev_hash, and curr_hash, then re-verify the chain on the
    *target* to prove nothing drifted. See ``verify_hash_chain_in_rows``.

2.  **IDENTITY sequence alignment.** SQLite's ``INTEGER PRIMARY KEY``
    becomes PG ``BIGINT GENERATED BY DEFAULT AS IDENTITY`` via the
    G4 #1 compat shim. Inserting rows with explicit ids does *not*
    advance PG's identity sequence — the next implicit insert would
    collide with id=1. Every migrated table with an auto-id column
    gets ``setval(pg_get_serial_sequence(...), max(id))`` at the end.

3.  **Fail-closed invariants.** Any of the following aborts with a
    non-zero exit code and leaves the target untouched (or at worst
    in the post-``TRUNCATE`` empty state):
      - source audit_log chain broken before we start (exit 3)
      - target has existing non-trivial data and ``--truncate-target``
        was not passed (exit 4)
      - target audit_log chain broken after copy (exit 5 — implies a
        migration bug, never expected)
      - row count mismatch between source and target (exit 6)

Usage::

    # Default: fail if target has any data beyond the Alembic seed row
    python3 scripts/migrate_sqlite_to_pg.py \\
        --source   sqlite:///data/omnisight.db \\
        --target   postgresql+asyncpg://omni:pw@pg-primary:5432/omnisight

    # Wipe the target first (still preserves schema)
    python3 scripts/migrate_sqlite_to_pg.py \\
        --source  data/omnisight.db \\
        --target  postgresql+asyncpg://omni:pw@localhost:5432/omnisight \\
        --truncate-target

    # Dry run: walk every row, compute chain, verify source only.
    python3 scripts/migrate_sqlite_to_pg.py \\
        --source  data/omnisight.db --dry-run

    # Structured output for CI
    python3 scripts/migrate_sqlite_to_pg.py --source ... --target ... --json

Exit codes::

    0  migration completed, hash chain verified on both sides
    1  unexpected error / driver unavailable / connection failure
    2  CLI usage error
    3  source audit_log chain broken BEFORE migration started
    4  target not empty and --truncate-target not set
    5  target audit_log chain broken AFTER migration (corruption bug)
    6  row count mismatch between source and target after copy

This script deliberately keeps its core logic as pure functions so the
contract test suite can exercise the hash-chain walk, insert-SQL
builder, and argparse surface without requiring a real Postgres.
"""

from __future__ import annotations

import argparse
import asyncio
import hashlib
import json
import logging
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from backend.db_url import (  # noqa: E402
    DatabaseURL,
    MalformedURLError,
    UnsupportedURLError,
    parse as parse_db_url,
)

logger = logging.getLogger("migrate_sqlite_to_pg")


# ─────────────────────────────────────────────────────────────────────────
#  Static table-ordering + column metadata.
# ─────────────────────────────────────────────────────────────────────────

#: Migrate ``tenants`` first because ``api_keys``, ``tenant_secrets``,
#: and the ``tenant_egress_*`` tables declare ``REFERENCES tenants(id)``
#: on PG. Everything else has no FK on OmniSight so order is cosmetic,
#: but we still fix it for deterministic logs + CI snapshot diffs.
TABLES_IN_ORDER: tuple[str, ...] = (
    # Tenant root — MUST be first for FK parents below.
    "tenants",
    # Phase 50 baseline business tables.
    "agents",
    "tasks",
    "task_comments",
    "npi_state",
    "artifacts",
    "notifications",
    "handoffs",
    "token_usage",
    "simulations",
    "event_log",
    "episodic_memory",
    "debug_findings",
    "decision_rules",
    # Phase 52+ additions.
    "workflow_runs",
    "workflow_steps",
    # Phase 56-DAG-B plan storage (FK-soft-link: dag_plans.run_id →
    # workflow_runs.id). Placed after workflow_runs so the FK target
    # exists when PG is enforcing constraints during replay.
    "dag_plans",
    # Phase 53 audit log.
    "audit_log",
    # L1 bootstrap wizard state. No FK, independent table. Load-
    # bearing because its rows drive ``missing_required_steps`` on
    # the finalize gate — losing this table forces operators through
    # the wizard again on first login.
    "bootstrap_state",
    # Phase 54 profiles + auto decision log.
    "decision_profiles",
    "auto_decision_log",
    # Prompt versioning (no FK, independent).
    "prompt_versions",
    # IQ-gate runs (no FK; tracks model benchmark outcomes).
    "iq_runs",
    # Phase 55 users/sessions/GitHub app.
    "users",
    # Y1 row 1 (#277, alembic 0032): N-to-M users <-> tenants. FKs
    # ``user_id → users.id`` and ``tenant_id → tenants.id`` (both
    # ON DELETE CASCADE) so it MUST replay after both parents. PK is
    # composite ``(user_id, tenant_id)`` — both TEXT — so NOT in
    # TABLES_WITH_IDENTITY_ID.
    "user_tenant_memberships",
    # Y1 row 2 (#277, alembic 0033): project layer. FKs
    # ``tenant_id → tenants.id`` (CASCADE), ``parent_id → projects.id``
    # (SET NULL, self-FK), ``created_by → users.id`` (SET NULL) so it
    # MUST replay after both ``tenants`` and ``users``.  Self-FK on
    # ``parent_id`` means rows must be ordered topologically within
    # the table dump (parent before children); the migrator's per-row
    # batched insert mode honours sqlite ROWID order — we rely on the
    # backfill row to insert default top-level projects first, which
    # gets natural-order inserted before any nested child.  PK is
    # TEXT (``p-*``) — NOT in TABLES_WITH_IDENTITY_ID.  Placed before
    # ``project_runs`` so the eventual hard FK ``project_runs.project_id
    # → projects.id`` (added in a later Y1 row) replays cleanly.
    "projects",
    # Y1 row 3 (#277, alembic 0034): per-project explicit role
    # bindings. FKs ``user_id → users.id`` (CASCADE) and
    # ``project_id → projects.id`` (CASCADE) so it MUST replay after
    # both ``users`` and ``projects``. Composite PK
    # ``(user_id, project_id)`` is TEXT — NOT in
    # TABLES_WITH_IDENTITY_ID. Empty until Y3 admin REST starts
    # writing project-level role overrides.
    "project_members",
    # Y1 row 4 (#277, alembic 0035): email-keyed tenant invites. FKs
    # ``tenant_id → tenants.id`` (CASCADE) and ``invited_by →
    # users.id`` (SET NULL) so it MUST replay after both ``tenants``
    # and ``users``. PK is the app-generated TEXT ``id`` (``inv-*``);
    # NOT in TABLES_WITH_IDENTITY_ID. Empty until Y2 admin REST
    # ``POST /api/v1/admin/invites`` starts inserting.
    "tenant_invites",
    # Y1 row 5 (#277, alembic 0036): cross-tenant project share.
    # FKs ``project_id → projects.id`` (CASCADE), ``guest_tenant_id
    # → tenants.id`` (CASCADE), ``granted_by → users.id`` (SET NULL)
    # so it MUST replay after ``projects``, ``tenants`` and ``users``.
    # PK is the app-generated TEXT ``id`` (``psh-*``); NOT in
    # TABLES_WITH_IDENTITY_ID. UNIQUE (project_id, guest_tenant_id)
    # forbids two concurrent role grants on the same (project, guest
    # tenant) pair. Empty until Y3 admin REST starts inserting.
    "project_shares",
    # MFA tables — all have FK ``user_id → users.id`` so they MUST
    # come after users in the replay order.
    "user_mfa",
    "mfa_backup_codes",
    # Password-history K-series — same FK parent as above.
    "password_history",
    # AS.2.2 (alembic 0057): per-(user, provider) OAuth credential vault.
    # FK ``user_id → users.id`` (CASCADE) so it MUST replay after
    # ``users``.  Composite PK ``(user_id, provider)`` is two TEXT
    # columns — NOT in TABLES_WITH_IDENTITY_ID below.  Empty until
    # AS.6.1 OAuth router starts writing rows; the table ships ahead
    # of the router so dev-image schema is one Phase ahead of code.
    "oauth_tokens",
    # FS.1.3 (alembic 0061): tenant-owned DB provisioning registry.
    # FK ``tenant_id → tenants.id`` (CASCADE) so it MUST replay after
    # ``tenants``.  Composite PK ``(tenant_id, provider)`` is TEXT —
    # NOT in TABLES_WITH_IDENTITY_ID.  Stores encrypted connection URL
    # ciphertext only; plaintext DSNs never enter the control-plane DB.
    "provisioned_databases",
    # FS.3.2 (alembic 0062): tenant-owned object storage registry.
    # FK ``tenant_id → tenants.id`` (CASCADE) so it MUST replay after
    # ``tenants``. Composite PK ``(tenant_id, provider)`` is TEXT —
    # NOT in TABLES_WITH_IDENTITY_ID. Bucket names are non-secret
    # provider identifiers; credentials are not stored in this table.
    "provisioned_storage",
    # FS.8.3 (alembic 0063): tenant-owned Stripe billing registry.
    # FK ``tenant_id → tenants.id`` (CASCADE) so it MUST replay after
    # ``tenants``. Composite PK ``(tenant_id, provider)`` is TEXT —
    # NOT in TABLES_WITH_IDENTITY_ID. Stores Stripe customer /
    # subscription identifiers and current subscription status for
    # FS.8.4 state sync; no API keys or webhook secrets live here.
    "provisioned_billing",
    # SC.10.1 (alembic 0064): per-user data-subject request workflow
    # queue. FKs ``tenant_id → tenants.id`` and ``user_id → users.id``
    # (both CASCADE) so it MUST replay after both parents. PK is the
    # app-generated TEXT ``id`` (``dsar-*``); NOT in
    # TABLES_WITH_IDENTITY_ID. Empty until SC.10.2-SC.10.5 start writing
    # access / erasure / portability workflow rows.
    "dsar_requests",
    # SC.11.1 (alembic 0065): tenant-owned compliance evidence bundle
    # queue/catalog. FKs ``tenant_id → tenants.id`` (CASCADE) and
    # ``requested_by → users.id`` (SET NULL) so it MUST replay after
    # both parents. PK is the app-generated TEXT ``id`` (``ceb-*``);
    # NOT in TABLES_WITH_IDENTITY_ID. Empty until SC.11.2-SC.11.4 start
    # collecting SOC 2 / ISO 27001 evidence and writing export rows.
    "compliance_evidence_bundles",
    # KS.1.10 (alembic 0106): envelope-encryption persistence tables.
    # ``kms_keys`` has no FK and must replay before ``tenant_deks`` /
    # ``kek_rotations`` because both reference it. ``tenant_deks``,
    # ``decryption_audits``, and ``spend_thresholds`` FK to tenants;
    # decryption rows also carry user_id as audit metadata but do not
    # enforce a users FK so deleted-user forensics remain readable.
    # All five PKs are TEXT or tenant_id TEXT, so none belong in
    # TABLES_WITH_IDENTITY_ID.
    "kms_keys",
    "tenant_deks",
    "decryption_audits",
    "spend_thresholds",
    "kek_rotations",
    # KS.2.11 (alembic 0107): Tier 2 CMEK persistence. All three FK
    # to ``tenants``; ``tier_assignments`` and ``cmek_revoke_events``
    # also FK to ``cmek_configs`` so configs replay first. PKs are
    # TEXT / tenant_id TEXT, so none belong in TABLES_WITH_IDENTITY_ID.
    "cmek_configs",
    "tier_assignments",
    "cmek_revoke_events",
    # KS.4.13 (alembic 0187): LLM firewall review events. FK
    # ``tenant_id -> tenants.id`` (CASCADE) so it MUST replay after
    # tenants. PK is app-generated TEXT ``event_id``; raw input is not
    # present in the table, only ``input_hash`` for review correlation.
    # NOT in TABLES_WITH_IDENTITY_ID.
    "firewall_events",
    "sessions",
    "github_installations",
    # Project runs (alembic 0006).
    "project_runs",
    # User preferences (alembic 0010).
    "user_preferences",
    # API keys (alembic 0011).
    "api_keys",
    # Multi-tenancy extras.
    "tenant_secrets",
    "tenant_egress_policies",
    "tenant_egress_requests",
    # Q.3-SUB-6 (#297, alembic 0021): per-user chat history. No FK but
    # logically owned by ``users.id`` — keep near the user-scoped
    # tables for deterministic replay ordering.
    "chat_messages",
    # Q.6 (#300, alembic 0022): per-user composer drafts (INVOKE bar
    # + workspace chat). 24 h GC sweep; PK is (user_id, slot_key).
    # No FK by design (matches ``chat_messages`` precedent — see
    # migration 0022's docstring for the rationale).
    "user_drafts",
    # ZZ.B2 #304-2 (alembic 0026): per-user chat-session metadata for
    # the left-sidebar title (LLM-generated auto_title + optional
    # user_title). PK is (session_id, user_id, tenant_id); upserted
    # on every chat message write.
    "chat_sessions",
    # Phase 5-1 (alembic 0027): one row per forge account
    # (github/gitlab/gerrit/jira). FK ``tenant_id → tenants(id)
    # ON DELETE CASCADE`` so it must replay AFTER tenants. PK is the
    # app-generated TEXT ``id`` (same convention as tenant_secrets);
    # NOT in TABLES_WITH_IDENTITY_ID. Empty until rows 5-2 / 5-5 land.
    "git_accounts",
    # Phase 5b-1 (alembic 0029): one row per LLM-provider credential
    # (anthropic/google/openai/xai/groq/deepseek/together/openrouter/
    # ollama). FK ``tenant_id → tenants(id) ON DELETE CASCADE`` so it
    # must replay AFTER tenants. PK is the app-generated TEXT ``id``
    # (same convention as tenant_secrets / git_accounts); NOT in
    # TABLES_WITH_IDENTITY_ID. Empty until rows 5b-2 / 5b-5 land.
    "llm_credentials",
    # H4a row 2582 (alembic 0030): singleton last-known-good AIMD
    # budget for cold-start carry-over. PK is the fixed TEXT id
    # ``'global'`` (NOT an INTEGER IDENTITY); one row max — no FK.
    # Placed last because it has no dependencies and carrying its
    # row is non-load-bearing (missing row falls back to INIT_BUDGET).
    "adaptive_budget_state",
    # Y9 #285 row 3 (alembic 0039): per-(tenant_id, project_id)
    # billing usage events. Append-only fact table; no FK on it from
    # any other table. PK is INTEGER IDENTITY (in TABLES_WITH_IDENTITY_ID
    # below). Placed near the end with the other operational /
    # observability tables; replay order vs ``token_usage`` doesn't
    # matter since neither table FKs the other.
    "billing_usage_events",
    # BS.1.1 (alembic 0051) — catalog DB schema. Three tables ship
    # together; all three FK ``tenant_id → tenants(id)`` (CASCADE) so
    # they MUST replay after ``tenants``. ``install_jobs.requested_by
    # → users(id)`` (SET NULL) so it ALSO needs ``users`` ahead — both
    # parents are already listed early in this tuple. ``catalog_entries``
    # has NO single-column PK (uniqueness comes from the partial UNIQUE
    # index ``uq_catalog_entries_visible``); ``install_jobs`` and
    # ``catalog_subscriptions`` use TEXT PKs (``ij-…`` / ``sub-…``
    # prefixes) — none are INTEGER IDENTITY, so NOT in
    # TABLES_WITH_IDENTITY_ID below. ``catalog_entries`` replays first
    # because ``install_jobs.entry_id`` references its ``id`` (logical,
    # not enforced as FK) so cutover ordering matches the read-after-
    # write expectation of the BS.7 install pipeline.
    "catalog_entries",
    "install_jobs",
    "catalog_subscriptions",
    # W14.10 (alembic 0059) — per-launch audit log for the
    # ``omnisight-web-preview`` sidecar.  No FK to any other table:
    # ``workspace_id`` is operator-supplied (Y6 worktree key, not a
    # FK target on this DB) and ``sandbox_id`` is deterministic from
    # ``workspace_id`` (no separate identity table).  PK is INTEGER
    # IDENTITY so the table IS in TABLES_WITH_IDENTITY_ID below.
    # Replays at the end with the other operational / audit tables;
    # ordering vs ``billing_usage_events`` doesn't matter since
    # neither table FKs the other.  Empty until the WebSandboxManager
    # swap to PG-backed reads lands (separate row).
    "web_sandbox_instances",
)

#: Tables whose ``id`` is an INTEGER auto-id on SQLite and an IDENTITY
#: sequence on PG. After migrating these we reset the sequence so the
#: next insert doesn't collide with a preserved id.
#:
#: bootstrap_state is NOT here — its PK is ``step`` (TEXT, e.g.
#: 'admin_password_set'), not an integer IDENTITY.
#: user_mfa is NOT here — its PK is ``id`` (TEXT, app-generated).
TABLES_WITH_IDENTITY_ID: tuple[str, ...] = (
    "event_log",
    "audit_log",
    "auto_decision_log",
    "github_installations",
    # 2026-04-20 Phase-3 pre-req F2 additions — five freshly-covered
    # tables whose INTEGER PKs need sequence restart after replay.
    "dag_plans",
    "iq_runs",
    "mfa_backup_codes",
    "password_history",
    "prompt_versions",
    # 2026-04-26 Y9 #285 row 3 (alembic 0039) — billing fact table;
    # PK is BIGINT GENERATED BY DEFAULT AS IDENTITY (compat-shim
    # rewrites SQLite's INTEGER PRIMARY KEY AUTOINCREMENT). Sequence
    # must restart after replay so the next live insert doesn't
    # collide with a preserved id.
    "billing_usage_events",
    # 2026-05-03 W14.10 (alembic 0059) — per-launch audit log for the
    # ``omnisight-web-preview`` sidecar; PK is BIGINT GENERATED BY
    # DEFAULT AS IDENTITY on PG / INTEGER PRIMARY KEY AUTOINCREMENT
    # on SQLite.  Sequence must restart after replay so the next live
    # WebSandboxManager INSERT doesn't collide with a preserved id.
    "web_sandbox_instances",
)

DEFAULT_BATCH_SIZE = 500
DEFAULT_TENANT_ID = "t-default"


# ─────────────────────────────────────────────────────────────────────────
#  Hash chain — mirrored from backend/audit.py so this script does not
#  depend on the async audit module (which pulls in db_context + config).
# ─────────────────────────────────────────────────────────────────────────


def canonical_payload(row: Mapping[str, Any]) -> dict[str, Any]:
    """Return the payload dict that the audit chain hashes.

    The shape matches :func:`backend.audit.log`:

    ``{action, entity_kind, entity_id, before, after, actor}``

    ``before_json`` / ``after_json`` store compact JSON; we parse them
    so the re-hash matches the original (audit.log serialises with
    ``json.dumps(ensure_ascii=False)`` before hashing — feeding back
    the decoded dict gives us an identical canonical form).
    """
    return {
        "action":      row["action"],
        "entity_kind": row["entity_kind"],
        "entity_id":   row["entity_id"] or "",
        "before":      json.loads(row["before_json"] or "{}"),
        "after":       json.loads(row["after_json"] or "{}"),
        "actor":       row["actor"],
    }


def canonical_json(payload: Mapping[str, Any]) -> str:
    """Deterministic JSON encoding used inside the hash input."""
    return json.dumps(
        payload,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
        default=str,
    )


def recompute_hash(prev_hash: str, row: Mapping[str, Any]) -> str:
    """Return the ``curr_hash`` this row SHOULD have given ``prev_hash``.

    Mirrors :func:`backend.audit._hash` plus the ``ts`` round trick used
    by :func:`backend.audit.log`::

        curr = sha256(prev_hash + canonical(payload) + str(round(ts, 6)))
    """
    payload = canonical_payload(row)
    seed = prev_hash + canonical_json(payload) + str(round(row["ts"], 6))
    return hashlib.sha256(seed.encode("utf-8")).hexdigest()


@dataclass(frozen=True)
class ChainBreak:
    """The first audit row where the chain diverges."""

    tenant_id:    str
    row_id:       int
    why:          str            # "prev_hash" | "curr_hash"
    expected:     str
    actual:       str


def verify_hash_chain_in_rows(
    rows: Sequence[Mapping[str, Any]],
) -> tuple[bool, ChainBreak | None]:
    """Walk rows assumed to be one tenant, ordered by id ascending.

    Returns ``(True, None)`` if the chain holds, else
    ``(False, ChainBreak)`` pinned to the first divergent row.

    This is the pure, connection-free version of
    :func:`backend.audit.verify_chain` used by both the source
    pre-flight and the target post-flight checks.
    """
    prev_hash = ""
    for row in rows:
        expected_curr = recompute_hash(prev_hash, row)
        if row["prev_hash"] != prev_hash:
            return False, ChainBreak(
                tenant_id=row.get("tenant_id") or "",
                row_id=row["id"],
                why="prev_hash",
                expected=prev_hash,
                actual=row["prev_hash"] or "",
            )
        if row["curr_hash"] != expected_curr:
            return False, ChainBreak(
                tenant_id=row.get("tenant_id") or "",
                row_id=row["id"],
                why="curr_hash",
                expected=expected_curr,
                actual=row["curr_hash"] or "",
            )
        prev_hash = row["curr_hash"]
    return True, None


# ─────────────────────────────────────────────────────────────────────────
#  SQL builders (pure).
# ─────────────────────────────────────────────────────────────────────────


def build_insert_sql(
    table: str,
    columns: Sequence[str],
    *,
    on_conflict: str | None = None,
) -> str:
    """Return a parameterised ``INSERT INTO ...`` statement for asyncpg.

    Placeholders are ``$1, $2, ...`` — asyncpg's native paramstyle.
    ``on_conflict`` lets callers append an ``ON CONFLICT ...`` clause
    (we use ``DO NOTHING`` for the idempotent ``t-default`` tenants
    seed row).
    """
    if not columns:
        raise ValueError(f"no columns provided for {table}")
    col_list = ", ".join(f'"{c}"' for c in columns)
    placeholders = ", ".join(f"${i + 1}" for i in range(len(columns)))
    sql = f'INSERT INTO "{table}" ({col_list}) VALUES ({placeholders})'
    if on_conflict:
        sql += f" {on_conflict}"
    return sql


def build_sequence_reset_sql(table: str, column: str = "id") -> str:
    """Return a ``SELECT setval(...)`` that re-aligns an IDENTITY column.

    We use ``pg_get_serial_sequence`` so this works uniformly for
    IDENTITY (PG 10+) and legacy SERIAL columns.
    """
    return (
        f"SELECT setval("
        f"pg_get_serial_sequence('\"{table}\"', '{column}'), "
        f"COALESCE((SELECT MAX(\"{column}\") FROM \"{table}\"), 1), "
        f"(SELECT MAX(\"{column}\") IS NOT NULL FROM \"{table}\"))"
    )


# ─────────────────────────────────────────────────────────────────────────
#  CLI / argparse (pure — can be tested standalone).
# ─────────────────────────────────────────────────────────────────────────


def build_argparser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="migrate_sqlite_to_pg.py",
        description=(
            "One-shot SQLite → PostgreSQL migration with audit_log "
            "hash chain verification on both sides."
        ),
    )
    p.add_argument(
        "--source",
        required=False,
        default="",
        help=(
            "SQLite source. Either a bare filesystem path "
            "(``data/omnisight.db``) or a SQLAlchemy-style URL "
            "(``sqlite:///data/omnisight.db``). Defaults to "
            "the OMNISIGHT_DATABASE_PATH env var if set."
        ),
    )
    p.add_argument(
        "--target",
        required=False,
        default="",
        help=(
            "Postgres target URL, e.g. "
            "``postgresql+asyncpg://omni:pw@pg-primary:5432/omnisight``. "
            "Required unless --dry-run is set."
        ),
    )
    p.add_argument(
        "--batch-size",
        type=int,
        default=DEFAULT_BATCH_SIZE,
        help=(
            "Number of rows per executemany() batch. Lower = more "
            "progress ticks, higher = less round-trip overhead. "
            "Default: %(default)s."
        ),
    )
    p.add_argument(
        "--tables",
        default="",
        help=(
            "Comma-separated list of tables to migrate. Default: all "
            "known tables in FK-safe order. Tables listed that don't "
            "exist on the source are silently skipped."
        ),
    )
    p.add_argument(
        "--truncate-target",
        action="store_true",
        help=(
            "TRUNCATE every target table before copying. Required "
            "when the target has leftover data from a previous run "
            "(beyond the Alembic-seeded ``t-default`` tenant row)."
        ),
    )
    p.add_argument(
        "--skip-chain-verify",
        action="store_true",
        help=(
            "Skip audit_log hash-chain verification. DANGEROUS — the "
            "chain is the whole point of this script. Only for "
            "recovering a knowingly corrupt database under operator "
            "supervision."
        ),
    )
    p.add_argument(
        "--dry-run",
        action="store_true",
        help=(
            "Read from source and verify the hash chain but make no "
            "writes to the target. Useful as a pre-flight check. "
            "``--target`` is not required when --dry-run is set."
        ),
    )
    p.add_argument(
        "--json",
        action="store_true",
        help="Emit a single JSON report on stdout instead of human log.",
    )
    p.add_argument(
        "--quiet",
        action="store_true",
        help="Suppress per-table progress logging (only final summary).",
    )
    return p


def parse_source_arg(raw: str, *, env: Mapping[str, str] | None = None) -> DatabaseURL:
    """Accept either a URL (``sqlite:///...``) or a bare path.

    If *raw* is empty, falls back to the ``OMNISIGHT_DATABASE_PATH`` env
    var (legacy SQLite-only settings knob). Anything else: pass through
    to :func:`backend.db_url.parse`, which rejects Postgres URLs for the
    ``--source`` slot (the source must be SQLite).
    """
    import os as _os

    env_map = _os.environ if env is None else env
    value = (raw or "").strip()
    if not value:
        value = (env_map.get("OMNISIGHT_DATABASE_PATH") or "").strip()
    if not value:
        raise ValueError(
            "no --source provided and OMNISIGHT_DATABASE_PATH not set"
        )
    if "://" in value:
        url = parse_db_url(value)
    else:
        url = DatabaseURL(
            scheme="sqlite",
            dialect="sqlite",
            driver="aiosqlite",
            database=value,
        )
    if not url.is_sqlite:
        raise ValueError(
            f"--source must be SQLite, got {url.dialect}:{url.driver}"
        )
    return url


def parse_target_arg(raw: str) -> DatabaseURL:
    """Parse ``--target`` as a Postgres asyncpg URL. Empty = error."""
    value = (raw or "").strip()
    if not value:
        raise ValueError("--target is required unless --dry-run is set")
    url = parse_db_url(value)
    if not url.is_postgres:
        raise ValueError(
            f"--target must be PostgreSQL, got {url.dialect}:{url.driver}"
        )
    if url.driver != "asyncpg":
        raise ValueError(
            f"--target must use the asyncpg driver, got {url.driver!r}. "
            "Use postgresql+asyncpg://..."
        )
    return url


# ─────────────────────────────────────────────────────────────────────────
#  Migration data classes.
# ─────────────────────────────────────────────────────────────────────────


@dataclass
class TableResult:
    table:            str
    source_rows:      int = 0
    copied_rows:      int = 0
    skipped:          bool = False
    skipped_reason:   str = ""
    columns:          list[str] = field(default_factory=list)


@dataclass
class MigrationReport:
    source_url:               str = ""
    target_url:               str = ""
    dry_run:                  bool = False
    truncated_target:         bool = False
    source_chain_ok:          bool = False
    source_chain_tenants:     dict[str, dict[str, Any]] = field(default_factory=dict)
    target_chain_ok:          bool | None = None
    target_chain_tenants:     dict[str, dict[str, Any]] = field(default_factory=dict)
    tables:                   list[TableResult] = field(default_factory=list)
    sequences_reset:          dict[str, int] = field(default_factory=dict)
    duration_seconds:         float = 0.0
    exit_code:                int = 0

    def to_dict(self) -> dict[str, Any]:
        return {
            "source_url":           self.source_url,
            "target_url":           self.target_url,
            "dry_run":              self.dry_run,
            "truncated_target":     self.truncated_target,
            "source_chain_ok":      self.source_chain_ok,
            "source_chain_tenants": self.source_chain_tenants,
            "target_chain_ok":      self.target_chain_ok,
            "target_chain_tenants": self.target_chain_tenants,
            "tables": [
                {
                    "table":           t.table,
                    "source_rows":     t.source_rows,
                    "copied_rows":     t.copied_rows,
                    "skipped":         t.skipped,
                    "skipped_reason":  t.skipped_reason,
                    "columns":         t.columns,
                }
                for t in self.tables
            ],
            "sequences_reset":    self.sequences_reset,
            "duration_seconds":   round(self.duration_seconds, 3),
            "exit_code":          self.exit_code,
        }


# ─────────────────────────────────────────────────────────────────────────
#  Source (aiosqlite) helpers.
# ─────────────────────────────────────────────────────────────────────────


async def _sqlite_open(url: DatabaseURL) -> Any:  # returns aiosqlite.Connection
    import aiosqlite  # lazy

    path = url.sqlite_path()
    if not path.exists():
        raise FileNotFoundError(f"SQLite source not found: {path}")
    conn = await aiosqlite.connect(str(path))
    conn.row_factory = aiosqlite.Row
    return conn


async def list_source_tables(sqlite_conn: Any) -> list[str]:
    """Return names of all non-internal tables present on the source."""
    async with sqlite_conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table' "
        "AND name NOT LIKE 'sqlite_%' AND name NOT LIKE 'alembic_%' "
        "ORDER BY name"
    ) as cur:
        rows = await cur.fetchall()
    return [r["name"] for r in rows]


async def list_source_columns(sqlite_conn: Any, table: str) -> list[str]:
    """Return column names for *table* in the order the source declared them."""
    # PRAGMA table_info returns (cid, name, type, notnull, dflt_value, pk);
    # ``row[1]`` is the column name regardless of row_factory.
    async with sqlite_conn.execute(f"PRAGMA table_info({table})") as cur:
        rows = await cur.fetchall()
    return [row[1] for row in rows]


async def count_source_rows(sqlite_conn: Any, table: str) -> int:
    async with sqlite_conn.execute(f'SELECT COUNT(*) FROM "{table}"') as cur:
        row = await cur.fetchone()
    return int(row[0]) if row else 0


async def fetch_source_rows(
    sqlite_conn: Any,
    table: str,
    columns: Sequence[str],
    *,
    order_by: str | None = None,
) -> list[dict[str, Any]]:
    """Fetch every row from *table* as a list of dicts.

    We load the whole table into memory for simplicity — OmniSight's
    ops scale is hundreds of thousands of rows for audit_log and a
    few hundred for everything else. If this ever becomes a concern
    (tens of millions of rows) we'll swap to a streaming cursor, but
    the pure-function invariants (hash chain walked in-order) stay
    the same.
    """
    col_list = ", ".join(f'"{c}"' for c in columns)
    sql = f'SELECT {col_list} FROM "{table}"'
    if order_by:
        sql += f" ORDER BY {order_by}"
    async with sqlite_conn.execute(sql) as cur:
        rows = await cur.fetchall()
    return [dict(r) for r in rows]


async def collect_audit_rows_by_tenant(
    sqlite_conn: Any,
) -> dict[str, list[dict[str, Any]]]:
    """Return ``{tenant_id: [rows ordered by id ASC, ...]}``.

    Used both as the pre-flight chain verifier source and as the
    canonical insert order for the target migration: preserving
    ORDER BY id ASC is what keeps the hash chain intact.
    """
    cols = await list_source_columns(sqlite_conn, "audit_log")
    if not cols:
        return {}
    rows = await fetch_source_rows(
        sqlite_conn, "audit_log", cols, order_by="id ASC"
    )
    grouped: dict[str, list[dict[str, Any]]] = {}
    for r in rows:
        tid = r.get("tenant_id") or DEFAULT_TENANT_ID
        grouped.setdefault(tid, []).append(r)
    return grouped


# ─────────────────────────────────────────────────────────────────────────
#  Target (asyncpg) helpers.
# ─────────────────────────────────────────────────────────────────────────


async def _pg_open(url: DatabaseURL) -> Any:  # returns asyncpg.Connection
    try:
        import asyncpg  # lazy
    except ImportError as exc:
        raise RuntimeError(
            "asyncpg is not installed. `pip install asyncpg` first."
        ) from exc
    kw = url.asyncpg_connect_kwargs()
    return await asyncpg.connect(**kw)


async def count_target_rows(pg_conn: Any, table: str) -> int:
    row = await pg_conn.fetchrow(f'SELECT COUNT(*) AS n FROM "{table}"')
    return int(row["n"]) if row else 0


async def target_table_exists(pg_conn: Any, table: str) -> bool:
    row = await pg_conn.fetchrow(
        "SELECT 1 FROM information_schema.tables "
        "WHERE table_schema = current_schema() AND table_name = $1",
        table,
    )
    return row is not None


async def truncate_target(pg_conn: Any, tables: Sequence[str]) -> list[str]:
    """TRUNCATE ... RESTART IDENTITY CASCADE on every given table.

    CASCADE handles the FK references into ``tenants``. We do a single
    TRUNCATE statement for atomicity (a fail half-way leaves a coherent
    empty set; mixing TRUNCATE with DELETE would not).
    """
    present = [t for t in tables if await target_table_exists(pg_conn, t)]
    if not present:
        return []
    quoted = ", ".join(f'"{t}"' for t in present)
    await pg_conn.execute(
        f"TRUNCATE TABLE {quoted} RESTART IDENTITY CASCADE"
    )
    return present


async def reset_identity_sequences(
    pg_conn: Any,
    tables: Iterable[str],
) -> dict[str, int]:
    """Advance the IDENTITY sequence for each table to MAX(id).

    Returns ``{table: new_sequence_value}``. Skips tables that don't
    exist on the target (e.g. if the operator filtered with --tables).
    """
    out: dict[str, int] = {}
    for table in tables:
        if not await target_table_exists(pg_conn, table):
            continue
        sql = build_sequence_reset_sql(table)
        row = await pg_conn.fetchrow(sql)
        if row is not None:
            val = int(list(row.values())[0]) if row else 0
            out[table] = val
    return out


async def copy_rows_to_target(
    pg_conn: Any,
    table: str,
    columns: Sequence[str],
    rows: Sequence[Mapping[str, Any]],
    *,
    batch_size: int,
    on_conflict: str | None = None,
) -> int:
    """executemany the rows in batches; return number inserted."""
    if not rows:
        return 0
    sql = build_insert_sql(table, columns, on_conflict=on_conflict)
    total = 0
    # Convert dict rows to ordered tuples matching *columns*.
    for start in range(0, len(rows), batch_size):
        batch = rows[start : start + batch_size]
        tuples = [tuple(r.get(c) for c in columns) for r in batch]
        await pg_conn.executemany(sql, tuples)
        total += len(batch)
    return total


# ─────────────────────────────────────────────────────────────────────────
#  Source / target pre-flight (pure except for DB reads).
# ─────────────────────────────────────────────────────────────────────────


async def verify_source_chain(
    sqlite_conn: Any,
) -> tuple[bool, dict[str, dict[str, Any]]]:
    """Walk every tenant's chain on the source.

    Returns ``(all_ok, per_tenant_report)``. The per-tenant report
    shape matches :meth:`MigrationReport.source_chain_tenants`:
    ``{tenant_id: {"ok": bool, "first_bad_id": int|None, "why": str}}``.
    """
    grouped = await collect_audit_rows_by_tenant(sqlite_conn)
    report: dict[str, dict[str, Any]] = {}
    all_ok = True
    for tid, rows in grouped.items():
        ok, brk = verify_hash_chain_in_rows(rows)
        if not ok:
            all_ok = False
            report[tid] = {
                "ok":           False,
                "first_bad_id": brk.row_id if brk else None,
                "why":          brk.why if brk else "",
                "expected":     brk.expected if brk else "",
                "actual":       brk.actual if brk else "",
                "rows":         len(rows),
            }
        else:
            report[tid] = {"ok": True, "first_bad_id": None, "rows": len(rows)}
    return all_ok, report


async def check_target_empty(
    pg_conn: Any,
    tables: Sequence[str],
) -> dict[str, int]:
    """Return ``{table: non_trivial_row_count}`` for tables that have
    data beyond the Alembic-seeded ``t-default`` row.

    An empty dict means the target is safe to migrate into without
    ``--truncate-target``.
    """
    dirty: dict[str, int] = {}
    for t in tables:
        if not await target_table_exists(pg_conn, t):
            continue
        n = await count_target_rows(pg_conn, t)
        # ``tenants`` is seeded with exactly one row (``t-default``)
        # by Alembic migration 0012, so one row there is fine.
        if t == "tenants":
            if n > 1:
                dirty[t] = n
        elif n > 0:
            dirty[t] = n
    return dirty


# ─────────────────────────────────────────────────────────────────────────
#  Post-flight: re-walk the chain on the target.
# ─────────────────────────────────────────────────────────────────────────


async def verify_target_chain(
    pg_conn: Any,
) -> tuple[bool, dict[str, dict[str, Any]]]:
    """Walk every tenant's chain on the freshly-migrated target.

    If this ever returns ``ok=False`` it is a migration bug, not a
    data bug — the source was verified before we started. Exit 5.
    """
    # Discover what tenants are present on target; reuse same pure
    # verifier as on the source by fetching all audit rows grouped.
    tenants_rows = await pg_conn.fetch(
        "SELECT DISTINCT tenant_id FROM audit_log ORDER BY tenant_id"
    )
    report: dict[str, dict[str, Any]] = {}
    all_ok = True
    for trow in tenants_rows:
        tid = trow["tenant_id"]
        rows = await pg_conn.fetch(
            "SELECT id, ts, actor, action, entity_kind, entity_id, "
            "before_json, after_json, prev_hash, curr_hash, tenant_id "
            "FROM audit_log WHERE tenant_id = $1 ORDER BY id ASC",
            tid,
        )
        row_dicts = [dict(r) for r in rows]
        ok, brk = verify_hash_chain_in_rows(row_dicts)
        if not ok:
            all_ok = False
            report[tid] = {
                "ok":           False,
                "first_bad_id": brk.row_id if brk else None,
                "why":          brk.why if brk else "",
                "rows":         len(row_dicts),
            }
        else:
            report[tid] = {"ok": True, "first_bad_id": None, "rows": len(row_dicts)}
    return all_ok, report


# ─────────────────────────────────────────────────────────────────────────
#  Orchestrator.
# ─────────────────────────────────────────────────────────────────────────


async def _run_migration(args: argparse.Namespace) -> MigrationReport:
    """Async driver; see :func:`main` for the sync CLI wrapper."""
    t0 = time.monotonic()
    report = MigrationReport(dry_run=bool(args.dry_run))

    # ── Parse URLs before touching any connection ──
    source_url = parse_source_arg(args.source)
    report.source_url = source_url.redacted()
    if not args.dry_run:
        target_url = parse_target_arg(args.target)
        report.target_url = target_url.redacted()
    else:
        target_url = None

    # Table list (intersect operator-provided filter with known order)
    selected: list[str]
    if args.tables:
        requested = [t.strip() for t in args.tables.split(",") if t.strip()]
        unknown = [t for t in requested if t not in TABLES_IN_ORDER]
        if unknown:
            raise ValueError(f"unknown tables: {unknown!r}")
        selected = [t for t in TABLES_IN_ORDER if t in set(requested)]
    else:
        selected = list(TABLES_IN_ORDER)

    sqlite_conn = await _sqlite_open(source_url)
    pg_conn: Any = None
    try:
        # Drop tables not actually present on source (source may be
        # older than current alembic head).
        present_on_source = set(await list_source_tables(sqlite_conn))
        effective = [t for t in selected if t in present_on_source]

        # ── Source chain pre-flight ──
        if not args.skip_chain_verify:
            ok, tenant_report = await verify_source_chain(sqlite_conn)
            report.source_chain_ok = ok
            report.source_chain_tenants = tenant_report
            if not ok:
                report.exit_code = 3
                return report
        else:
            report.source_chain_ok = True  # operator opted out

        if args.dry_run:
            # Still populate per-table source counts for visibility.
            for table in effective:
                cols = await list_source_columns(sqlite_conn, table)
                n = await count_source_rows(sqlite_conn, table)
                report.tables.append(TableResult(
                    table=table, source_rows=n, copied_rows=0,
                    skipped=True, skipped_reason="dry-run",
                    columns=cols,
                ))
            report.exit_code = 0
            return report

        # ── Open target ──
        pg_conn = await _pg_open(target_url)  # type: ignore[arg-type]

        # ── Target emptiness gate ──
        dirty = await check_target_empty(pg_conn, effective)
        if dirty and not args.truncate_target:
            logger.error(
                "target has existing data in %d table(s): %s. "
                "Pass --truncate-target to wipe or clear manually.",
                len(dirty), sorted(dirty),
            )
            report.exit_code = 4
            return report

        if args.truncate_target:
            truncated = await truncate_target(pg_conn, effective)
            report.truncated_target = bool(truncated)
            if not args.quiet:
                logger.info("truncated %d target tables", len(truncated))

        # ── Copy per-table ──
        for table in effective:
            cols = await list_source_columns(sqlite_conn, table)
            if not cols:
                report.tables.append(TableResult(
                    table=table, skipped=True,
                    skipped_reason="no columns on source",
                ))
                continue

            if not await target_table_exists(pg_conn, table):
                report.tables.append(TableResult(
                    table=table, columns=cols, skipped=True,
                    skipped_reason="target table does not exist "
                                  "(run `alembic upgrade head` first)",
                ))
                continue

            # audit_log MUST be migrated in id order across the whole
            # table (not per-tenant) to match SQLite's insertion order.
            order_by = "id ASC" if "id" in cols else None
            rows = await fetch_source_rows(
                sqlite_conn, table, cols, order_by=order_by
            )

            # ``tenants`` has a seed row on the target (``t-default``)
            # inserted by the Alembic bootstrap; we don't truncate it
            # in the default path so use ON CONFLICT DO NOTHING to
            # absorb the re-insert cleanly.
            on_conflict = None
            if table == "tenants" and not args.truncate_target:
                on_conflict = "ON CONFLICT (id) DO NOTHING"

            copied = await copy_rows_to_target(
                pg_conn, table, cols, rows,
                batch_size=args.batch_size,
                on_conflict=on_conflict,
            )
            report.tables.append(TableResult(
                table=table, source_rows=len(rows),
                copied_rows=copied, columns=cols,
            ))
            if not args.quiet:
                logger.info(
                    "copied %6d/%-6d rows -> %s",
                    copied, len(rows), table,
                )

        # ── Reset IDENTITY sequences ──
        identity_tables = [t for t in TABLES_WITH_IDENTITY_ID if t in effective]
        report.sequences_reset = await reset_identity_sequences(
            pg_conn, identity_tables,
        )

        # ── Row count parity ──
        mismatch: list[tuple[str, int, int]] = []
        for t in report.tables:
            if t.skipped:
                continue
            n = await count_target_rows(pg_conn, t.table)
            if n != t.source_rows:
                mismatch.append((t.table, t.source_rows, n))
        if mismatch:
            for table, src, tgt in mismatch:
                logger.error(
                    "row count mismatch: %s source=%d target=%d",
                    table, src, tgt,
                )
            report.exit_code = 6
            return report

        # ── Target chain post-flight ──
        if "audit_log" in effective and not args.skip_chain_verify:
            ok, tenant_report = await verify_target_chain(pg_conn)
            report.target_chain_ok = ok
            report.target_chain_tenants = tenant_report
            if not ok:
                report.exit_code = 5
                return report

        report.exit_code = 0
        return report
    finally:
        try:
            await sqlite_conn.close()
        except Exception:
            pass
        if pg_conn is not None:
            try:
                await pg_conn.close()
            except Exception:
                pass
        report.duration_seconds = time.monotonic() - t0


# ─────────────────────────────────────────────────────────────────────────
#  CLI entry points.
# ─────────────────────────────────────────────────────────────────────────


def _emit_report(report: MigrationReport, *, as_json: bool) -> None:
    if as_json:
        print(json.dumps(report.to_dict(), ensure_ascii=False, sort_keys=True))
        return
    print(f"source: {report.source_url}")
    if report.target_url:
        print(f"target: {report.target_url}")
    print(f"dry-run: {report.dry_run}")
    print(f"truncated_target: {report.truncated_target}")
    print(f"source chain ok: {report.source_chain_ok}")
    if report.target_chain_ok is not None:
        print(f"target chain ok: {report.target_chain_ok}")
    for t in report.tables:
        if t.skipped:
            print(f"  [skip] {t.table}: {t.skipped_reason}")
        else:
            print(f"  [ok  ] {t.table}: {t.copied_rows}/{t.source_rows} rows")
    if report.sequences_reset:
        print("sequences reset:")
        for tbl, val in sorted(report.sequences_reset.items()):
            print(f"  {tbl} = {val}")
    print(f"duration: {report.duration_seconds:.3f}s")
    print(f"exit code: {report.exit_code}")


def main(argv: Sequence[str] | None = None) -> int:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )
    args = build_argparser().parse_args(argv)
    try:
        # Argument validation that doesn't need a connection.
        parse_source_arg(args.source)
        if not args.dry_run:
            parse_target_arg(args.target)
    except (ValueError, MalformedURLError, UnsupportedURLError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    try:
        report = asyncio.run(_run_migration(args))
    except FileNotFoundError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    except (MalformedURLError, UnsupportedURLError, ValueError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    except RuntimeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    _emit_report(report, as_json=bool(args.json))
    return report.exit_code


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
