-- Generated by SKILL-SPRING-BOOT (X9 #305).
--
-- Flyway baseline migration. Creates the `items` table the default
-- scaffold CRUD surface hits. Any schema change after this ships
-- must land as `V2__*.sql`, `V3__*.sql`, … so Hibernate's
-- `ddl-auto=validate` keeps passing.

CREATE TABLE IF NOT EXISTS items (
    id   BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);
