/* SPDX-License-Identifier: MIT
 *
 * Version constants for the OP-1949 customer SDK header bundle.
 */
#ifndef OMNISIGHT_CASE4_VERSION_H
#define OMNISIGHT_CASE4_VERSION_H

#define OMNISIGHT_CASE4_SDK_VERSION_MAJOR 1
#define OMNISIGHT_CASE4_SDK_VERSION_MINOR 0
#define OMNISIGHT_CASE4_SDK_VERSION_PATCH 0
#define OMNISIGHT_CASE4_SDK_VERSION "1.0.0"

#endif /* OMNISIGHT_CASE4_VERSION_H */
