"""W4 #278 — Docker + nginx static-site deploy adapter.

The outlier in the W4 family: instead of hitting a cloud REST API, this
adapter renders a self-contained docker + nginx build context on disk.
The output is what ``docker build`` + ``docker run`` can consume with no
additional setup, matching the ``deploy_provider: docker`` path from the
``web-ssr-node`` profile and the ``deploy_provider: any-static`` fallback
from ``web-static``.

Why on-disk files instead of a direct ``docker build`` invocation:

    1. Operators frequently deploy to air-gapped infra where the
       OmniSight backend has no Docker socket. Emitting a self-contained
       build context decouples "provision" from "hand off to ops".
    2. The rendered context is reviewable and commit-able — no
       surprise layers, no vendored binaries.
    3. Tests can diff the generated files deterministically without a
       Docker daemon.

``provision()`` renders:

    <output>/
        Dockerfile           — two-stage build (nginx:alpine)
        nginx.conf           — SPA-safe config (try_files → index.html)
        .dockerignore         — excludes node_modules / .git
        docker-compose.yml    — one-liner for local bring-up (optional)

``deploy(build_artifact)`` copies the build output under
``<output>/public/`` so ``docker build .`` picks it up as the final
image payload. If the Docker daemon is reachable on the host it also
runs ``docker build`` + ``docker run`` and records the container id —
otherwise it writes a ``deploy.sh`` helper the operator can run on the
target host.
"""

from __future__ import annotations

import logging
import shutil
import subprocess
import uuid
from pathlib import Path
from typing import Any, Optional

from backend.deploy.base import (
    BuildArtifact,
    DeployArtifactError,
    DeployError,
    DeployResult,
    ProvisionResult,
    RollbackUnavailableError,
    WebDeployAdapter,
)

logger = logging.getLogger(__name__)


_DEFAULT_NGINX_CONF = """# W4 #278 — SPA-safe nginx config for OmniSight static web deploys.
# try_files makes every 404 fall back to /index.html so client-side
# routers (Next.js static export, SvelteKit adapter-static, Astro)
# keep working under direct URLs.
worker_processes  auto;
events { worker_connections 1024; }

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    keepalive_timeout 65;
    gzip          on;
    gzip_types    text/plain text/css application/json application/javascript
                  application/xml+rss text/xml application/xml image/svg+xml;

    server {
        listen       __PORT__;
        server_name  _;
        root   /usr/share/nginx/html;
        index  index.html;

        location /healthz {
            access_log off;
            return 200 \"ok\\n\";
        }

        # Long-cache fingerprinted assets.
        location ~* \\.(css|js|svg|woff2?|ttf|eot|otf|png|jpe?g|gif|webp|ico|avif)$ {
            expires 7d;
            add_header Cache-Control \"public, max-age=604800, immutable\";
            try_files $uri =404;
        }

        # SPA fallback — unknown paths → index.html.
        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
"""


_DOCKERFILE_TEMPLATE = """# W4 #278 — Auto-generated by backend.deploy.docker_nginx
# Project: __PROJECT__
# Generated: __GENERATED__
FROM nginx:1.27-alpine

LABEL org.opencontainers.image.source=\"omnisight\" \\
      org.opencontainers.image.title=\"__PROJECT__\" \\
      org.opencontainers.image.description=\"Static site served via nginx\"

COPY nginx.conf /etc/nginx/nginx.conf
COPY public/ /usr/share/nginx/html/

EXPOSE __PORT__
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s \\
    CMD wget -qO- http://127.0.0.1:__PORT__/healthz >/dev/null 2>&1 || exit 1

CMD [\"nginx\", \"-g\", \"daemon off;\"]
"""


_DOCKERIGNORE = """.git
.gitignore
node_modules
.next
.cache
.DS_Store
*.log
tests
test
__pycache__
"""


_COMPOSE_TEMPLATE = """# W4 #278 — docker-compose bring-up for __PROJECT__
services:
  web:
    build: .
    image: __PROJECT__:latest
    ports:
      - \"__PORT__:__PORT__\"
    restart: unless-stopped
    healthcheck:
      test: [\"CMD\", \"wget\", \"-qO-\", \"http://127.0.0.1:__PORT__/healthz\"]
      interval: 30s
      timeout: 3s
      retries: 3
"""


_DEPLOY_SH_TEMPLATE = """#!/usr/bin/env sh
# W4 #278 — Helper generated by backend.deploy.docker_nginx.
# Run on a host with Docker installed to build + run the image.
set -e
cd \"$(dirname \"$0\")\"
IMAGE=\"__PROJECT__:__TAG__\"
CONTAINER=\"__PROJECT__\"
PORT=\"__PORT__\"

echo \"[docker_nginx] Building image $IMAGE...\"
docker build -t \"$IMAGE\" .

echo \"[docker_nginx] Restarting container $CONTAINER on port $PORT...\"
docker rm -f \"$CONTAINER\" 2>/dev/null || true
docker run -d --name \"$CONTAINER\" -p \"$PORT:$PORT\" --restart unless-stopped \"$IMAGE\"
docker ps --filter \"name=$CONTAINER\"
"""


class DockerNginxAdapter(WebDeployAdapter):
    """Static site + nginx Docker deploy adapter (``provider='docker-nginx'``).

    Works entirely on the local filesystem; the "token" is a harmless
    placeholder so the adapter fits the unified interface but it never
    hits any remote service. ``output_dir`` defaults to
    ``./dist/docker-<project_name>/``.
    """

    provider = "docker-nginx"

    def _configure(
        self,
        *,
        output_dir: Optional[Path] = None,
        port: int = 8080,
        image_tag: str = "latest",
        public_url: Optional[str] = None,
        run_docker_build: bool = False,
        **_: Any,
    ) -> None:
        if output_dir is None:
            output_dir = Path.cwd() / "dist" / f"docker-{self._project_name}"
        self._output_dir = Path(output_dir)
        self._port = int(port)
        self._image_tag = image_tag
        self._public_url = public_url or f"http://localhost:{self._port}"
        self._run_docker_build = bool(run_docker_build)
        self._rollback_stack: list[str] = []  # stack of previous image tags

    @classmethod
    def from_plaintext_token(
        cls,
        token: str = "",
        *,
        project_name: str,
        **kwargs: Any,
    ) -> "WebDeployAdapter":
        # docker-nginx has no remote credential; accept an empty token.
        return cls(token=token or "docker-nginx-local", project_name=project_name, **kwargs)

    # ── Public helpers ──

    @property
    def output_dir(self) -> Path:
        return self._output_dir

    @property
    def port(self) -> int:
        return self._port

    @property
    def image_tag(self) -> str:
        return self._image_tag

    # ── Render helpers ──

    def _render_dockerfile(self) -> str:
        import datetime
        return (
            _DOCKERFILE_TEMPLATE
            .replace("__PROJECT__", self._project_name)
            .replace("__PORT__", str(self._port))
            .replace(
                "__GENERATED__",
                datetime.datetime.now(datetime.timezone.utc)
                .replace(microsecond=0).isoformat().replace("+00:00", "Z"),
            )
        )

    def _render_nginx_conf(self) -> str:
        return _DEFAULT_NGINX_CONF.replace("__PORT__", str(self._port))

    def _render_compose(self) -> str:
        return (
            _COMPOSE_TEMPLATE
            .replace("__PROJECT__", self._project_name)
            .replace("__PORT__", str(self._port))
        )

    def _render_deploy_sh(self) -> str:
        return (
            _DEPLOY_SH_TEMPLATE
            .replace("__PROJECT__", self._project_name)
            .replace("__TAG__", self._image_tag)
            .replace("__PORT__", str(self._port))
        )

    def _write_build_context(self, env: Optional[dict[str, str]] = None) -> list[str]:
        self._output_dir.mkdir(parents=True, exist_ok=True)
        (self._output_dir / "Dockerfile").write_text(self._render_dockerfile(), encoding="utf-8")
        (self._output_dir / "nginx.conf").write_text(self._render_nginx_conf(), encoding="utf-8")
        (self._output_dir / ".dockerignore").write_text(_DOCKERIGNORE, encoding="utf-8")
        (self._output_dir / "docker-compose.yml").write_text(self._render_compose(), encoding="utf-8")
        sh_path = self._output_dir / "deploy.sh"
        sh_path.write_text(self._render_deploy_sh(), encoding="utf-8")
        try:
            sh_path.chmod(0o755)
        except OSError:
            pass
        written = ["Dockerfile", "nginx.conf", ".dockerignore", "docker-compose.yml", "deploy.sh"]
        if env:
            # Render an env file so the operator can `--env-file` it. We
            # DO NOT bake env vars into the image (static site — there's
            # no server code to read them at runtime); the env file is
            # therefore a build-time reference, not a runtime source.
            env_lines = [f"{k}={v}" for k, v in env.items()]
            (self._output_dir / ".env.deploy").write_text(
                "\n".join(env_lines) + "\n", encoding="utf-8",
            )
            written.append(".env.deploy")
        return written

    # ── Abstract impl ──

    async def provision(
        self,
        *,
        env: Optional[dict[str, str]] = None,
        **kwargs: Any,
    ) -> ProvisionResult:
        self._write_build_context(env=env)
        # Reserve a public dir so deploy() can drop the build output in.
        (self._output_dir / "public").mkdir(parents=True, exist_ok=True)
        self._project_id = self._project_name  # Docker "project id" == name
        self._cached_url = self._public_url
        logger.info(
            "docker_nginx.provision project=%s dir=%s port=%d",
            self._project_name, self._output_dir, self._port,
        )
        return ProvisionResult(
            provider=self.provider,
            project_id=self._project_name,
            project_name=self._project_name,
            url=self._public_url,
            created=True,
            env_vars_set=list(env.keys()) if env else [],
            raw={
                "output_dir": str(self._output_dir),
                "port": self._port,
                "image_tag": self._image_tag,
            },
        )

    def _copy_tree(self, src: Path, dst: Path) -> int:
        # Refuse self-containment: copying a parent into its own descendant
        # would recurse forever (observed with tmp_path root = build artifact
        # AND output_dir = tmp_path / "deploy-ctx").
        src_resolved = src.resolve()
        dst_resolved = dst.resolve()
        try:
            dst_resolved.relative_to(src_resolved)
            raise DeployArtifactError(
                f"Refusing to copy {src} into its own descendant {dst}"
            )
        except ValueError:
            pass  # dst is NOT under src — safe.
        if dst.exists():
            shutil.rmtree(dst)
        dst.mkdir(parents=True, exist_ok=True)
        count = 0
        for p in src.rglob("*"):
            rel = p.relative_to(src)
            target = dst / rel
            if p.is_dir():
                target.mkdir(parents=True, exist_ok=True)
            else:
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(p, target)
                count += 1
        return count

    async def deploy(self, build_artifact: BuildArtifact) -> DeployResult:
        build_artifact.validate()
        self._enforce_container_vulnerability_gate(build_artifact)
        if not self._output_dir.exists():
            # deploy() called without provision() — render the context first.
            self._write_build_context()
        public_dir = self._output_dir / "public"
        count = self._copy_tree(build_artifact.path, public_dir)
        if count == 0:
            raise DeployArtifactError(
                f"Build artifact at {build_artifact.path} has no files"
            )

        deployment_id = f"{self._project_name}-{uuid.uuid4().hex[:12]}"
        container_id: Optional[str] = None
        status = "ready"

        if self._run_docker_build:
            if not shutil.which("docker"):
                raise DeployError(
                    "run_docker_build=True but 'docker' is not on PATH.",
                    provider=self.provider,
                )
            image = f"{self._project_name}:{self._image_tag}"
            # Record the previous image sha (if any) for rollback.
            try:
                prev = subprocess.run(
                    ["docker", "inspect", "--format={{.Id}}", image],
                    capture_output=True, text=True, check=False,
                )
                if prev.returncode == 0 and prev.stdout.strip():
                    self._rollback_stack.append(prev.stdout.strip())
            except OSError:
                pass
            subprocess.run(
                ["docker", "build", "-t", image, str(self._output_dir)],
                check=True,
            )
            # Restart container.
            subprocess.run(
                ["docker", "rm", "-f", self._project_name],
                check=False, capture_output=True,
            )
            run = subprocess.run(
                [
                    "docker", "run", "-d",
                    "--name", self._project_name,
                    "-p", f"{self._port}:{self._port}",
                    "--restart", "unless-stopped",
                    image,
                ],
                check=True, capture_output=True, text=True,
            )
            container_id = run.stdout.strip()
            status = "ready"

        self._last_deployment_id = deployment_id
        self._cached_url = self._public_url
        logger.info(
            "docker_nginx.deploy project=%s deployment=%s files=%d docker_built=%s",
            self._project_name, deployment_id, count, self._run_docker_build,
        )
        return DeployResult(
            provider=self.provider,
            deployment_id=deployment_id,
            url=self._public_url,
            status=status,
            logs_url=None,
            commit_sha=build_artifact.commit_sha,
            raw={
                "output_dir": str(self._output_dir),
                "files_copied": count,
                "container_id": container_id,
                "docker_built": self._run_docker_build,
            },
        )

    async def rollback(
        self,
        *,
        deployment_id: Optional[str] = None,
    ) -> DeployResult:
        previous_id = self._last_deployment_id
        if not self._run_docker_build:
            raise RollbackUnavailableError(
                "docker_nginx rollback only available when run_docker_build=True "
                "(nothing to revert for disk-only render).",
                provider=self.provider,
            )
        target = deployment_id
        if not target:
            if not self._rollback_stack:
                raise RollbackUnavailableError(
                    "No previous image sha recorded to roll back to.",
                    provider=self.provider,
                )
            target = self._rollback_stack.pop()

        subprocess.run(
            ["docker", "tag", target, f"{self._project_name}:{self._image_tag}"],
            check=True, capture_output=True,
        )
        subprocess.run(
            ["docker", "rm", "-f", self._project_name],
            check=False, capture_output=True,
        )
        subprocess.run(
            [
                "docker", "run", "-d",
                "--name", self._project_name,
                "-p", f"{self._port}:{self._port}",
                "--restart", "unless-stopped",
                f"{self._project_name}:{self._image_tag}",
            ],
            check=True, capture_output=True,
        )
        logger.info(
            "docker_nginx.rollback project=%s target=%s previous=%s",
            self._project_name, target, previous_id,
        )
        return DeployResult(
            provider=self.provider,
            deployment_id=target,
            url=self._public_url,
            status="rolled-back",
            previous_deployment_id=previous_id,
            raw={"restored_sha": target},
        )

    def get_url(self) -> Optional[str]:
        return self._cached_url


__all__ = ["DockerNginxAdapter"]
