// Generated by SKILL-NEXTJS (W6 #280).
// FS.7.4 todo example page. Server Component shell; interactivity
// stays in components/TodoApp.tsx.

import { TodoApp } from "@/components/TodoApp"

const initialTodos = [
  { id: "plan", title: "Plan launch checklist", done: true },
  { id: "write", title: "Draft customer update", done: false },
  { id: "ship", title: "Ship production bundle", done: false },
]

export default function TodosPage() {
  return (
    <main id="main" role="main" aria-labelledby="todos-heading">
      <h1 id="todos-heading">Todo example</h1>
      <p>
        A complete client-side todo workflow rendered inside the
        FS.7.4 full-stack bundle.
      </p>
      <TodoApp initialTodos={initialTodos} />
    </main>
  )
}
