// Generated by SKILL-ASTRO (W8 #282). SC.6.3 security headers.
// Astro middleware applies the same origin hardening for server targets.

import { defineMiddleware } from "astro:middleware"

const SECURITY_HEADERS: Array<[string, string]> = [
  ["Content-Security-Policy", "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; connect-src 'self' https:; frame-ancestors 'none'; base-uri 'self'; form-action 'self'"],
  ["Strict-Transport-Security", "max-age=31536000; includeSubDomains; preload"],
  ["X-Frame-Options", "DENY"],
  ["X-Content-Type-Options", "nosniff"],
  ["Referrer-Policy", "strict-origin"],
  ["Permissions-Policy", "camera=(), microphone=(), geolocation=(), payment=()"],
  ["Cross-Origin-Resource-Policy", "same-origin"],
  ["Cross-Origin-Embedder-Policy", "require-corp"],
  ["Cross-Origin-Opener-Policy", "same-origin"],
]

export const onRequest = defineMiddleware(async (_context, next) => {
  const response = await next()
  for (const [header, value] of SECURITY_HEADERS) {
    response.headers.set(header, value)
  }
  return response
})
