/* BLE GATT Server scaffold — auto-generated by connectivity sub-skill.
 * Customize service UUIDs, characteristics, and callbacks for your product. */

#include <stdint.h>
#include <string.h>

/* Platform-specific BLE headers (Nordic / ESP-IDF / Zephyr) */
#if defined(CONFIG_BT_NRF_SOFTDEVICE)
#include <ble.h>
#include <ble_gatts.h>
#elif defined(CONFIG_BT_NIMBLE_ENABLED)
#include "esp_nimble_hci.h"
#include "nimble/nimble_port.h"
#include "host/ble_hs.h"
#elif defined(CONFIG_BT)
#include <zephyr/bluetooth/bluetooth.h>
#include <zephyr/bluetooth/gatt.h>
#endif

#define CUSTOM_SERVICE_UUID   0x1234
#define CUSTOM_CHAR_RX_UUID   0x1235
#define CUSTOM_CHAR_TX_UUID   0x1236

static uint8_t rx_buffer[512];
static uint8_t tx_buffer[512];

static int on_write_cb(uint16_t conn_handle, const uint8_t *data, uint16_t len) {
    if (len > sizeof(rx_buffer)) len = sizeof(rx_buffer);
    memcpy(rx_buffer, data, len);
    /* TODO: process incoming data */
    return 0;
}

static int on_read_cb(uint16_t conn_handle, uint8_t *data, uint16_t *len) {
    *len = sizeof(tx_buffer);
    memcpy(data, tx_buffer, *len);
    return 0;
}

int ble_gatt_server_init(void) {
    /* TODO: register service table with platform BLE stack */
    return 0;
}
