/* CAN / SocketCAN scaffold — auto-generated by connectivity sub-skill.
 * Supports CAN 2.0B and CAN FD via Linux SocketCAN. */

#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include <unistd.h>
#include <net/if.h>
#include <sys/socket.h>
#include <sys/ioctl.h>
#include <linux/can.h>
#include <linux/can/raw.h>

typedef struct {
    int sock_fd;
    char ifname[IFNAMSIZ];
    uint32_t bitrate;
    uint8_t is_fd;
} can_ctx_t;

static can_ctx_t can_ctx;

int can_init(const char *ifname, uint32_t bitrate, uint8_t use_fd) {
    strncpy(can_ctx.ifname, ifname, IFNAMSIZ - 1);
    can_ctx.bitrate = bitrate;
    can_ctx.is_fd = use_fd;

    can_ctx.sock_fd = socket(PF_CAN, SOCK_RAW, CAN_RAW);
    if (can_ctx.sock_fd < 0) return -1;

    struct ifreq ifr;
    strncpy(ifr.ifr_name, ifname, IFNAMSIZ - 1);
    if (ioctl(can_ctx.sock_fd, SIOCGIFINDEX, &ifr) < 0) {
        close(can_ctx.sock_fd);
        return -2;
    }

    struct sockaddr_can addr = {0};
    addr.can_family = AF_CAN;
    addr.can_ifindex = ifr.ifr_ifindex;

    if (bind(can_ctx.sock_fd, (struct sockaddr *)&addr, sizeof(addr)) < 0) {
        close(can_ctx.sock_fd);
        return -3;
    }

    return 0;
}

int can_send(uint32_t id, const uint8_t *data, uint8_t len) {
    struct can_frame frame = {0};
    frame.can_id = id;
    frame.can_dlc = len > 8 ? 8 : len;
    memcpy(frame.data, data, frame.can_dlc);
    return write(can_ctx.sock_fd, &frame, sizeof(frame)) > 0 ? 0 : -1;
}

int can_recv(struct can_frame *frame, int timeout_ms) {
    /* TODO: use poll() or select() for timeout */
    return read(can_ctx.sock_fd, frame, sizeof(*frame)) > 0 ? 0 : -1;
}

void can_close(void) {
    if (can_ctx.sock_fd >= 0) {
        close(can_ctx.sock_fd);
        can_ctx.sock_fd = -1;
    }
}
