/* Ethernet VLAN + PoE scaffold — auto-generated by connectivity sub-skill.
 * Covers basic link, 802.1Q VLAN tagging, and PoE detection. */

#include <stdint.h>
#include <string.h>
#include <stdio.h>

typedef struct {
    char ifname[32];
    uint32_t speed_mbps;
    uint8_t duplex;  /* 0=half, 1=full */
    uint8_t link_up;
} eth_link_status_t;

typedef struct {
    uint16_t vlan_id;
    char parent_if[32];
    char vlan_if[48];
} vlan_config_t;

typedef struct {
    uint8_t poe_detected;
    uint8_t power_class;   /* 0-8 per 802.3bt */
    float power_budget_w;
    float power_drawn_w;
} poe_status_t;

int eth_get_link_status(const char *ifname, eth_link_status_t *status) {
    /* TODO: ethtool / ioctl SIOCETHTOOL */
    memset(status, 0, sizeof(*status));
    strncpy(status->ifname, ifname, sizeof(status->ifname) - 1);
    return 0;
}

int eth_vlan_create(const char *parent_if, uint16_t vlan_id) {
    /* ip link add link <parent> name <parent>.<vid> type vlan id <vid> */
    char cmd[256];
    snprintf(cmd, sizeof(cmd),
             "ip link add link %s name %s.%u type vlan id %u",
             parent_if, parent_if, vlan_id, vlan_id);
    return system(cmd);
}

int eth_vlan_delete(const char *parent_if, uint16_t vlan_id) {
    char cmd[256];
    snprintf(cmd, sizeof(cmd), "ip link del %s.%u", parent_if, vlan_id);
    return system(cmd);
}

int eth_poe_get_status(const char *ifname, poe_status_t *status) {
    /* TODO: read from sysfs or PSE controller I2C */
    memset(status, 0, sizeof(*status));
    return 0;
}
