"""Modbus RTU / TCP scaffold — auto-generated by connectivity sub-skill.

Provides master/slave (client/server) abstractions using pymodbus.
Customize register maps and function codes for your product.
"""

from __future__ import annotations
from dataclasses import dataclass, field
from typing import Any


@dataclass
class ModbusRegister:
    address: int
    name: str
    data_type: str = "uint16"
    access: str = "rw"
    description: str = ""


@dataclass
class ModbusConfig:
    mode: str = "rtu"  # rtu | tcp
    port: str = "/dev/ttyUSB0"  # serial port or IP:port
    baudrate: int = 9600
    slave_id: int = 1
    timeout_s: float = 1.0


REGISTER_MAP: list[ModbusRegister] = [
    ModbusRegister(address=0, name="device_status", data_type="uint16", access="ro"),
    ModbusRegister(address=1, name="temperature", data_type="int16", access="ro"),
    ModbusRegister(address=2, name="setpoint", data_type="uint16", access="rw"),
]


class ModbusMaster:
    def __init__(self, config: ModbusConfig):
        self.config = config
        self._client = None

    def connect(self) -> bool:
        # TODO: pymodbus ModbusSerialClient or ModbusTcpClient
        return True

    def read_holding_registers(self, address: int, count: int = 1) -> list[int]:
        # TODO: self._client.read_holding_registers(address, count, slave=self.config.slave_id)
        return [0] * count

    def write_register(self, address: int, value: int) -> bool:
        # TODO: self._client.write_register(address, value, slave=self.config.slave_id)
        return True

    def close(self) -> None:
        if self._client:
            pass  # TODO: self._client.close()


class ModbusSlave:
    def __init__(self, config: ModbusConfig, register_map: list[ModbusRegister] | None = None):
        self.config = config
        self.register_map = register_map or REGISTER_MAP
        self._server = None

    def start(self) -> bool:
        # TODO: pymodbus StartSerialServer or StartTcpServer
        return True

    def stop(self) -> None:
        if self._server:
            pass  # TODO: self._server.shutdown()
