/* WiFi STA/AP scaffold — auto-generated by connectivity sub-skill.
 * Customize SSID, credentials, and event handlers for your product. */

#include <stdint.h>
#include <string.h>

/* Platform-specific WiFi headers */
#if defined(CONFIG_ESP_WIFI_ENABLED)
#include "esp_wifi.h"
#include "esp_event.h"
#elif defined(CONFIG_WIFI)
#include <zephyr/net/wifi_mgmt.h>
#endif

typedef struct {
    char ssid[33];
    char password[65];
    uint8_t mode; /* 0 = STA, 1 = AP, 2 = STA+AP */
    uint8_t auth_mode; /* 0=OPEN, 1=WPA2, 2=WPA3, 3=Enterprise */
} wifi_config_t;

static wifi_config_t current_config;

int wifi_sta_connect(const char *ssid, const char *password) {
    strncpy(current_config.ssid, ssid, sizeof(current_config.ssid) - 1);
    strncpy(current_config.password, password, sizeof(current_config.password) - 1);
    current_config.mode = 0;
    /* TODO: call platform WiFi connect API */
    return 0;
}

int wifi_ap_start(const char *ssid, const char *password, uint8_t channel) {
    strncpy(current_config.ssid, ssid, sizeof(current_config.ssid) - 1);
    strncpy(current_config.password, password, sizeof(current_config.password) - 1);
    current_config.mode = 1;
    /* TODO: call platform SoftAP start API */
    return 0;
}

int wifi_provision_start(void) {
    /* TODO: start SoftAP provisioning flow */
    return 0;
}
