#!/usr/bin/env bash
# Generated by SKILL-DESKTOP-TAURI (X8 #304).
#
# Enforce the X1 software simulate-track Rust coverage floor (75%) on
# the src-tauri/ crate. Matches `COVERAGE_THRESHOLDS["rust"]` in
# backend/software_simulator.py — same gate the X7 SKILL-RUST-CLI
# script enforces.
#
# Tries cargo-llvm-cov first (the upstream-blessed tool), falls back
# to cargo-tarpaulin. Exits non-zero on missing toolchain (so CI
# enforces rather than silently skipping) unless COVERAGE_ALLOW_SKIP=1.

set -euo pipefail

THRESHOLD="${COVERAGE_THRESHOLD:-75.0}"
ALLOW_SKIP="${COVERAGE_ALLOW_SKIP:-0}"

cd "$(dirname "$0")/../src-tauri"

if command -v cargo-llvm-cov >/dev/null 2>&1 || cargo llvm-cov --help >/dev/null 2>&1; then
    tool="llvm-cov"
elif command -v cargo-tarpaulin >/dev/null 2>&1 || cargo tarpaulin --help >/dev/null 2>&1; then
    tool="tarpaulin"
else
    if [ "$ALLOW_SKIP" = "1" ]; then
        echo "cargo-llvm-cov / cargo-tarpaulin not installed; skipping coverage gate" >&2
        exit 0
    fi
    echo "cargo-llvm-cov or cargo-tarpaulin required (neither on PATH)" >&2
    exit 127
fi

if [ "$tool" = "llvm-cov" ]; then
    output="$(cargo llvm-cov --summary-only 2>&1)"
    pct="$(printf '%s\n' "$output" | awk '/^TOTAL/ {gsub("%","",$NF); print $NF; exit}')"
else
    output="$(cargo tarpaulin --print-summary 2>&1)"
    pct="$(printf '%s\n' "$output" | awk '/coverage/ {for(i=1;i<=NF;i++) if ($i ~ /%/) {gsub("%","",$i); print $i; exit}}')"
fi

if [ -z "${pct:-}" ]; then
    echo "could not parse coverage output from cargo $tool" >&2
    printf '%s\n' "$output" >&2
    exit 1
fi

awk -v t="$pct" -v th="$THRESHOLD" '
  BEGIN {
    if (t + 0 < th + 0) {
      printf "Rust coverage %.1f%% is below threshold %.1f%% (X1 Rust floor)\n", t, th
      exit 1
    }
    printf "Rust coverage %.1f%% meets threshold %.1f%%\n", t, th
  }
'
