// Generated by SKILL-RUST-CLI (X7 #303).
//
// `version` subcommand — fulfils the cli-tooling role rule #1
// (`{name} {semver} ({git_sha})`). build.rs injects BUILD_GIT_SHA
// at compile time via cargo:rustc-env; semver comes from
// CARGO_PKG_VERSION (populated by cargo).

use anyhow::Result;
use serde::Serialize;

#[derive(Debug, Serialize)]
struct VersionReport {
    name: &'static str,
    version: &'static str,
    build_sha: &'static str,
}

pub fn run(json: bool) -> Result<()> {
    let report = VersionReport {
        name: env!("CARGO_PKG_NAME"),
        version: env!("CARGO_PKG_VERSION"),
        build_sha: env!("BUILD_GIT_SHA"),
    };

    if json {
        let line = serde_json::to_string(&report).expect("serialise VersionReport");
        println!("{line}");
    } else {
        println!("{} {} ({})", report.name, report.version, report.build_sha);
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn report_fields_populated() {
        let r = VersionReport {
            name: env!("CARGO_PKG_NAME"),
            version: env!("CARGO_PKG_VERSION"),
            build_sha: env!("BUILD_GIT_SHA"),
        };
        assert!(!r.name.is_empty());
        assert!(!r.version.is_empty());
    }

    #[test]
    fn json_output_is_structured() {
        let r = VersionReport {
            name: "x",
            version: "0.1.0",
            build_sha: "abc123",
        };
        let line = serde_json::to_string(&r).unwrap();
        assert!(line.contains("\"name\":\"x\""));
        assert!(line.contains("\"version\":\"0.1.0\""));
    }
}
