// Generated by SKILL-NEXTJS (W6 #280). AUTH=nextauth.
// Next.js middleware — route guard. Redirect unauthenticated users
// to /auth/sign-in for any /dashboard/* path.

export { auth as middleware } from "@/auth/nextauth.config"

export const config = {
  matcher: ["/dashboard/:path*", "/api/protected/:path*"],
}
