// Generated by SKILL-NUXT (W7 #281).
// Health probe — Nitro route handler. File name `health.get.ts`
// makes it a GET handler at `/api/health` (Nitro convention).
// Intentionally does not depend on the backend so cold-start
// liveness checks stay green even when upstream warms up.

export default defineEventHandler(() => ({
  status: "ok",
  service: "nuxt",
  at: new Date().toISOString(),
}))
