"""BP.Q.2 -- git ``post-merge`` hook for workspace RAG indexing.

This mirrors :mod:`backend.hooks.post_merge_docs`: keep the git hook thin,
fast-skip when a merge did not touch indexable paths, and delegate real work
to :mod:`backend.agents.rag_indexer`.

Module-global state audit (SOP 2026-04-21 rule)
-----------------------------------------------
This module has immutable constants and pure helpers only. It runs from a
developer git client, not uvicorn workers; persisted RAG state lives in the
configured BP.Q vector store.
"""

from __future__ import annotations

import argparse
import logging
import os
import subprocess
import sys
import time
from pathlib import Path
from typing import Iterable

from backend.agents.rag_indexer import classify_source_path

logger = logging.getLogger(__name__)

_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
_GIT_DIR = _REPO_ROOT / ".git"
_HOOK_PATH = _GIT_DIR / "hooks" / "post-merge"

_HOOK_SHIM = """\
#!/usr/bin/env sh
# Auto-generated by `python -m backend.hooks.post_merge_rag_index --install`.
# Source of truth: backend/hooks/post_merge_rag_index.py
exec python3 -m backend.hooks.post_merge_rag_index "$@"
"""


def main(argv: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m backend.hooks.post_merge_rag_index",
        description="git post-merge hook that incrementally refreshes BP.Q RAG chunks.",
    )
    parser.add_argument("--force", action="store_true")
    parser.add_argument("--install", action="store_true")
    parser.add_argument("--uninstall", action="store_true")
    args = parser.parse_args(list(argv) if argv is not None else None)

    if args.install:
        return _install_hook()
    if args.uninstall:
        return _uninstall_hook()
    return _run_hook(force=args.force)


def _run_hook(*, force: bool) -> int:
    """Run incremental indexing. Always returns 0 to git."""

    if os.environ.get("OMNISIGHT_RAG_INDEX_ON_MERGE", "").lower() not in {
        "1",
        "true",
        "yes",
    }:
        logger.debug("post_merge_rag_index: disabled by env")
        return 0

    if not force:
        changed = _changed_files_in_merge()
        if changed is None:
            _emit("could not determine merge diff; running incremental index")
        elif not _merge_touches_indexable_path(changed):
            logger.debug("post_merge_rag_index: merge does not touch RAG corpus")
            return 0

    try:
        from backend.agents.rag_indexer import main as run_indexer
    except ImportError as exc:
        _emit(f"backend not importable ({exc}); skipping RAG index refresh")
        return 0

    started = time.monotonic()
    try:
        rc = run_indexer(["--repo-root", str(_REPO_ROOT), "--incremental"])
    except Exception as exc:  # pragma: no cover - defensive hook path
        _emit(
            f"RAG index refresh crashed: {exc}. "
            "Your merge succeeded; run `python -m backend.agents.rag_indexer "
            "--incremental` to investigate."
        )
        logger.exception("post_merge_rag_index: refresh crashed")
        return 0
    if rc == 0:
        _emit(f"refreshed workspace RAG index ({time.monotonic() - started:.1f}s)")
    else:
        _emit(f"RAG index refresh returned {rc}; merge still succeeded")
    return 0


def _changed_files_in_merge() -> list[str] | None:
    try:
        out = subprocess.run(
            ["git", "diff", "--name-only", "ORIG_HEAD", "HEAD"],
            cwd=str(_REPO_ROOT),
            capture_output=True,
            text=True,
            timeout=10,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return None
    if out.returncode != 0:
        return None
    return [line for line in out.stdout.splitlines() if line]


def _merge_touches_indexable_path(changed: Iterable[str]) -> bool:
    for path in changed:
        kind, _language = classify_source_path(path)
        if kind is not None:
            return True
    return False


def _install_hook() -> int:
    if not _GIT_DIR.is_dir():
        _emit(f"not a git repo (no {_GIT_DIR}); cannot install hook", prefix="install")
        return 1
    _HOOK_PATH.parent.mkdir(parents=True, exist_ok=True)
    if _HOOK_PATH.exists() or _HOOK_PATH.is_symlink():
        existing = _HOOK_PATH.read_text(encoding="utf-8", errors="replace")
        if existing == _HOOK_SHIM:
            _emit("hook already installed; nothing to do.", prefix="install")
            return 0
        backup = _HOOK_PATH.with_name(f"post-merge.bak.{int(time.time())}")
        _HOOK_PATH.replace(backup)
        _emit(f"backed up existing hook to {backup.name}", prefix="install")
    _HOOK_PATH.write_text(_HOOK_SHIM, encoding="utf-8")
    _HOOK_PATH.chmod(0o755)
    _emit(f"installed hook to {_HOOK_PATH.relative_to(_REPO_ROOT)}", prefix="install")
    return 0


def _uninstall_hook() -> int:
    if not _HOOK_PATH.exists():
        _emit("no hook to uninstall.", prefix="uninstall")
        return 0
    current = _HOOK_PATH.read_text(encoding="utf-8", errors="replace")
    if current != _HOOK_SHIM:
        _emit(
            f"{_HOOK_PATH.relative_to(_REPO_ROOT)} is not our shim; leaving it alone.",
            prefix="uninstall",
        )
        return 1
    _HOOK_PATH.unlink()
    _emit("removed our shim.", prefix="uninstall")
    backups = sorted(
        _HOOK_PATH.parent.glob("post-merge.bak.*"),
        key=lambda path: path.stat().st_mtime,
        reverse=True,
    )
    if backups:
        backups[0].replace(_HOOK_PATH)
        _emit(f"restored previous hook from {backups[0].name}", prefix="uninstall")
    return 0


def _emit(msg: str, *, prefix: str = "rag-index") -> None:
    sys.stderr.write(f"[{prefix}] {msg}\n")
    sys.stderr.flush()


if __name__ == "__main__":
    logging.basicConfig(
        level=os.environ.get("OMNISIGHT_HOOK_LOGLEVEL", "INFO"),
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )
    sys.exit(main())
