// Generated by SKILL-NEXTJS (W6 #280). RESEND=on.
// Resend API keys stay server-side; never expose them through
// NEXT_PUBLIC_* env vars.

import { Resend } from "resend"

const resend = new Resend(process.env.RESEND_API_KEY)

export async function sendContactEmail(input: {
  fromEmail: string
  subject: string
  body: string
}) {
  const to = process.env.CONTACT_TO_EMAIL
  const from = process.env.RESEND_FROM_EMAIL
  if (!to || !from) {
    throw new Error("CONTACT_TO_EMAIL and RESEND_FROM_EMAIL must be configured")
  }

  return resend.emails.send({
    from,
    to,
    replyTo: input.fromEmail,
    subject: input.subject,
    text: input.body,
  })
}
