"use client"

// Generated by SKILL-NEXTJS (W6 #280). TRPC=on.
// Browser-side tRPC client — wraps the app in QueryClientProvider
// and tRPC's React context. Drop <TRPCProvider> into app/layout.tsx.

import { useState } from "react"
import { QueryClient, QueryClientProvider } from "@tanstack/react-query"
import { httpBatchLink } from "@trpc/client"
import { createTRPCReact } from "@trpc/react-query"
import type { AppRouter } from "@/server/trpc"

export const trpc = createTRPCReact<AppRouter>()

export function TRPCProvider({ children }: { children: React.ReactNode }) {
  const [qc] = useState(() => new QueryClient())
  const [client] = useState(() =>
    trpc.createClient({
      links: [httpBatchLink({ url: "/api/trpc" })],
    }),
  )
  return (
    <trpc.Provider client={client} queryClient={qc}>
      <QueryClientProvider client={qc}>{children}</QueryClientProvider>
    </trpc.Provider>
  )
}
