// Generated by SKILL-NEXTJS (W6 #280). TRPC=on.
// Root tRPC router. Start here and compose sub-routers from feature
// folders (e.g. `server/routers/user.ts`).

import { initTRPC } from "@trpc/server"
import { z } from "zod"

const t = initTRPC.create()

export const appRouter = t.router({
  ping: t.procedure.query(() => ({ pong: Date.now() })),
  echo: t.procedure
    .input(z.object({ message: z.string().min(1).max(200) }))
    .mutation(({ input }) => ({ echoed: input.message })),
})

export type AppRouter = typeof appRouter
