#!/usr/bin/env bash
# Generated by SKILL-GO-SERVICE (X6 #302).
#
# Enforce the X1 software simulate-track Go coverage floor (70%).
# `go test` itself has no built-in `--fail-under` flag, so we parse
# `go tool cover -func=` output and exit non-zero when below the
# threshold. Matches `COVERAGE_THRESHOLDS["go"]` in
# backend/software_simulator.py.

set -euo pipefail

THRESHOLD="${COVERAGE_THRESHOLD:-70.0}"

go test -race -covermode=atomic -coverprofile=coverage.out ./...

total=$(go tool cover -func=coverage.out | awk '/^total:/ {gsub("%","",$3); print $3}')

awk -v t="$total" -v th="$THRESHOLD" '
  BEGIN {
    if (t + 0 < th + 0) {
      printf "coverage %.1f%% is below threshold %.1f%% (X1 Go floor)\n", t, th
      exit 1
    }
    printf "coverage %.1f%% meets threshold %.1f%%\n", t, th
  }
'
