"""Items CRUD tests — generated by SKILL-FASTAPI (X5 #301)."""

from __future__ import annotations

import pytest


@pytest.mark.asyncio
async def test_items_crud_roundtrip(client):
    created = await client.post(
        "/api/v1/items/",
        json={"name": "pilot", "description": "x5 smoke"},
    )
    assert created.status_code == 201, created.text
    item = created.json()
    assert item["name"] == "pilot"
    assert item["description"] == "x5 smoke"
    assert isinstance(item["id"], int)

    fetched = await client.get(f"/api/v1/items/{item['id']}")
    assert fetched.status_code == 200
    assert fetched.json()["id"] == item["id"]

    listed = await client.get("/api/v1/items/")
    assert listed.status_code == 200
    assert any(row["id"] == item["id"] for row in listed.json())


@pytest.mark.asyncio
async def test_item_missing_returns_404(client):
    response = await client.get("/api/v1/items/999999")
    assert response.status_code == 404
