// Generated by SKILL-ASTRO (W8 #282).
// GDPR Art. 17 — right-to-be-forgotten handler. Posts are forwarded
// to the backend; the backend is responsible for scrubbing across
// sub-processors and returning an audit trail. Exposed at
// POST /api/privacy/erasure.

import type { APIRoute } from "astro"

export const prerender = false

export const POST: APIRoute = async ({ request }) => {
  const backend = import.meta.env.PUBLIC_BACKEND_URL || "http://localhost:8000"
  const body = await request.text()
  const upstream = await fetch(`${backend}/api/v1/privacy/erasure`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body,
  })
  return new Response(await upstream.text(), {
    status: upstream.status,
    headers: { "Content-Type": "application/json" },
  })
}
